embrace-io/embrace-android-sdk

.github/workflows/release-workflow.yml
**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>
=> publishing dokka before setting next snapshot

.github/CODEOWNERS
Adding myself as a code owner for the API service so I don't need specific reviews from Fredric or Jamie - just a regular one - to make these changes. I promise to be good.
=> Add myself as a codeowner for the some files in the repo

embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/api/EmbraceApiServiceTest.kt
Validate payload of requests vs expected
=> Compare payloads in EmbraceApiServiceTest

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crash/EmbraceCrashService.kt
Documents our strategy for sending crashes, spun out of #56
=> Document crash sending strategy

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceSessionService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/SessionHandler.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/EmbraceSessionServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt
Moves the periodic caching functionality to the `SessionHandler` class.
=> Move periodic caching to SessionHandler

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/lifecycle/EmbraceProcessStateService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/EmbraceProcessStateServiceTest.kt
Detects when a process lifecycle state change is unbalanced. Theoretically the `androidx` library should not make unbalanced calls, but I'd like to confirm this hypothesis by logging an internal error that will show up in Grafana if the scenario does occur.
If an unbalanced call does occur for an `onForeground` event it may cause data loss as a new session will be created & the session ordinal incremented. Therefore I have only logged an internal error if this happens for the foreground lifecycle state change. 
=> Detect unbalanced process lifecycle calls

embrace-android-sdk/src/androidTest/assets/golden-files/session-end.json, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/metadata/EmbraceMetadataService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/metadata/MetadataUtils.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceExtensions.kt
Try to detect whether the running device is an emulator and improve the detection heuristic a bit
Modified functional test to expect this
=> Add isEmulator to app attributes logging

.github/workflows/generate_baseline_profile.yml, .github/workflows/publish-snapshot.yml
There were a few errors in the [workflows](https://github.com/embrace-io/embrace-android-sdk/tree/master/.github/workflows)
=> Fix baseline workflow

.github/workflows/release-workflow.yml
Change release workflow user for
=> Change the release workflow user

.github/workflows/release-workflow.yml
Create a release branch before releasing to avoid pushing changes directly to master.
=> Update release-workflow.yml to push to a release branch

.github/workflows/release-workflow.yml
Release workflow failed to push new version
=> Fix release-workflow.yml push next version

.github/workflows/generate_baseline_profile.yml
=> Update generate_baseline_profile.yml to use proper token

.github/workflows/release-workflow.yml
Using proper token in release workflow to push to master
=> Using proper token in release workflow to push to master

.github/workflows/publish-snapshot.yml
**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>
=> Fix Snapshot Workflow: Inherit token

embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EventSanitizerFacadeTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EventSanitizerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/NetworkUtilsTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/PerformanceInfoSanitizerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/PropertiesTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/SessionPerformanceInfoSanitizerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/SessionSanitizerFacadeTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/SessionSanitizerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/UserInfoSanitizerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/cpu/EmbraceCpuInfoDelegateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/crumbs/BreadcrumbsSanitizerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/crumbs/PushNotificationCaptureServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/metadata/EmbraceMetadataReactNativeTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/api/CachedConfigTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/config/ApplicationExitInfoRemoteConfigTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/config/local/ApplicationExitInfoLocalConfigTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/event/EmbraceRemoteLoggerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/EmbraceSerializerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/network/logging/EmbraceNetworkCaptureServiceTest.kt, test-server/src/main/kotlin/io/embrace/android/embracesdk/BaseTest.kt
Uses static imports in tests so our style remains consistent.
=> Use static imports in test

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/EmbraceBreadcrumbService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/event/EmbraceEventService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceWebViewServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/anr/AnrStacktraceSamplerTest.kt
Fixes various code smells that were causing compiler warnings.
=> Fix misc compiler warnings

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/connectivity/EmbraceNetworkConnectivityService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/powersave/EmbracePowerSaveModeService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceNetworkConnectivityServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbracePowerSaveModeServiceTest.kt
Adds some extra limits for data capture, so that the session payload isn't unbounded.
=> Add limits for data capture

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/Session.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceSessionService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/SessionHandler.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/SessionMessageCollator.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/EmbraceSessionServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt
Improves the log messages & moves them to the `SessionHandler` class where appropriate. I also took the chance to inline some functions that are no longer necessary in `SessionService`.
=> Improve logging in session service

embrace-android-sdk/src/androidTest/java/io/embrace/android/embracesdk/AnrIntegrationTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/anr/AnrStacktraceSampler.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crash/EmbraceCrashService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/LocalConfigParser.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/local/LocalConfig.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/remote/AppExitInfoConfig.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/EssentialServiceModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/AnrInterval.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/AnrSampleList.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/Crash.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/MemoryWarning.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/Session.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/extensions/AnrIntervalExt.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/extensions/AnrSampleListExt.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/extensions/CrashFactory.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/SessionHandler.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/SessionMessageCollator.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/AnrSampleListTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceCrashServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceGatingServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/LocalConfigTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/anr/AnrIntervalTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/anr/AnrStacktraceSamplerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/config/ApplicationExitInfoRemoteConfigTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/config/behavior/NetworkBehaviorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeAndroidResourcesService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSession.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/network/logging/EmbraceNetworkCaptureServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityServiceTest.kt
Attempts to extract some business logic that was present in the payload classes to separate classes/extension functions.
=> Extract business logic from payload classes

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crash/EmbraceCrashService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/ApiService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/EmbraceApiService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/DeliveryService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/ndk/EmbraceNdkService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceCrashServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeDeliveryService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeApiService.kt
Removes an unnecessary function in the `DeliveryService` by refactoring the `sendCrash` function.
=> Remove unnecessary sendEventAndWait function

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRuleExtensions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/BackgroundActivityTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeDeliveryService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityServiceTest.kt
Adds a basic integration test that asserts background activities are recorded.
=> Add integration test for background activity

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/ApiService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/EmbraceApiService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/DeliveryCacheManager.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryCacheManager.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/DeliveryModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceDeliveryCacheManagerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/api/EmbraceApiServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeApiService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeDeliveryCacheManager.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSession.kt
Uses streams when sending session HTTP requests. This should reduce memory usage.
=> Stream session HTTP requests

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/DeliveryCacheManager.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryCacheManager.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeDeliveryCacheManager.kt
Streams http requests that send background activities.
Relied on existing test coverage + manual testing.
=> Stream background activity requests

embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EventSanitizerFacadeTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/PerformanceInfoSanitizerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/SessionPerformanceInfoSanitizerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/SessionSanitizerFacadeTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/anr/detection/LivenessCheckSchedulerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/anr/detection/TargetThreadHandlerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/metadata/EmbraceMetadataReactNativeTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/event/EmbraceEventServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/event/EmbraceRemoteLoggerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/event/EventHandlerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakePerformanceInfo.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/serialization/EmbraceSerializerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt
Removes some obviously unnecessary uses of mocks from within the tests.
=> Avoid tests using mocks

embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceAnrServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceCrashServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceDeliveryCacheManagerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceMemoryServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceNetworkConnectivityServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbracePowerSaveModeServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceWebViewServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeDeliveryService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/PerformanceInfoTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/anr/detection/BlockedThreadDetectorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/anr/detection/LivenessCheckSchedulerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/anr/detection/UnbalancedCallDetectorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/memory/ComponentCallbackServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/metadata/EmbraceMetadataServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/event/EmbraceRemoteLoggerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/event/EventHandlerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeBlockedThreadListener.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeEventService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeMemoryService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/ndk/EmbraceNdkServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/network/logging/EmbraceNetworkCaptureServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/network/logging/NetworkCaptureEncryptionManagerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt
Refactors some additional tests that were using mocks to replace them with fakes where possible.
=> Refactors more tests to replace mocks with fakes.

embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceCrashServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeBreadcrumbService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeNdkService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeSessionService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/NativeThreadSamplerInstallerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/metadata/EmbraceMetadataUnityTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeAnrService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeCoreModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/ndk/EmbraceNdkServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/network/logging/EmbraceNetworkCaptureServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityServiceTest.kt
Removes some additional uses of mocks in the unit tests.
=> Reduce mock usage

.github/workflows/generate_baseline_profile.yml
Use the new baselineProfile build type to generate baseline profiles
=> Update buildType for baseline profile

buildSrc/build.gradle.kts
Update detekt version used by the build plugin
=> The version of detekt applied by the build plugin was not updated

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/CacheService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceCacheService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceCacheServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/TestCacheService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeCacheService.kt
- Removed unused methods from CacheService. 
=> Remove unused methods from CacheService

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/ReactNativeInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/metadata/EmbraceMetadataService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/webview/EmbraceWebViewService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/SessionHandler.kt
Remove unnecessary dev logging
=> Remove unnecessary dev logging

embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceConfigServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceInternalInterfaceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeBreadcrumbService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/crumbs/PushNotificationCaptureServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/metadata/EmbraceMetadataServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/api/EmbraceApiServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeEventService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeNetworkCaptureService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeOrientationService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/logging/InternalErrorLoggerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/ndk/EmbraceNdkServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/network/logging/EmbraceNetworkCaptureServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/network/logging/EmbraceNetworkLoggingServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/ActivityLifecycleTrackerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/BackgroundActivityCollatorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt
Removes some additional mocks that can be implemented with fakes instead.
=> Remove additional mocks

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/worker/WorkerThreadModule.kt
Adds some docs that explain what each executor is currently responsible for.
=> Add docs for what each executor does

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/Session.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/BackgroundActivityCollator.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/SessionMessageCollator.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeConfigService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSession.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/BackgroundActivityCollatorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt, embrace-android-sdk/src/test/resources/breadcrumb_custom.json, embrace-android-sdk/src/test/resources/breadcrumb_empty.json, embrace-android-sdk/src/test/resources/breadcrumb_fragment.json, embrace-android-sdk/src/test/resources/breadcrumb_view.json, embrace-android-sdk/src/test/resources/breadcrumb_view_custom.json, embrace-android-sdk/src/test/resources/breadcrumb_webview.json, embrace-android-sdk/src/test/resources/session_message_expected.json, embrace-android-sdk/src/test/resources/session_stacktrace_symbols.json
Increases test coverage for the BackgroundActivityService class & moves some constants to a consistent location.
=> Enhance background activity service test coverage

embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/UnityInternalInterface.kt
Make the internal Unity interface methods callable from Kotlin
=> Make internal Unity interface public so it can be called from Kotlin

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityServiceTest.kt
This changeset simplifies how the background activities are cached, while not making any changes to the underlying persistence mechanism. Rather than posting a runnable to the main thread to schedule a worker, now the SDK will just schedule a task with an appropriate delay.
=> Simplify how background activities are saved

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityService.kt
Rename some functions in the background activity & alter how they are ordered. No functional changes
=> Rename and reorder background activity functions

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceSessionService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/PayloadMessageCollator.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadMessageCollatorTest.kt
Renames a few functions for greater consistency with how the session building functions work. Additionally this simplifies the code so that the function that creates the `BackgroundActivity` is now hidden, similarly to how construction of sessions behave.
=> Rename & hide payload creation functions

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryCacheManager.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceSessionService.kt
Adding traces for benchmarking tests
=> Add traces to measure session serialization and caching

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceSessionService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/FinalEnvelopeParams.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/PayloadMessageCollator.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadMessageCollatorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt
Creates a class that holds the parameters used to create the final session/BA objects. I also consolidated some null checks & data population within `PayloadMessageCollator`.
=> Create final envelope params class

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceSessionService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt
Inlines some functions & renames another.
=> Reorder functions and make private

.github/workflows/release-workflow.yml
we need to checkout the sdk and run the release from there
**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>
=> embr-627 we need to checkout the sdk and run the release from there

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceSessionService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/SessionService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeNdkService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeSessionService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/EmbraceSessionServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorTest.kt
Extracts user info clearing to the `SessionOrchestrator`.
=> Extract how user info is cleared

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceSessionService.kt
Parameterises session delivery in SessionService, avoiding unnecessary duplication.
=> Parameterise session delivery in SessionService

embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/UninitializedSdkInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/EmbraceInternalInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/InternalTracingApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceTracer.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/InternalTracer.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceInternalInterfaceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/UninitializedSdkInternalInterfaceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/InternalTracerTest.kt
Add implementation of internal tracing API so hosted SDKs can work with traces
Added components tests
=> Create internal tracing interface and implementation

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/BackgroundActivityService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeBackgroundActivityService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityServiceTest.kt
Removes some dead code from the `BackgroundActivityService` that is only called from tests.
=> Remove dead code from background activity service

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceSessionService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/caching/PeriodicSessionCacher.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeSessionModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/EmbraceSessionServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt
Extracts the periodic caching of sessions to a separate class. This will make its eventual removal easier.
=> Extract periodic caching to separate class

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/orchestrator/OrchestratorBoundaryDelegate.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorTest.kt
Creates a delegate for cleaning the session/background activity boundary.
=> Create delegate for session orchestrator

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/InternalTracingApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/InternalTracer.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/UninitializedSdkInternalInterfaceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/InternalTracerTest.kt
Add more docs and improve validation of the map containing the data for a prospective event
=> Add in better documentation and validation for internal tracing impl

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceSessionService.kt
Inlines a function in `SessionService`.
=> Inline a function in SessionService

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceBackgroundActivityService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/EmbraceSessionService.kt
Inlines some functions & parameterises the timestamp calculation.
=> Inline functions + parameterise timestamp

gradle.properties
Revert inadvertent change to version caused by a failed CI job
=> Revert change that makes the publishing fail

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt
Add integration test for the internal tracing API exposed for the hosted SDKs
=> Add integration tests for internal tracing API

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorImpl.kt
Refactors SessionOrchestratorImpl to create a transitionState function that models the logic required for each state transition. This makes it less likely we will forget to perform a step if we ever need to add an extra transition in future, and makes the code easier to read.
=> Create transitionState function

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/lifecycle/ProcessState.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/orchestrator/OrchestratorTerminationConditions.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorImpl.kt
Extracts early termination business logic from the orchestrator class as it was growing fairly large & this felt like a natural fit to move into a separate source file.
=> Extract termination logic from orchestrator

.github/workflows/pre-release-workflow.yml, .github/workflows/release-workflow.yml
so this is temporary. I messed up on previous release, so we now need to create the same RC as before. We will revert these changes once 6.3.0 is out
**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>
=> Perform 6.3.0 again. Temporary change

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/InitModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeInitModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/InitModuleImplTest.kt
Clean up FakeInitModule to reduce duplication between it and the real thing.
=> Remove duplication in FakeInitModule

buildSrc/src/main/kotlin/io/embrace/gradle/InternalEmbracePlugin.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/UninitializedSdkInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/ViewSwazzledHooks.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/metadata/MetadataUtils.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/AndroidServicesModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/EssentialServiceModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/EmbraceInternalInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/prefs/EmbracePreferencesService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/samples/ComparableVersion.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/lifecycle/EmbraceProcessStateService.kt, embrace-android-sdk/src/test/java/com/android/server/os/TombstoneProtos.java, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceDeliveryCacheManagerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/UninitializedSdkInternalInterfaceImplTest.kt
Resolves & suppresses a couple of compiler warnings that were cluttering up the build log.
=> Address compiler warnings

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRuleExtensions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/BackgroundActivityTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/CrashSessionTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/NetworkRequestApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/DeliveryCacheManager.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/DeliveryService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryCacheManager.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/StorageModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/PayloadFactory.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/PayloadFactoryImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceDeliveryCacheManagerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeDeliveryService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakePayloadFactory.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeDeliveryCacheManager.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadFactoryBaTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadFactorySessionTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorTest.kt
Hoists up session delivery to the session orchestration class. This simplifies the delivery logic so that all session message persistence is routed through one function.
=> Hoist up session delivery to session orchestration class

.github/workflows/ci-gradle.yml, .github/workflows/functional-tests.yml, .github/workflows/generate_baseline_profile.yml, .github/workflows/pre-release-workflow.yml, .github/workflows/publish-snapshot.yml, .github/workflows/release-workflow.yml
Updates CI with latest dependabot version bumps.
=> Update CI versions

.github/workflows/create-release-branch.yml, .github/workflows/pre-patch-workflow.yml, .github/workflows/release-workflow.yml
Workflow to create a patch RC based on an existing release branch
=> Create patch workflow

.github/workflows/create-release-branch.yml, .github/workflows/pre-patch-workflow.yml, .github/workflows/pre-release-workflow.yml
Stage the changed properties file so there's something to commit
=> Stage changes before commiting

.github/workflows/ci-gradle.yml, .github/workflows/functional-tests.yml, .github/workflows/generate_baseline_profile.yml, .github/workflows/pre-release-workflow.yml, .github/workflows/publish-snapshot.yml
Builds with JDK 17 by default instead of 11. This should get us all the perf improvements that have happened over the years.
=> Build with JDK 17 by default

.github/workflows/ci-gradle.yml, .github/workflows/functional-tests.yml, .github/workflows/generate_baseline_profile.yml, .github/workflows/pre-release-workflow.yml, .github/workflows/publish-snapshot.yml, build.gradle, buildSrc/src/main/kotlin/io/embrace/gradle/InternalEmbracePlugin.kt
Fixes two warnings in the build script: one about a deprecated detekt API, and another around eager registration of a task.
=> Fixes two build warnings

.github/workflows/ci-gradle.yml, .github/workflows/functional-tests.yml, .github/workflows/generate_baseline_profile.yml, .github/workflows/pre-release-workflow.yml, .github/workflows/publish-snapshot.yml, build.gradle, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/embrace/gradle/InternalEmbracePlugin.kt, buildSrc/src/main/kotlin/io/embrace/gradle/Versions.kt
Updates the binary compatibility validator plugin to the latest version.
=> Update api check plugin

.github/workflows/ci-gradle.yml, .github/workflows/functional-tests.yml, .github/workflows/generate_baseline_profile.yml, .github/workflows/pre-release-workflow.yml, .github/workflows/publish-snapshot.yml, build.gradle, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/embrace/gradle/InternalEmbracePlugin.kt, buildSrc/src/main/kotlin/io/embrace/gradle/Versions.kt
Updates dokka to the latest version.
=> Update dokka to latest version

.github/workflows/ci-gradle.yml, .github/workflows/create-release-branch.yml, .github/workflows/functional-tests.yml, .github/workflows/generate_baseline_profile.yml, .github/workflows/pre-patch-workflow.yml, .github/workflows/pre-release-workflow.yml, .github/workflows/publish-snapshot.yml, .github/workflows/release-workflow.yml
Updates github actions to use the latest dependabot PRs.
=> Update github actions with version bumps

embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSpansService.kt
Adds a fake for the spans service for use in testing.
=> Add fake for spans service

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/DataCaptureOrchestrator.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/DataSourceState.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/SessionType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/orchestrator/OrchestratorBoundaryDelegate.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/DataCaptureOrchestratorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/DataSourceStateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadMessageCollatorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/OrchestratorBoundaryDelegateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorTest.kt
Renames envelope type to session type as discussed internally.
=> Rename envelope type to session type

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapperTest.kt
Initialize and hook up modules in a separate component so that we can move EmbraceImpl's code into Kotlin piecemeal.
Existing tests pass
=> Consolidate modules init in separate component

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/InitModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpansService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceTracer.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/SpansService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/SpansServiceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/UninitializedSdkSpansService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSpansService.kt
Tweak dependency to simplify the dep graph
=> Make EmbraceTracer not depend on SpansRepository

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/InternalInterfaceModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/UninitializedSdkInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/InitModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/InternalTracer.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceInternalInterfaceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/UninitializedSdkInternalInterfaceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/InternalTracerTest.kt
Initialize `InternalTracer` in a module so we never have dupes
=> Initialize InternalTracer as singleton

embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceInternalInterfaceImplTest.kt
=> Unused import removal so CI doesn't yell at me

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/ApiClient.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/ApiClientImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/ApiService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/EmbraceApiService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/SerializationAction.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/CacheService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/DeliveryCacheManager.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceCacheService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryCacheManager.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbracePendingApiCallsSender.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/PendingApiCallsSender.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/behavior/DataCaptureEventBehavior.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/behavior/LogMessageBehavior.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/behavior/NetworkSpanForwardingBehavior.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/behavior/SdkEndpointBehavior.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/behavior/StartupBehavior.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/behavior/UnimplementedConfig.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/behavior/WebViewVitalsBehavior.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/utils/Types.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/TestCacheService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/EmbracePendingApiCallsSenderTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeApiClient.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeApiService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeCacheService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeDeliveryCacheManager.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakePendingApiCallsSender.kt
Consolidate type aliases into a single file
=> Consolidate type aliases into a single file

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt
Tweak flakey test to provide better info to help diagnose failing condition
=> Tweak flakey test to give us more info at failure time

embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/integrationTest/java/io/embrace/android/embracesdk/NullParametersTest.java, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceTracer.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/SpansService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/spans/TracingApi.kt
Expose getSpan with a spanId in the public API
=> Add getSpan to public API

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/Systrace.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/SystraceTest.kt
Provide more details about SDK startup by adding synchronous traces in various parts.
=> Add system tracing for SDK startup workflow

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapper.kt
Do all the service registration in ModuleInitBoostrapper and reordered some of the registration or post-instantiation init activities to do them as soon as the services are ready.
Covered by existing tests
=> Move and reorder service registration to ModuleInitBootstrapper

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/DataSource.kt
Converts an interface to a typealias.
=> Convert interface to typealias

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/SpansServiceImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt
Only check the total number of spans in a session when apply limits
=> Change per-session limits for spans started to 500 overall

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/BreadcrumbDataStore.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/BreadcrumbService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/EmbraceBreadcrumbService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/ViewBreadcrumbDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/ViewBreadcrumb.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeBreadcrumbService.kt
Extracts the capture of view breadcrumbs out to a separate class. 
=> Extract view breadcrumb data capture

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/logs/LogPayload.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/Envelope.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/EnvelopeMetadata.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/EnvelopeResource.kt
- Added `Envelope` data class and the related classes needed to produce a payload for Logs. 
- This might be replaced once the OpenApi work is done. 
They are all data classes that don't need to be tested until we start using them.
=> Add envelope for new endpoints.

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.java
We were needlessly initializing the internal interfaces for all frameworks, but we can ever have one, so just do the init for the framework in use - or none at all if we are not running in a hosted SDK environment.
Will be added later
=> Only initialize internal interface for the current framework

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/BreadcrumbService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/EmbraceBreadcrumbService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/FragmentBreadcrumbDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/FragmentBreadcrumb.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/PayloadMessageCollator.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeBreadcrumbService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FragmentBreadcrumbTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/crumbs/EmbraceBreadcrumbServiceTest.kt
Extracts the capture of fragment breadcrumbs from the breadcrumb service.
=> Extract fragment breadcrumb capture

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/DataCaptureOrchestrator.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/DataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/DataSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/DataSourceState.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/EventDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/LogDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/SpanDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/SpanDataSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/destination/LogWriter.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/destination/SessionSpanWriter.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/destination/SpanAttributeData.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/destination/SpanAttributeMapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/destination/SpanEventData.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/destination/SpanEventMapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/DataSourceModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpan.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/DataCaptureOrchestratorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/DataSourceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/DataSourceStateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/SpanDataSourceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/SpanDataSourceKtTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeCurrentSessionSpan.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeDataSource.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorTest.kt
Reorganises some of the recently added files so they are in more specific packages.
=> Reorganise source files

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/destination/LogWriter.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/destination/LogWriterImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/OpenTelemetryModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeTracingApi.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/OpenTelemetryModuleImplTest.kt
Add a placeholder implementation for the `LogWriter` class.
=> Add empty implementation for log writer

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryCacheManager.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/OpenTelemetryModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/opentelemetry/OpenTelemetrySdk.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/caching/PeriodicSessionCacher.kt
Add more trace sections to further break down startup. Make the async sections synchronous so it shows up better stacked in their running threads
=> Add more trace sections to the startup flow

embrace-android-sdk/src/main/cpp/file_writer.c
Extracts the JSON serialization in the NDK code into separate functions so that its easier to modify & read upcoming reviews. There are no functional changes associated with this PR.
Regression tested NDK test-suite app manually by confirming crash reports are still parsed in the happy path.
=> Extract separate functions for JSON serialization

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/InternalTracer.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/InternalTracerTest.kt
For the internal tracing API, look for the old attribute value for a timestamp in nanos and use it (after converting to millis) if the appropriate attribute in millis isn't specified
Added tests at all layers
=> Convert time not in millis for span events

.github/workflows/create-release-branch.yml, .github/workflows/pre-patch-workflow.yml, .github/workflows/release-workflow.yml
Update workflows to use JDK 17
=> Update JDK used in release workflows

embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeOtelLogger.kt
Adds a fake implementation of an OTel logger that will be used in future tests.
=> Add fake implementation of OTel logger

embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/crumbs/EmbraceBreadcrumbServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeLogRecordData.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/OpenTelemetryModuleImplTest.kt
Fixes some compiler warnings that have been introduced recently.
=> Resolve some compiler warnings

embrace-android-sdk/src/androidTest/assets/golden-files/session-end.json, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/OtelSessionGatingTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/gating/SpanSanitizer.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceExtensions.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/startup/StartupServiceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fixtures/SpansTestFixtures.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceTracerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/InternalTracerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/SpanServiceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt, embrace-android-sdk/src/test/resources/span_expected.json
**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>
=> Change span type and names to fit with convention

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/ApiRequestMapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/ApiService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/EmbraceApiService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/EmbraceUrl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/Endpoint.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/DeliveryService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/PendingApiCalls.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/Envelope.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/serialization/EmbraceSerializer.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/session/SessionPayload.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeDeliveryService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/api/ApiRequestMapperTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/api/EmbraceApiServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/PendingApiCallsTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeApiService.kt
Added necessary code to send envelopes to the correct API
https://www.notion.so/embraceio/1-1-Delivery-Layer-Can-Consume-new-payload-a8eb354f44984434bb0d136b98b1ea08?pvs=23
=> Added the API for sending envelopes in the EmbraceApiService

embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/InternalTracingApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/InternalTracer.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/spans/EmbraceSpan.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeEmbraceSpan.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/InternalTracerTest.kt
stopSpan can be called with a specific end time
Appropriate tests added
=> Add the ability for the internal stopSpan API method to be called with a specific end time

.github/workflows/pre-release-workflow.yml
Update git command to set upstream
Eff it, we're doing it live.
=> Fix branch cut workflow git command

gradle.properties
Fix version number mangled by the pre-release branching workflow
=> Fix version number in properties file

.github/workflows/release-workflow.yml
It worked! https://github.com/embrace-io/embrace-android-sdk/actions/runs/8173033145/job/22344565420
=> Update release-workflow.yml to use JDK 17

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/envelope/SessionEnvelopeSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/envelope/session/SessionPayloadSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/envelope/session/SessionPayloadSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/ApiRequestMapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/ApiService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/EmbraceApiService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/DeliveryService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/SessionPayload.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeDeliveryService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/api/EmbraceApiServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeApiService.kt
Moves a class in the new envelope to the same package as all the others.
=> Move session envelope class

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/Log.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/LogBody.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/LogPayload.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/SessionPayload.kt
Copies remaining parts from the OpenAPI generated-code to the new payload classes.
=> Add remaining parts to new payload

.github/CODEOWNERS
Put me as code owner in RNInterface
=> Updating Codeowner for RN interface

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/SharedObjectLoader.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/ndk/EmbraceNdkService.kt
Add more tracing for what the NDK service is doing.
=> Add NDK service tracing

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/EmbraceApiService.kt
Fix bad merge introduced by not rebuilding after accepting change suggestions via GitHub
=> Fix bad merge thanks to..., well, me

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/PayloadModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/utils/Types.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeOpenTelemetryModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapperTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/PayloadModuleImplTest.kt
Creates a payload module that is responsible for creating classes that generate the new payload. This is hooked up but these objects are never instantiated are used right now.
=> Create payload module

.github/workflows/stale.yaml
=> GHA worflows - Use common actions

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/CacheService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceCacheService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeCacheService.kt
Just some formatting changes I don't want to mess up later diffs
=> Simple reordering of methods in interface and impls before bigger change

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceCacheService.kt
Make the logic to safely write and overwrite session files generic so other disk write methods can leverage them.
Existing session tests cover this change
=> Extract safe-write logic from session writing path so it can be reused

embrace-android-sdk/src/androidTest/java/io/embrace/android/embracesdk/BaseTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/Endpoint.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/api/ApiRequestMapperTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/api/EmbraceApiServiceTest.kt
Alters the new endpoint as we decided to rename it.
=> Alter new session endpoint

embrace-android-sdk/src/androidTest/assets/golden-files/session-end.json
Forgot to update the JSON in function tests say validate the spans in the payload
=> Fix expected JSON for functional tests

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/AeiFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/CustomBreadcrumbFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/FragmentBreadcrumbFeatureTest.kt
Adds integration tests for custom breadcrumbs, view breadcrumbs, and AEI. These will help us assert that functionality is still working as expected when migrating features to OTel.
=> Add integration tests for features

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImplTest.kt
Add more unit tests since I can't do more complicate validation in the integration tests
=> Improve snapshot unit tests to be more comprehensive before we can add integration tests

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/envelope/log/LogEnvelopeSourceImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/envelope/log/LogEnvelopeSourceImplTest.kt
- Add version and type for Log envelope.
Relied on existing tests.
=> Add version and type for Log envelope.

embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/EmbraceAttributeExtensions.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSpanData.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/payload/SpanMapperTest.kt
Bulked up FakeSpanData so that it can produce more realistic fakes with consistent data. Also added some helpers that produces fakes that are appropriate for snapshots.
=> Tweak span tests and infra

embrace-android-sdk/src/main/cpp/sampler/stacktrace_sampler.c
Creates an [alternative signal stack](https://man7.org/linux/man-pages/man2/sigaltstack.2.html) when sampling the Unity thread. By default, signal handlers run on the current thread's stack. If this stack overflows then we can't sample the Unity thread & we'll likely get a random segfault. This is something that our signal handler for crashes already does.
Manually verified that stacktraces are still captured.
=> Setup alternative signal stack when sampling native thread

embrace-android-sdk/src/main/cpp/sampler/stacktrace_sampler.c
Adds a bounds check for the unlikely scenario where an index exceeds the bounds of its array.
Manually verified that stacktraces are still captured.
=> Add bounds check for current sample

buildSrc/src/main/kotlin/io/embrace/gradle/Versions.kt, embrace-android-sdk/build.gradle, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/opentelemetry/OpenTelemetryAttributeKeys.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/opentelemetry/OpenTelemetrySdk.kt
Use OTel semantic conventions directly
=> Add workaround to mirror OTel semantics convention tooling usage

config/detekt/detekt.yml, embrace-android-compose/src/main/java/io/embrace/android/embracesdk/compose/internal/EmbraceNodeIterator.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/UninitializedSdkInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/ViewSwazzledHooks.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/BreadcrumbService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/EmbraceBreadcrumbService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/TapBreadcrumbDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/EmbraceInternalInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/TapBreadcrumb.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceGatingServiceV1PayloadTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeBreadcrumbService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/crumbs/EmbraceBreadcrumbServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/payload/TapBreadcrumbTest.kt
Use kotlin.Pair instead of android.util.Pair
unit testing
=> replace android.util.Pair

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SpanTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/InitModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/OpenTelemetryModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/IdGenerator.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceExtensions.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanProcessor.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/opentelemetry/OpenTelemetryConfiguration.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/InitModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/IdGeneratorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/network/EmbraceNetworkRequestTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/opentelemetry/OpenTelemetryConfigurationTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/opentelemetry/OpenTelemetrySdkTest.kt
Add a unique ID to every app instance start for easier tracking of related sessions
=> Attach app instance ID to each Span

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/EmbType.kt
Changed this per slack discussion
=> Change the emb.type of breadrumbs to sys.breadcrumb

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/EmbType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/SchemaType.kt
Defines the OTel schema that will be used for capturing ANRs.
=> Define OTel schema for capturing ANRs

embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/anr/EmbraceAnrServiceRule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/anr/EmbraceAnrServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/anr/EmbraceAnrServiceTimingTest.kt
Moves ANR tests to the correct package.
=> Move ANR tests to correct package

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/CustomerLogModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/DataContainerModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/EssentialServiceModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/PayloadModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/utils/Types.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/ndk/NativeModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EssentialServiceModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeEssentialServiceModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/CustomerLogModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/DataContainerModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/ndk/NativeModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionModuleImplTest.kt
Initialize EmbraceSessionProperties as part of the Essential Services Module
=> Move init of EmbraceSessionProperties to essential services module

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/SessionPropertiesTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/envelope/session/SessionPayloadSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/session/SessionPropertiesDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/PayloadModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/utils/Types.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/V1PayloadMessageCollator.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/properties/EmbraceSessionPropertiesService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/properties/SessionPropertiesService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeSessionPropertiesService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/envelope/session/SessionPayloadSourceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/PayloadModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/properties/EmbraceSessionPropertiesServiceTest.kt
Populate the session span with the current set session properties.
Add integration test to verify that this works end to end.
=> Set session properties on session span on init

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/UserFeaturesTest.kt
Integration tests for v1 session payload for user info. Need to switch to v2 when that is hooked up.
=> Create integration tests for v1 payload for user info

embrace-android-sdk/src/androidTest/java/io/embrace/android/embracesdk/BaseTest.kt, embrace-android-sdk/src/androidTest/java/io/embrace/android/embracesdk/SessionSpanTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/ConfigService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/EmbraceConfigService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/behavior/OTelBehavior.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/behavior/SessionBehavior.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/remote/OTelConfig.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/remote/OTelRemoteConfig.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/remote/RemoteConfig.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/remote/SessionRemoteConfig.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/logs/CompositeLogService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/PayloadFactoryImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/config/behavior/OTelBehaviorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/config/behavior/SessionBehaviorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/BehaviorFakes.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeConfigService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/logs/CompositeLogServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/PayloadFactoryImplTest.kt
- Created a new remote config for OTel feature flags.
- Created 3 feature flags:
- dev
- beta
- stable
=> Create new remote config for OTel feature flags.

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/EmbType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/opentelemetry/EmbraceAttributeKeys.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/opentelemetry/OpenTelemetryAttributeKeys.kt
Add the proposed new attributes to be used the crash and native crash OTel logs.
=> Definition of attributes for ART and Native crashes

embrace-android-sdk/src/main/cpp/unwinders/stack_unwinder.cpp
A C++ termination handler does not have any value available for `user_context` so we pass `nullptr`. However, the signal handler appears to return early if `NULL` is present. I'm not entirely sure how we are getting a stacktrace because of this (possibly we fallback to the C signal handler), but thought it would be sensible to default to using the current register values as a starting point for unwinding. 
Compared two symbolicated stacktraces & checked they appeared the same for `throw std::runtime_error("My C++ exception");`.
[old_stacktrace.log](https://github.com/embrace-io/embrace-android-sdk/files/14871850/old_stacktrace.log)
[new_stacktrace.log](https://github.com/embrace-io/embrace-android-sdk/files/14871851/new_stacktrace.log)
=> Use local register values when user context is null

embrace-android-sdk/src/integrationTest/java/io/embrace/android/embracesdk/PreSdkStartTest.java, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRuleExtensions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/AeiFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/FragmentViewFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/PersonaFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/UserFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/BackgroundActivityTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/ManualSessionTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/MomentBoundaryTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/OtelSessionGatingTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/PeriodicSessionCacheTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/NetworkRequestApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SpanTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt
Renaming some parameters in the test harness to prepare for a bigger refactor
=> Refactor test rule to simplify init

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/PersonaFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/UserFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt
Removed a bunch of overriddable modules that are only that way because we need to feed in a config service provider to the essential services module
Existing tests passes
=> Simply the initialization of the integration test harness

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/limits/OnOffLimitStrategy.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/EmbType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/SchemaType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crash/CrashDataSource.kt
The start of the Crash Data Source implementation. This is not done but should give a good start in migration.
Will merge this WIP since it's not hooked up so this can be worked on by Lucas.
=> Start implementation of Crash DataSource

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/startup/AppStartupTraceEmitter.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/startup/AppStartupTraceEmitterTest.kt
Make startup traces visible as a replacement for the startup moment span
=> Make startup traces public

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/AeiFeatureTest.kt
=> Fix integration test

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/aei/AeiDataSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crash/CrashDataSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/CrashModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/crash/CrashFileMarker.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/crash/CrashFileMarkerImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/utils/EncodingExtensions.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/utils/Types.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/ndk/EmbraceNdkService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceCrashServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/crash/CrashDataSourceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeCrashFileMarker.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeCrashModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/CrashModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/crash/CrashFileMarkerImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/crash/LastRunCrashVerifierTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/ndk/EmbraceNdkServiceTest.kt
- Encoded attributes to UTF8 String as we do in AEI.
- Moved function bytesToUTF8String to a separate file so it could be used by crash and others. 
=> Encode some Crash Attributes to UTF8 String.

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crash/CrashDataSourceImpl.kt
- Fix serialization of some crash attributes.
=> Fix crash attributes serialization.

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/TelemetryAttributes.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/DataSourceModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/utils/Types.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeDataSourceModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/CrashModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/DataSourceModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionModuleImplTest.kt
Just a bunch of formatting/cleanup changes that I don't want to discard
=> Misc fixes to files that I did not end up materially modifying

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/EmbType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceExtensions.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/ndk/NativeCrashDataSource.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeNdkService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fixtures/LogTestFixtures.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/ndk/NativeCrashDataSourceImplTest.kt
**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>
=> Add native crash datasource

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/network/logging/EmbraceNetworkLoggingService.kt
Delete getNetworkCallsSnapshot, and some private variables used by it.
=> Remove getNetworkCallsSnapshot, as we won't be using it anymore

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/CustomerLogModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/network/logging/DomainCountLimiter.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/network/logging/EmbraceDomainCountLimiter.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/network/logging/EmbraceNetworkLoggingService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeDomainCountLimiter.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSpanService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/network/logging/EmbraceNetworkLoggingServiceTest.kt
Added unit tests for EmbraceNetworkLoggingService
Many of the existing tests will be moved to the DomainCountLimiter tests in a following PR
=> Fixed tests for EmbraceNetworkLoggingService

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/network/logging/EmbraceDomainCountLimiter.kt
Added locks to synchronize access to DomainCountLimiter, also replaced a normal map with a Concurrent one.
=> Modified EmbraceDomainCountLimiter to make it thread safe

embrace-android-sdk/src/androidTest/assets/golden-files/log-error-event.json, embrace-android-sdk/src/androidTest/assets/golden-files/log-error-with-exception-and-message-event.json, embrace-android-sdk/src/androidTest/assets/golden-files/log-error-with-exception-event.json, embrace-android-sdk/src/androidTest/assets/golden-files/log-error-with-property-event.json, embrace-android-sdk/src/androidTest/assets/golden-files/log-info-event.json, embrace-android-sdk/src/androidTest/assets/golden-files/log-info-with-property-event.json, embrace-android-sdk/src/androidTest/assets/golden-files/log-warning-event.json, embrace-android-sdk/src/androidTest/assets/golden-files/session-end-v2.json, embrace-android-sdk/src/androidTest/java/io/embrace/android/embracesdk/BaseTest.kt, embrace-android-sdk/src/androidTest/java/io/embrace/android/embracesdk/SessionSpanTest.kt
Updates the assertions in the functional tests so that they are asserting against the correct payloads now that we're sending v2 logs by default.
=> Fix failures in functional tests

embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/envelope/resource/EnvelopeResourceSourceImplTest.kt
Version can NOT be fixed in a unit test
=> envelope can't verify version

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/destination/LogWriterImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/EmbType.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/destination/LogWriterImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/ndk/NativeCrashDataSourceImplTest.kt
Cherry picking #783, #785 into 6.6
=> Release cherry picks

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlConnectionDelegate.java
Cherrypicking commits in #787  to release branch
=> Cherrypick to network logging fixes to release branch

.github/workflows/build-rc-workflow.yml
**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>
=> Revert "Use macos to run the rc workflow"

.github/workflows/build-rc-workflow.yml
Try to skip check before publishing
=> skip check

.github/workflows/pre-release-swazzler.yml
Workflow to create swazzler release branch
=> Temporary workflow to create swazzler release branch

.github/workflows/pre-release-swazzler.yml
=> Fix swazzler branching workflow

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/EmbType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/SchemaType.kt
- Added EmbType and SchemaType for WebViewInfo.
- DataSource will be added in future PRs.
- Will be covered when testing the data source in future PRs
=> Add EmbType and SchemaType for WebViewInfo.

gradle.properties
=> Fix SDK version

embrace-android-sdk/src/test/resources/session_config.json
Removing unused values form expected json file.
Unit test.
=> Update test expected file

embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/SdkStateApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegateTest.kt
Extract SDK state functions to a delegate.
=> Extract sdk state functions to delegate

embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/NetworkRequestApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/SdkStateApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/NetworkRequestApiDelegate.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/NetworkRequestApiDelegateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegateTest.kt
Extracts a few more network calls functions into an api delegate
=> Extract network calls into api delegate

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/BreadcrumbApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/BreadcrumbApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeBreadcrumbService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/BreadcrumbApiDelegateTest.kt
Adds a delegate for the breadcrumb API.
=> Add breadcrumb delegate

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/WebViewApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/WebViewApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeBreadcrumbService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeWebViewService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeDataCaptureServiceModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/WebViewApiDelegateTest.kt
Adds a delegate for the webview API.
=> Webview API delegate

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRuleExtensions.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/AndroidServicesModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/CoreModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/CrashModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/CustomerLogModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/DataCaptureServiceModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/DataSourceModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/DeliveryModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/EssentialServiceModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/InitModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/StorageModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/utils/Types.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/ndk/NativeModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeCoreModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/CoreModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/CrashModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/DeliveryModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/InitModuleImplTest.kt
Moving EmbraceSerializer up to the InitModule so that it can be used in OpenTelemetryModule
Moved existing tests
=> Move EmbraceSerializer to InitModule

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRuleExtensions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/PersonaFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/UserFeaturesTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/gating/SessionSanitizerFacade.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/SessionMessage.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/V1PayloadMessageCollator.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceGatingServiceV1PayloadTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeBackgroundActivity.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/SessionSanitizerFacadeTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/payload/BackgroundActivityMessageTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/payload/SessionMessageTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadFactoryBaTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/V1PayloadMessageCollatorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/PayloadFactoryImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/V2PayloadMessageCollatorTest.kt, embrace-android-sdk/src/test/resources/bg_activity_message_expected.json, embrace-android-sdk/src/test/resources/session_message_expected.json, embrace-android-sdk/src/test/resources/v1_session_expected.json
Removes the legacy user info field & migrates tests to the new one. This is targeting an integration branch so won't be merged down to master just yet.
Updated existing test coverage
=> Remove legacy user info field

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRuleExtensions.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/SessionMessage.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/V1PayloadMessageCollator.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/V2PayloadMessageCollator.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeBackgroundActivity.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/SessionSanitizerFacadeTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/payload/BackgroundActivityMessageTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/payload/SessionMessageTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadFactoryBaTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadFactorySessionTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/V1PayloadMessageCollatorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/PayloadFactoryImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/V2PayloadMessageCollatorTest.kt, embrace-android-sdk/src/test/resources/bg_activity_message_expected.json, embrace-android-sdk/src/test/resources/session_message_expected.json
Removes the legacy device info field. This is targeting an integration branch so won't be merged down to master just yet.
=> Remove device info field

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/AttributeExtensions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/SpanAssertions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/NetworkStatusFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/ThermalStateTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/V2SessionApiTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceExtensions.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/SessionMessage.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/V1PayloadMessageCollator.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/V2PayloadMessageCollator.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSession.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeV1PayloadCollator.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/payload/SessionMessageTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadFactoryBaTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadFactorySessionTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/PayloadFactoryImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/V2PayloadMessageCollatorTest.kt, embrace-android-sdk/src/test/resources/session_message_expected.json, embrace-android-sdk/src/test/resources/v1_session_expected.json, embrace-android-sdk/src/test/resources/v2_session_expected.json
Migrates the span snapshots to the new position in the payload. This is targeting an integration branch & will not be merged to master yet.
=> Migrate span snapshot field

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/SpanAssertions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/ActivityFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/AeiFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/LowPowerFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/NetworkStatusFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/ThermalStateTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/ViewFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/WebviewFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/CrashTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/FlutterInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ReactNativeInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/V2SessionApiTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/startup/AppStartupTraceEmitterTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/startup/StartupServiceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanAttributeTests.kt
Refactors some assertions made on spans in test code. This is a necessary pre-requisite for future changes.
=> Refactor span test assertions

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/ApiRequest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/ApiRequestMapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/ApiService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/EmbraceApiService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/CachedSession.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryCacheManager.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/PendingApiCalls.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/SessionMessage.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/api/ApiRequestMapperTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/api/ApiRequestTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/api/EmbraceApiServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/EmbracePendingApiCallsSenderTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/PendingApiCallsTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeApiService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/payload/SessionMessageTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/PayloadFactoryImplTest.kt
Sends the payload to the new v2 endpoint. This is targeting an integration branch so won't be merged down to master just yet.
=> Send payload to v2 endpoint

gradle.properties
Manually update this after the release GH action failed to do so
=> Update version file manually to 6.9.0-SNAPSHOT

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanBuilder.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/SpanRepository.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/SpanService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/SpanServiceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/UninitializedSdkSpanService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSpanService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanBuilderTest.kt
=> Create Span with EmbraceSpanBuilder in SpanService

embrace-android-sdk/src/integrationTest/java/io/embrace/android/embracesdk/NullParametersTest.java, embrace-android-sdk/src/integrationTest/java/io/embrace/android/embracesdk/PreSdkStartTest.java, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/ActivityFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/AeiFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/AnrFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/PersonaFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/UserFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/OtelSessionGatingTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/FlutterInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/LogRecordExporterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PushNotificationTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ReactNativeInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SpanTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/UnityInternalInterfaceTest.kt
Simplifies the syntax required to construct a test harness object.
=> Alter syntax of test harness construction

.github/workflows/stale.yaml
Use independent stale workflow
=> GHA worflows - Use independent stale workflow

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/CleanSessionBoundaryTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/PeriodicSessionCacheTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/gating/SessionSanitizer.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/Session.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/PayloadMessageCollatorImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceGatingServiceV2PayloadTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/SessionSanitizerFacadeTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/SessionSanitizerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/SessionTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/api/ApiClientImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSession.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeV2PayloadCollator.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fixtures/SessionTestFixtures.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/payload/BackgroundActivityTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadFactoryBaTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadFactorySessionTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/PayloadFactoryImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/PayloadMessageCollatorImplTest.kt, embrace-android-sdk/src/test/resources/bg_activity_expected.json, embrace-android-sdk/src/test/resources/session_expected.json, embrace-android-sdk/src/test/resources/session_message_expected.json
Removes some additional fields from the `Session` object.
=> Remove some additional session fields

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/CrashTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/gating/EmbraceGatingService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/Session.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/SessionMessage.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/PayloadMessageCollatorImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceGatingServiceV2PayloadTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/SessionTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeNativeCrashService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSession.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeV2PayloadCollator.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/payload/BackgroundActivityTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/PayloadMessageCollatorImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorTest.kt, embrace-android-sdk/src/test/resources/bg_activity_expected.json, embrace-android-sdk/src/test/resources/session_expected.json
Remove crash ID from the session object as it is now an attribute of the session span.
=> Remove crash id

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt
Reviewing synchronization of the current span object and tweaked  it to prevent potentially double init. While it really wouldn't happen now, who knows what the future brings.
=> Flesh out synchronization of session span transition

embrace-android-compose/build.gradle.kts, embrace-android-fcm/build.gradle.kts, embrace-android-okhttp3/build.gradle.kts, embrace-android-sdk/build.gradle.kts, embrace-lint/build.gradle.kts, gradle/libs.versions.toml
Uses a [version catalog](https://developer.android.com/build/migrate-to-catalogs) to specify library dependencies.
=> Use version catalog for lib dependencies

README.md
Update project README for users who are not Embrace customers. Given that folks who discover us via our repo will likely want to try the SDK without signing up for Embrace first, I've made the README more geared towards getting them going.
This should help folks coming to the repo for the first time after hearing about us just to fork and play with the SDK.
=> Update README for OSS usage

.github/dependabot.yml
Use the [gradle package ecosystem](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem) to search for dependency updates in our gradle build.
=> Run dependabot on gradle dependencies

.github/workflows/build-rc-workflow.yml, .github/workflows/pre-release-workflow.yml, .github/workflows/rc-release-branch.yml
Improve our release pipeline
Not yet...
=> Update Release Candidate Workflow

.github/workflows/functional-tests.yml, .github/workflows/publish-snapshot.yml
Adding the option to manually run the workflow and to be called from the snapshot workflow.
=> fix changes in functional tests workflow

.github/workflows/build-rc-workflow.yml, .github/workflows/pre-release-workflow.yml, .github/workflows/rc-release-branch.yml
Removes baseline profile from rc workflow until it works fine.
=> Removes baseline profile from rc workflow until it works fine.

.github/workflows/rc-update-test-apps.yml
Update the remaining test apps
=> Added new test apps to update workflow

gradle.properties
Change version after cutting release branch for 6.9
=> Bump version in master to 6.10.0-SNAPSHOT

embrace-android-sdk/embrace-proguard.cfg
Avoiding apps with `minifyEnabled = true` failing on compilation.
=> Added missing proguard rules

buildSrc/src/main/kotlin/embrace-defaults.gradle.kts, buildSrc/src/main/kotlin/io/embrace/gradle/Versions.kt, embrace-android-compose/build.gradle.kts, embrace-android-fcm/build.gradle.kts, embrace-android-okhttp3/build.gradle.kts, embrace-android-sdk/build.gradle.kts
Standardises how the unit test/integration tests are setup by adding the same dependencies & sourceSet structure for each module.
=> Refactor test build script setup

.github/workflows/build-rc-workflow.yml
Run RC workflow on MacOS to match CI workflows
=> Run RC workflow on MacOS rather than Ubuntu

build.gradle.kts, buildSrc/src/main/kotlin/embrace-defaults.gradle.kts
Use key in memory to do signing
=> Use in-memory key for signing

build.gradle.kts, buildSrc/src/main/kotlin/embrace-defaults.gradle.kts
Cherrypick of #1046 into 6.9 release branch
=> Use in-memory key for signing (#1046)

embrace-android-sdk/src/integrationTest/java/io/embrace/android/embracesdk/PreSdkStartTest.java, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/SessionPropertiesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/OtelSessionGatingTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/CrashTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/FlutterInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ReactNativeInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/UnityInternalInterfaceTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/AppInfoTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/ReactNativeInternalInterfaceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadFactoryBaTest.kt
Fixes a few compiler warnings that have shown up in the build recently.
=> Fix compiler warnings

embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/BreadcrumbApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/EmbraceAndroidApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/InternalInterfaceApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/InternalWebViewApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/LogsApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/MomentsApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/NetworkRequestApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/OTelApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/SdkApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/SdkStateApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/SessionApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/UserApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/spans/TracingApi.kt
Alters the internal API interface visibility in preparation for moving them to the API module.
=> Alter internal api visibility

embrace-android-core/api/embrace-android-core.api, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AppExitInfoBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/BackgroundActivityBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/BreadcrumbBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/DataCaptureEventBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/LogMessageBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/NetworkSpanForwardingBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/SdkEndpointBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/SdkModeBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/SessionBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/StartupBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/WebViewVitalsBehavior.kt, embrace-android-sdk/api/embrace-android-sdk.api
Moves some additional interfaces to the `embrace-android-core` module
=> Move behavior interfaces to core module

.github/workflows/ci-gradle.yml
Attempts to optimize the tasks that are run on CI by being more specific rather than running for every build type, and avoiding a clean.
=> Optimize tasks run on CI

.github/workflows/build-rc-workflow.yml, .github/workflows/ci-gradle.yml, .github/workflows/functional-tests.yml, .github/workflows/generate_baseline_profile.yml, .github/workflows/publish-snapshot.yml
Alters the keys used for calculating a cache on CI as it didn't account for all the things in the build script that could potentially alter the build.
=> Alter CI cache keys

build.gradle.kts, embrace-android-payload/build.gradle.kts, embrace-android-sdk/build.gradle.kts, gradle.properties
Replace usage of kapt with ksp now that our Kotlin version has been updated.
=> Replace kapt with ksp

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crumbs/BreadcrumbDataSource.kt
Moves the breadcrumb data source to the features module.
=> Move breadcrumb data source

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/utils/EncodingExtensions.kt, embrace-android-features/build.gradle.kts, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/datasource/SpanDataSourceImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/FeatureModule.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/FeatureModuleImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crumbs/PushNotificationDataSource.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crumbs/RnActionDataSource.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crumbs/TapDataSource.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crumbs/ViewDataSource.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crumbs/WebViewUrlDataSource.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/session/SessionPropertiesDataSource.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/webview/WebViewDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/DataSourceModuleImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/capture/FeatureModuleImplTest.kt
Begins moving the data source classes to the `embrace-android-features` module.
Relied on existing integration tests.
=> Modularise data source classes

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/SessionSpanTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpan.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/PayloadFactoryImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/PayloadMessageCollatorImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeCurrentSessionSpan.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSessionPayloadSource.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/PayloadFactoryImplTest.kt, gradle.properties
Manually apply changes and select tests from PR #1166 and #1167  to `release/6.9` branch in order to release a new patch version. Minimized changes and only moved over the critical tests that verify the fixes work.
=> Changes for the 6.9.2 patch

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupDataCollector.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupServiceImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupTracker.kt
Migrates the app startup classes to the `embrace-android-features` module.
=> Modularise app startup classes

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/SessionSpanTest.kt
Fix test name per review comment
=> Rename test per review comment

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/SessionPayloadTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeCoreModule.kt, embrace-android-sdk/src/test/resources/v2_session_expected.json
Validate session envelop expected attributes.
=> Add integration test for session envelope attributes

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/user/EmbraceUserService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/user/UserService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/UserApiDelegate.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/SessionModuleImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/session/orchestrator/OrchestratorBoundaryDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/UserApiDelegateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/OrchestratorBoundaryDelegateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeUserService.kt
Decouples the NDK service from needing to know directly about the user service by adding a listener.
=> Decouple ndk service

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRuleExtensions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/assertions/OTelLogAssertions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/BreadcrumbFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/EmbraceLoggingFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/JvmCrashFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/FlutterInternalInterfaceTest.kt
Add integration tests to verify key features while the app is in the background
=> Add more integration tests to verify background telemetry capture

.github/workflows/publish-api-docs.yml
=> Clean before running Dokka

.github/workflows/publish-api-docs.yml
=> Fix Dokka command

gradle.properties
Update version in trunk after release
=> Manually update SNAPSHOT version in master

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/schema/ErrorCodeAttribute.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/metadata/RnBundleIdTrackerImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/SessionBehaviorImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/behavior/BreadcrumbBehaviorImplTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkService.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/crumbs/WebViewUrlDataSourceTest.kt, embrace-android-okhttp3/src/test/kotlin/io/embrace/android/embracesdk/okhttp3/EmbraceOkHttp3InterceptorsTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/ActivityFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/ThermalStateTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/StatefulSessionTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PushNotificationApiTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionSpanAttrPopulatorImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/event/EmbraceEventServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeDeliveryService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/BehaviorFakes.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeBreadcrumbBehavior.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeConfigService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeLogRecordData.kt
Fix some easy to fix build warnings so the compiler doesn't yell at me.
=> Fix straightforward build warnings

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/AnrIntervalExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/AnrStacktraceSampler.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/EmbraceAnrService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/NoOpAnrService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/ThreadInfoCollector.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/ThreadStateExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/detection/LivenessCheckScheduler.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/detection/TargetThreadHandler.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/detection/UnbalancedCallDetector.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/sigquit/AnrThreadIdDelegate.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/sigquit/EmbraceSigquitNdkDelegate.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/sigquit/SigquitDataSource.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/sigquit/SigquitDataSourceImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/aei/AeiDataSourceImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crash/EmbraceUncaughtExceptionHandler.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupServiceImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/telemetry/InternalErrorDataSourceImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/user/UserInfoExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/AnrModuleImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashDataSource.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/anr/sigquit/SigquitDataSourceImplTest.kt, embrace-android-sdk/src/main/cpp/anr/anr.c, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSigquitDataSource.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakeAnrModule.kt
Reduces the visibility of classes in the ANR feature now that most of the modularisation has been done
=> Reduce visibility of classes in ANR feature

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/session/EmbraceSessionProperties.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/session/SessionPropertiesService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/session/SessionPropertiesServiceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/OrchestratorBoundaryDelegate.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/SessionPropertiesTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSessionPropertiesService.kt
Clarify actions taken when we do session transitions and update comments to reflect this. Added additional tests to verify non-standard transition scenarios and how session properties are applied.
=> Add integration tests for session props snapshots with bg off

gradle.properties
Update version number in trunk after 6.11 branch cut
=> Update version in properties file after cutting 6.11 branch

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/DeliveryCacheManager.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/EmbraceDeliveryCacheManager.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/EmbracePendingApiCallsSender.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/storage/EmbraceDeliveryCacheManagerTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeDeliveryCacheManager.kt
Ensures that logs are persisted synchronously if a crash happens.
=> Ensure logs are persisted sync in case of crash

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/SystemServiceModuleImpl.kt
Optimizes SDK initialization by delaying an unnecessary binder transaction.
=> Optimise system service initialization

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/metadata/EmbraceMetadataService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/ConfigService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/EmbraceConfigService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/registry/ServiceRegistry.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/capture/metadata/EmbraceMetadataServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/EmbraceConfigServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/registry/ServiceRegistryTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeConfigService.kt
Avoids some unnecessary service registration & moves some metadata service functionality off the main thread.
=> Avoid unnecessary service registration

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/ApiResponse.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/ApiService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/EmbraceDeliveryService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/InitModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/serialization/DecoratedSerializer.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/api/ApiResponseTest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/Endpoint.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/remote/Unwinder.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/AnrInterval.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/ApplicationState.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/PushNotificationBreadcrumb.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/ThreadState.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/WebVitalType.kt, embrace-android-sdk/embrace-proguard.cfg, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeApiService.kt
Cherrypick commits in PRs #1326 and #1327 into the 6.12 release branch in preparation for 6.12.1
=> 6.12.1 cherrypicks

gradle.properties
Update trunk version for developement
=> Update trunk version to 6.13.0-SNAPSHOT

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/EmbraceConfigService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/PayloadSourceModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/SessionOrchestrationModuleImpl.kt
Adds some additional tracing for startup benchmarking, and also tweaks a couple of places that were using references instead of lambdas & slowing things down.
=> Add extra tracing

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ActivityLifecycleTracker.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/ActivityLifecycleTrackerTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRuleExtensions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/ActivityFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt
Just some renaming and makes the code make more sense for what I'm putting on top of it
=> Rename properties and test code related to activity lifecycle tracking and testing

gradle.properties
Update version to 6.14.0-SNAPSHOT
=> Update version to 6.14.0-SNAPSHOT

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/EssentialServiceModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/PayloadSourceModuleImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/AnrService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/EmbraceAnrService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/NoOpAnrService.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/anr/EmbraceAnrServiceTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/anr/EmbraceAnrServiceTimingTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeAnrService.kt
Some minor tweaks to startup performance & tracing. In particular I've simplified the ANR service initialization as the configService is now immutable & won't change.
=> Minor tweaks to perf

.github/workflows/generate_baseline_profile.yml
=> Add token to generate baseline profile

.github/workflows/generate_baseline_profile.yml
I don't know what else to try, this is exactly what embrace-io/metrics/blob/master/.github/workflows/ci-pr-creator.ymll does.
=> Adding an operation between push and pr create in case there's a race condition

CONTRIBUTING.md, README.md
Update branch name in links to source code
=> Update trunk branch name in public docs

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/EmbraceInternalInterface.kt, embrace-android-okhttp3/src/main/java/io/embrace/android/embracesdk/okhttp3/EmbraceOkHttp3ApplicationInterceptor.kt, embrace-android-okhttp3/src/main/java/io/embrace/android/embracesdk/okhttp3/EmbraceOkHttp3NetworkInterceptor.kt, embrace-android-okhttp3/src/test/kotlin/io/embrace/android/embracesdk/okhttp3/EmbraceOkHttp3InterceptorsTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/EmbraceInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/UninitializedSdkInternalInterfaceImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/EmbraceInternalInterfaceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/UninitializedSdkInternalInterfaceImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbraceInternalInterface.kt
=> Delete dead code

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/assertions/DeliveryLayerAssertions.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeIntakeService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadCachingService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadIntake.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadResurrectionService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeRequestExecutionService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSchedulingService.kt
Writes some initial assertions that can be used to verify behavior in the delivery layer.
=> Write assertions for delivery layer

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2Impl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2ImplSupplier.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/DeliveryModule2ImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/assertions/DeliveryLayerAssertions.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeIntakeService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadCachingService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadIntake.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadResurrectionService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeRequestExecutionService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSchedulingService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakeDeliveryModule2.kt
Creates the boilerplate code required to instantiate objects in the delivery module.
=> Implement dependency injection for delivery module

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadata.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadataTest.kt
Alters the filename to store the version as a suffix rather than a prefix.
=> Alter filename schema

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SessionApiTest.kt
Fix SessionApiTest by actually removing the expectation of the disk space attribute smdh
=> Fix SessionApiTest for real

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/LogModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/SessionOrchestrationModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/LogOrchestratorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/PayloadStore.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V1PayloadStore.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/LogOrchestratorTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorTest.kt
Add log storage to the `PayloadStore` shim layer.
=> Log payload storage

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/LogOrchestratorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/PayloadStore.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V1PayloadStore.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStore.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStoreTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeIntakeService.kt
This provides an initial implementation of a v2 payload store that routes data to the `IntakeService`.
=> Initial implementation of v2 payload store

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/storage/StorageService2.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeRequestExecutionService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeStorageService2.kt
Make StorageService2 extend PayloadStorageService and make existing fake and tests work
=> Make StorageService2 implement PayloadStorageService and make existing tests and fakes work together

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImplTest.kt
Don't try to queue payload delivery if the network is not reachable. And if we come back on line, try to delivery what is outstanding.
=> Make ScheduleService understand network status

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/FlutterInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AeiFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/EmbraceLoggingFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/JvmCrashFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/SensitiveKeysRedactionFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ViewFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/BackgroundActivityDisabledTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceAssertionInterface.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/assertions/SessionPayloadEnvelopeAssertions.kt
Makes some miscellaneous improvements to the integration test assertions.
=> Rename some misc assertions in the integration tests

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crash/CrashTeardownHandler.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/LogOrchestratorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/NoopPayloadStore.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/PayloadStore.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V1PayloadStore.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStore.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/comparator/PriorityTaskComparators.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStoreTest.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparator.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/crash/CrashDataSourceImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UserFeaturesTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadStore.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeRequestExecutionService.kt
Miscellaneous tweaks made in #1466 to get the v2 delivery layer working fully. I've separated this out from the change that enabled the layer by default.
Updated test coverage.
=> V2 delivery layer tweaks

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupServiceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlConnectionDelegate.java, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeCpuInfoDelegate.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEventService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeUserService.kt
Ran cleanup accidentally and took some of the changes
=> Minor cleanup

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/PeriodicSessionCacheTest.kt
Addresses a flaky integration test by rolling back some changes that were made to not use a controllable executor.
=> Fix flaky test

embrace-android-sdk/build.gradle.kts
Adding the delivery modules to code coverage
=> Add embrace-android-delivery to code coverage tracking

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/EmbraceHooks.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ExternalTracerTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/LogRecordExporterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PushNotificationApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SpanExporterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ActivityFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AeiFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/JvmCrashFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/PersonaFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/SensitiveKeysRedactionFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/SessionPropertiesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UserFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/SessionSpanTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceActionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceAssertionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePreSdkStartInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeRequestExecutionService.kt
Simplifies how the integration tests work with initializing the SDK.
=> Tweak integration tests

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionServiceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt
=> Use a lower priority background worker to do resurrection

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImplTest.kt
Makes some updates to the threading model for the v2 delivery layer as the old approach wasn't working. Notably:
1. The `IntakeService` and `PayloadStorageService` now share a worker for any mutative file operations
2. `PayloadStorageService` enqueues delete operations on the same thread that `IntakeService` uses to write files
=> Review delivery threading model

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServiceImplTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImplTest.kt
Handles back pressure in periodic session caching by cancelling any pending tasks when submitting a new task request. While this won't stop any `Runnable` that is already executing it will cancel any that are in the queue, therefore helping avoid a scenario where N runnables are queued up to persist useless data.
The v1 delivery layer seems susceptible to this but I will leave that behavior as is since we plan on removing it soon.
Added unit test.
=> Address backpressure in periodic caching

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleSupplier.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImplTest.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparator.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/PeriodicSessionCacheTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/FakeCacheStorageService.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeRequestExecutionService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakeWorkerThreadModule.kt
If duplicate payloads are detected in the integration tests throw an error.
=> Throw error if duplicate payloads detected

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/V1DeliveryFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/SessionSpamTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePayloadAssertionInterface.kt
Adds integration tests that confirm the basic functions of the v1 delivery layer are still working.
=> Add integration tests for v1 delivery layer

embrace-android-sdk/build.gradle.kts, embrace-test-fakes/build.gradle.kts, gradle/libs.versions.toml
Applies some miscellaneous changes that were auto-suggested by Android Studio to our build scripts.
=> Misc gradle script fixes

gradle/libs.versions.toml
Bump several test dependencies to the latest version.
=> Bump test dependencies

buildSrc/src/main/kotlin/io/embrace/gradle/Versions.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/memory/MemoryWarningDataSource.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/instrumented/EnabledFeatureConfig.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/MemoryWarningFeatureTest.kt
Increases the compileSdkVersion to 35.
**WHAT**:Increase compile SDK version to 35<br>
=> [DNM] Bump compile sdk version to 35

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt
Try-catch individual payload queuing. In practice, this shouldn't do much right now given most of the complexity is not in the queuing but the execution, but this is structurally correct anyway
=> Continue to queue payloads even if one fails

embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/SystraceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ExternalTracerTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/FlutterInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/LogRecordExporterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/NetworkRequestApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PushNotificationApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ReactNativeInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SpanExporterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/UnityInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ActivityFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/PruningFeatureTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlConnectionDelegateDelegationTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlStreamHandlerTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNetworkConnectivityService.kt
Ran a bunch of integration tests. Looks at the really slow ones. Did some changes to make them faster or eliminate them because they're not really necessary. Found a flakey test during this and fixed that as well.
=> Tweaked some slows tests to run faster and remove flakiness

UPGRADING.md, embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/EmbraceAndroidApi.kt, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/SessionApi.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/user/UserInfoExt.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/prefs/EmbracePreferencesService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/prefs/PreferencesService.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/capture/user/EmbraceUserServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/prefs/EmbracePreferencesServiceTest.kt, embrace-android-infra/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/BackgroundWorker.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/SessionApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/SessionApiDelegateTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePreferenceService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpanData.kt
Removes some deprecated APIs as part of 7.0.
=> [DNM] Remove deprecated apis

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.kt
Always delegate directly to `EmbraceImpl` from `Embrace`.
=> Remove unnecessary overload calls

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/SpanRepository.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanFactoryImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt
Update the cached background activity when a span is updated
Updated unit tests
=> Update cached background activity when a span is updated

.github/workflows/clear-ci-cache.yml
Adds a workflow to clear the Github Actions cache. We periodically need to do this when the build cache seems to get corrupted.
=> Add workflow to clear cache

UPGRADING.md
Adds a note about properties that will be removed from the gradle plugin.
=> Update upgrading docs

embrace-android-sdk/src/main/cpp/safejni/jni_util.c, embrace-android-sdk/src/main/cpp/serializer/file_writer.c, embrace-android-sdk/src/main/cpp/utils/utilities.c, embrace-android-sdk/src/main/cpp/utils/utilities.h
Ran unused code inspection and didn't find much, besides 3rd party libraries code
=> Remove unused code from NDK

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/source/CombinedRemoteConfigSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt
Adds some extra systrace calls for config bootstrapping.
=> perf: systrace improvements

examples/ExampleApp/app/src/main/AndroidManifest.xml, examples/ExampleApp/app/src/main/res/xml/network_security_config.xml, examples/ExampleApp/settings.gradle.kts
I need that network config in order to use Proxyman 😬
=> Add network_security_config.xml for Proxyman testing in demo app

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AeiFeatureTest.kt
Enhances the integration tests for ApplicationExitInfo capture.
=> Add integration tests for AEI

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/RemoteConfigTest.kt
Attempts to reduce flakes in remote config test by getting the worker thread that persists config & blocking until it has completed all its tasks. The tests did not wait for the background thread so could fail intermittently.
=> Attempt to reduce flakes in remote config test

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashProcessorImpl.kt
Simplifies the code used to read native crash files for our NDK layer.
=> Simplify NDK storage layer code

gradle/wrapper/gradle-wrapper.properties
Bumps gradle to the latest patch version.
=> Bump gradle

examples/ExampleApp/gradle/wrapper/gradle-wrapper.properties, gradle/wrapper/gradle-wrapper.properties
=> Bump gradle to 8.12

build.gradle.kts, buildSrc/build.gradle.kts
Bumps the Kotlin dependency to 2.1.0.
=> Bump kotlin to 2.1.0

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadEventListener.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExtTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeUiLoadEventListener.kt
Remove an event that is no longer need now that we don't need to start a trace based on the time the last activity was done.
=> Remove the reset event

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ui/DrawEventEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ui/FirstDrawDetector.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExtTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeDrawEventEmitter.kt
=> Add unregistering of draw callback

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupTracker.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleImpl.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExtTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/StartupTrackerTest.kt
=> Make FirstDrawDetector a singleton

.github/workflows/swazzler-tests.yml, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/EmbraceLogService.kt
Initial refactor of the `LogService` to make it easier when we add the attachment upload feature.
=> Refactor log service implementation

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/EmbraceUrl.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/Endpoint.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/server/FakeApiServer.kt
Adds the attachment endpoint to the enum.
=> Add endpoint for attachment

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/attachments/Attachment.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/PayloadStore.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V1PayloadStore.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStore.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/attachments/AttachmentTest.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/PayloadType.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadata.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServiceImplTest.kt, embrace-android-sdk/build.gradle.kts, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/StatefulSessionTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePayloadAssertionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/server/FakeApiServer.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/server/MultipartFormReader.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadStore.kt
Refactors some of the existing attachment code & adds some test code that will eventually be used to assert that attachments are uploaded to Embrace's servers.
=> Refactors and test code for attachment work

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupDataCollector.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/InstrumentationApiDelegate.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeAppStartupDataCollector.kt
Add public APIs to add custom child spans and attributes to the app startup trace
=> Support attributes and events on custom startup trace child span

.github/workflows/swazzler-tests.yml
Cherry picks #1842 to the release branch
=> Cherry pick #1842

build.gradle.kts
Cherry pick of https://github.com/embrace-io/embrace-android-sdk/pull/1844
=> Cherry pick: increase sonatype timeouts

.github/workflows/build-rc-workflow.yml
Run :embrace-gradle-plugin:publishToSonatype instead of just publishToSonatype
=> Specify module to run publishToSonatype

CHANGELOG.md
Add changelog to repo as well.
=> Add changelog to repo

examples/ExampleApp/gradle.properties
Point example app to the new version
=> Update example app to latest version

.github/workflows/build-rc-workflow.yml
=> Avoid running tests on RC workflow

embrace-android-sdk/embrace-proguard.cfg
Adds a ProGuard rule that retains config that undergoes bytecode instrumentation.
=> Add proguard rule

CHANGELOG.md
Add JVM symbol upload issue to release note to 7.0.0
=> Update release note jfor 7.0.0

CHANGELOG.md
Add changelog entry for release 7.1
=> Add docs for android 7.1

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/embrace/internal/BuildPlugin.kt, buildSrc/src/main/kotlin/io/embrace/internal/EmbraceBuildLogicExtension.kt, embrace-android-api/build.gradle.kts, embrace-android-compose/build.gradle.kts, embrace-android-core/build.gradle.kts, embrace-android-delivery/build.gradle.kts, embrace-android-fcm/build.gradle.kts, embrace-android-features/build.gradle.kts, embrace-android-infra/build.gradle.kts, embrace-android-okhttp3/build.gradle.kts, embrace-android-payload/build.gradle.kts, embrace-android-sdk/build.gradle.kts, embrace-internal-api/build.gradle.kts, embrace-lint/build.gradle.kts, embrace-test-common/build.gradle.kts, embrace-test-fakes/build.gradle.kts
Makes some further tweaks to the internal plugin to make it possible to apply this to JVM modules.
=> Tweak internal plugin setup

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/settings.gradle.kts, buildSrc/src/main/kotlin/io/embrace/internal/BuildPlugin.kt, buildSrc/src/main/kotlin/io/embrace/internal/ProductionModuleConfig.kt, embrace-android-sdk/build.gradle.kts, embrace-lint/build.gradle.kts, gradle/libs.versions.toml, settings.gradle.kts
Updates the build to use the version catalog by configuring buildSrc to use it.
=> Use version catalog

embrace-android-sdk/build.gradle.kts, gradle.properties, gradle/wrapper/gradle-wrapper.properties
Misc minor updates to the build script in preparation for open sourcing the gradle plugin.
=> Update script in preparation for gradle plugin

.github/workflows/upload-artifacts-to-sonatype.yml
Updates the artifact upload workflow to use the gradle task used for publishing the gradle plugin artifact.
=> Update artifact upload workflow

.github/workflows/upload-artifacts-to-sonatype.yml, embrace-gradle-plugin-integration-tests/build.gradle.kts
Alters the publish task to a more specific one in our CI workflow so we don't upload test plugins.
=> Alter publish task to be more specific

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt
Change the name of the app startup root spans to match iOS
=> Rename startup root span

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/EmbraceGradlePluginDelegate.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/buildreporter/BuildTelemetryCollector.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/buildreporter/BuildTelemetryService.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/registration/TaskRegistrar.kt
Don't create an instance every time we need it. Use the same class instead.
Relied on existing tests
=> Consolidate instances of AgpWrapper

examples/ExampleApp/gradle/libs.versions.toml, gradle/libs.versions.toml
Bumps several dependencies to the latest version.
=> Bump dependencies

CHANGELOG.md
=> Changelog for SDK version 7.2.0

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/annotation/IgnoreForStartup.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/registry/ServiceRegistry.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ActivityLifecycleTracker.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ActivityTracker.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/StartupListener.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/registry/ServiceRegistryTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/ActivityLifecycleTrackerTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupDataCollector.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupTracker.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/StartupTrackerTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeActivityTracker.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeAppStartupDataCollector.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNotStartupActivity.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSplashScreenActivity.kt
Add back all the app startup changes that were reverted before 7.2 was cut
=> Re-add reverted app startup changes

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt
Tweaks to impl preventing duplicate startup traces from being created. We can now use the root span to keep track of the state rather than booleans that we have lock and check
=> Simplify logic to record app startup traces

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/EmbraceAttributeKeys.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt
Give spans better names that don't confuse it with specific lifecycle stages
=> Give startup trace spans and attributes better names

embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt
Refactor test code for app startup emitter so they can be called more modularly
=> Refactor app startup tests

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt
Allow component to end startup trace if startup hasn't completed. It's hooked on to the onBackground method of ProcessStateListener, but hasn't been hooked up yett
=> Support abandonning app startup at the emitter level

embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/AssertionInterface.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/ConfigInstrumentationTest.kt, embrace-test-common/src/main/kotlin/io/embrace/android/gradle/network/MultipartFormReader.kt
Strengthens a test case assertion so that we check the build ID in the APK matches the build ID in the HTTP request.
=> Strengthen build id assertion

embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/smali/SmaliParser.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/ConfigInstrumentationTest.kt, embrace-gradle-plugin-integration-tests/src/test/resources/config-overrides.json, embrace-gradle-plugin-integration-tests/src/test/resources/instrumented-config-overrides.json
Adds an integration tests that overrides the default value for each config value & asserts that the smali from the decompiled APK has an appropriate return value.
=> Add tests for overriding config instrumentation

embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/smali/ExpectedSmaliConfig.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/smali/SmaliFile.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/smali/SmaliMethod.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/smali/SmaliParser.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/ConfigInstrumentationTest.kt, embrace-gradle-plugin-integration-tests/src/test/resources/config-overrides.json, embrace-gradle-plugin-integration-tests/src/test/resources/instrumented-config-default.json, embrace-gradle-plugin-integration-tests/src/test/resources/instrumented-config-overrides.json
Adds a test case that checks the default values of instrumented config bytecode.
=> Increase scope of bytecode instrumentation tests

UPGRADING.md, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/api/EmbraceBytecodeInstrumentation.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/api/EmbraceExtension.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/buildreporter/BuildTelemetryService.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/InstrumentationBehaviorImpl.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/PluginBehavior.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/PluginBehaviorImpl.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/il2cpp/Il2CppUploadTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/r8/JvmMappingUploadTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/reactnative/EmbraceRnSourcemapGeneratorTaskRegistration.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/config/InstrumentationBehaviorImplTest.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/config/PluginBehaviorImplTest.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTaskRegistrationTest.kt
Migrates the remaining project properties to the new extension, where it's safe to do so.
=> Migrate project properties to extension

embrace-gradle-plugin-integration-tests/fixtures/android-instrumentation/build.gradle, embrace-gradle-plugin-integration-tests/fixtures/android-instrumentation/proguard-rules.pro, embrace-gradle-plugin-integration-tests/fixtures/android-instrumentation/src/main/AndroidManifest.xml, embrace-gradle-plugin-integration-tests/fixtures/android-instrumentation/src/main/kotlin/com/example/app/FcmServiceFixture.kt, embrace-gradle-plugin-integration-tests/fixtures/android-instrumentation/src/main/kotlin/com/example/app/OkHttpFixture.kt, embrace-gradle-plugin-integration-tests/fixtures/android-instrumentation/src/main/kotlin/com/example/app/OnClickListenerFixture.kt, embrace-gradle-plugin-integration-tests/fixtures/android-instrumentation/src/main/kotlin/com/example/app/OnLongClickListenerFixture.kt, embrace-gradle-plugin-integration-tests/fixtures/android-instrumentation/src/main/kotlin/com/example/app/WebViewClientFixture.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/smali/SmaliConfigReader.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/smali/SmaliMethod.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/smali/SmaliParser.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/BytecodeInstrumentationTest.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/ConfigInstrumentationTest.kt, embrace-gradle-plugin-integration-tests/src/test/resources/bytecode-instrumentation-disabled.json, embrace-gradle-plugin-integration-tests/src/test/resources/bytecode-instrumentation-enabled.json, embrace-gradle-plugin-integration-tests/src/test/resources/instrumented-config-default.json, embrace-gradle-plugin-integration-tests/src/test/resources/instrumented-config-overrides.json, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/visitor/FirebaseMessagingServiceClassAdapter.kt
Adds gradle integration test cases that assert how bytecode instrumentation functions.
=> Add bytecode instrumentation integration test

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/connectivity/EmbraceNetworkConnectivityService.kt
Concurrent access of the listeners, da-doi!
=> Make network status update thread safe

gradle.properties
This reverts commit 3ddc1f1329ea15e4351a6a243a522059fe08034f.
=> Revert "CI/CD: set next version: 7.4.0-SNAPSHOT (#2039)"

embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/CompressSharedObjectFilesTaskTest.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/CompressSharedObjectFilesTask.kt
Add more extensive testing around the architectures folder that's passed to CompressSharedObjectFilesTask.
Fixed some bugs for cases where we didn't fail correctly.
=> Added tests to CompressSharedObjectFilesTaskTest and fixed some bugs

embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/remote/RemoteConfig.kt
Change to new feature flag that defaults to "true", which will now match the client default
=> Change the remote feature flag for UI load instrumentation

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/ClassVisitBehavior.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/EmbraceClassVisitorFactory.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/visitor/BytecodeInstrumentationFeature.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/visitor/BytecodeInstrumentationFeatureList.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/visitor/InstrumentationTargetClassVisitor.kt
Extracts the information necessary to bytecode instrument the OkHttp/FCM features out to a separate data class.
=> Extract bytecode instrumentation features

examples/ExampleApp/app/src/main/AndroidManifest.xml, examples/ExampleApp/app/src/main/kotlin/io/embrace/android/exampleapp/ui/CodeExample.kt, examples/ExampleApp/app/src/main/kotlin/io/embrace/android/exampleapp/ui/ExampleContent.kt, examples/ExampleApp/app/src/main/kotlin/io/embrace/android/exampleapp/ui/examples/bytecode/BytecodeInstrumentationExample.kt, examples/ExampleApp/app/src/main/kotlin/io/embrace/android/exampleapp/ui/examples/bytecode/BytecodeOkHttpActivity.kt, examples/ExampleApp/app/src/main/kotlin/io/embrace/android/exampleapp/ui/examples/bytecode/BytecodeViewClickActivity.kt, examples/ExampleApp/app/src/main/kotlin/io/embrace/android/exampleapp/ui/examples/bytecode/BytecodeWebViewActivity.kt, examples/ExampleApp/app/src/main/res/layout/activity_bytecode_okhttp.xml, examples/ExampleApp/app/src/main/res/layout/activity_bytecode_view_click.xml, examples/ExampleApp/app/src/main/res/layout/activity_bytecode_webview.xml
Adds code to the example app that can be used to manually verify most of the bytecode instrumentation features.
=> Add examples for bytecode instrumentation

CHANGELOG.md
=> Update changelog for 7.4.0

CHANGELOG.md
=> Update changelog for 7.5.0

embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/anr/EmbraceAnrServiceTimingTest.kt
Increase the clock time update to avoid race conditions
=> Fix flaky EmbraceAnrServiceTimingTest.kt

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/KotlinApiConversions.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/logs/EmbraceLogRecordExporter.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/EmbraceExt.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OtelExt.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanExporter.kt
Cleans up some unused functions & refactored another.
=> Cleanup of unused functions

.github/dependabot.yml, .github/workflows/android-emulator-tests.yml, .github/workflows/build-example-app.yml, .github/workflows/ci-gradle-2.yml, .github/workflows/ci-gradle.yml, .github/workflows/example-app-emulator-tests.yml, .github/workflows/generate-baseline-profile.yml, .github/workflows/publish-api-docs.yml, .github/workflows/release-workflow.yml, .github/workflows/upload-artifacts-to-sonatype.yml
... and some other minor CI housekeeping.
=> chore: pin all 3rd-party GitHub actions

embrace-android-otel/lint-baseline.xml, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/config/OtelSdkConfig.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OtelSdkWrapper.kt
Refactors `OtelSdkConfig` to make the exporters accessible. This PR has no functional change but is a pre-requisite for later ones.
=> Refactor OtelSdkConfig

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OtelExt.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanData.kt
Moves a conversion function to the same place where other conversion functions are.
=> Alter mapping function location

embrace-android-core/build.gradle.kts, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/EssentialServiceModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModule.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleSupplier.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OtelSdkWrapper.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OpenTelemetrySdkTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanServiceTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanServiceImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/OTelApiDelegate.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeOpenTelemetryModule.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeOtelKotlinClock.kt
Moves OTel Java implementation details out of the core module.
=> Move otel out of core module

embrace-microbenchmark/build.gradle.kts, embrace-microbenchmark/src/androidTest/java/io/embrace/android/embracesdk/benchmark/LoggingApiBenchmarks.kt, embrace-microbenchmark/src/androidTest/java/io/embrace/android/embracesdk/benchmark/TracingApiBenchmarks.kt
Add logging microbenchmark tests
=> Add microbenchmarks for Logging API

README.md
Minor changes to make the readme file more readable
=> Minor changes to the readme file

embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImplTest.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbInvalidSpan.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbSpan.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/payload/SpanMapper.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/id/OtelIds.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanCreator.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanStartArgs.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbClockTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/payload/SpanMapperTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanCreatorTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/arch/EmbraceAttributeExtensions.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/assertions/LogAssertions.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeOpenTelemetryModule.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/SpansTestFixtures.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/internal/OtelTestExt.kt
Miscellaneous tweaks to use the new Kotlin API in the embrace-android-otel module.
=> Miscellaneous OTel tweaks

.github/workflows/publish-api-docs.yml
Now we can pass 7.6.1, and it'll checkout release/7.6.0 on the checkout step.
=> Update publish-api-docs.yml to accept hotfixes

CHANGELOG.md
Update changelog in the repo for the last few releases.
=> Update changelog in repo

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImpl.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImplTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanImplTest.kt
Filter the filtering conditions and add a tests for the getters that aren't explicitly used and tested via `snapshot()` already.
=> Fix filtering in attributes() getter function

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactory.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImpl.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanService.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanServiceImpl.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImplTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanImplTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanServiceTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanServiceImplTest.kt, embrace-microbenchmark/src/androidTest/java/io/embrace/android/embracesdk/benchmark/TracingApiBenchmarks.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbraceSpanFactory.kt
Simplifies `EmbraceSpanFactory` by removing some unnecessary overloads.
=> Simplify EmbraceSpanFactory

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImpl.kt
Reduce the access to span args from within `EmbraceSpanImpl` by assigning them to internal properties instead.
=> Reduce the access to span args

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanStartArgs.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanStartArgsTest.kt
Uses the Kotlin API for `SpanKind`.
=> Use spankind symbol

CHANGELOG.md
=> Add changelog for 7.8.0
