embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/connectivity/EmbraceNetworkConnectivityService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/connectivity/NetworkConnectivityService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/connectivity/NoOpNetworkConnectivityService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceNetworkConnectivityServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeNetworkConnectivityService.kt
The `NetworkConnectivityService` registers for network changes during its initialization. As this service has a bootstrapped reference to the `DataSourceModule` which is initialized after it, in rare circumstances where startup is slow + a network connectivity change happens this could result in access to a lateinit var that isn't initialized, which was captured as an internal error.
I've fixed this by ensuring that connectivity change registration only happens after the `DataSourceModule` is initialized.
=> Prevent lateinit property exception

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/assertions/SpanAssertions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/NetworkRequestApiTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/anr/AnrOtelMapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/anr/ndk/NativeAnrOtelMapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceExtensions.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/opentelemetry/EmbSpan.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/FakeBackgroundActivity.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/anr/AnrOtelMapperTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/EmbraceAttributeExtensions.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/startup/StartupServiceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakePersistableEmbraceSpan.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fixtures/SpansTestFixtures.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/network/logging/EmbraceNetworkLoggingServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/opentelemetry/EmbSpanTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/payload/BackgroundActivityMessageTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/payload/SessionMessageTest.kt, embrace-android-sdk/src/test/resources/bg_activity_message_expected.json, embrace-android-sdk/src/test/resources/session_message_expected.json, embrace-android-sdk/src/test/resources/span_expected.json
Don't explicit set the status of a span when we call `end()` in `EmbraceSpan`. This means that UNSET will be a valid status value for a completed span, per OTLP.
Fixed up tests to not look for OK status to denote a completed span, but rather that an end time has been set.
=> Don't set span status to OK on every successful trace stopping

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/SpanMapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceExtensions.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/opentelemetry/EmbSpan.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/spans/PersistableEmbraceSpan.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakePersistableEmbraceSpan.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSpan.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSpanBuilder.kt
Set the status and status description on the SDK span when `setStatus()` is called from `EmbSpan`. We still won't set it to OK when `EmbraceSpan.end()` is called without an ErrorCode, as this value is not useful when using the Embrace API. When an `ErrorCode` is used, we set the status to ERROR automatically.
Fix up existing tests.
=> Refactor how span status is peristed and sent to sdk span from wrappers

embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ExternalTracerTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/OTelApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/OTelApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/OTelApiDelegateTest.kt
Remove `getTracer()` methods from the API and instead serve up an `OpenTelemetry` implementation from which Tracers can be obtained. This reduces the number of methods in the API but also allow for 3rd party instrumentation libraries to consume our OTel API implementations in the way they want.
Existing tests cover this
=> Remove getTracer methods from the API

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/lifecycle/EmbraceProcessStateService.kt
Removes a misleading error message. `isInBackground` relies on the current state of the `LifecycleOwner`. The internal implementation of this sets the new state & then invokes the callback, meaning it's possible for an 'unbalanced' call to happen on the first launch, although practically speaking this makes no difference.
=> Remove unnecessary warning

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/envelope/resource/EnvelopeResourceSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/EnvelopeResource.kt
Removes the `disk_space` field in `Resource` as it's already covered by `disk_total_capacity`.
=> Remove disk field

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/SpanServiceImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt
Adds a limit of 1000 for the number of internal spans that we capture. I'm open to discussion on the exact limit we enforce, but noticed during my validation of this migration that the number of internal spans was unbounded.
Technically we should always bound the number of spans in the `DataSource` implementation, but in practice I'd like to add this as a backstop to prevent the payload from getting overloaded.
=> Add limit for internal span capture

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/envelope/session/SessionEnvelopeSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/comms/api/EmbraceApiService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/Envelope.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/envelope/session/SessionEnvelopeSourceImplTest.kt, embrace-android-sdk/src/test/resources/v2_session_expected.json
Resolves an issue with the integration branch where sessions weren't persisted to disk as the session ID couldn't be found in the payload. The fix is to look first in the `spans` field, and then in the `span_snapshots` field for the session span.
I've also improved the error messaging around failed HTTP requests as it was initially very hard to tell that a 400 status code was received by the server. Finally, I've tweaked the `type` value to `spans` as this seems to be what the mock api expects, although the field is unused by the actual implementation at this time.
=> Avoid dropping sessions

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceAutomaticVerification.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/metadata/EmbraceMetadataService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/event/EmbraceEventService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/prefs/EmbracePreferencesService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/registry/ServiceRegistry.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/lifecycle/ActivityLifecycleListener.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/lifecycle/ActivityLifecycleTracker.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/lifecycle/ActivityTracker.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/lifecycle/StartupListener.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeActivityTracker.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/registry/ServiceRegistryTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/ActivityLifecycleTrackerTest.kt
ActivityLifecycleListener serves two purposes: to provide a hook to for callback invocations when Activities are opened and closed, along with a callback to invoke when app startup is complete. This PR separates the two so that the activity lifecycle one can be added to without indirectly modifying services that really only care about app startup, which is all but two of the services that implement this interface.
For now, we will keep the object that holds all the listeners the same, but eventually, this could be merged with the `StartupTracker` which provides a super set of functionality.
Use existing tests to verify functionality, add unit tests to verify this second set of callbacks can be registered properlyl.
=> Separate startup listener from ActivityLifecycleListener interface

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/startup/StartupServiceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/EmbraceInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/UninitializedSdkInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/ViewTrackingApiDelegate.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlStreamHandlerFactory.java, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeLogRecordBuilder.kt
Resolve miscellaneous compiler warnings , mostly about deprecated method usage. Made changes to proper methods, or added suppression annotation regarding the use of our own deprecated enum `LogType`. 
Existing tests cover these changes
=> Fix build warnings

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/orchestrator/SessionSpanAttrPopulator.kt
Avoid serializing `"null"` when `deviceDiskFree` is not available.
=> Set device free disk bytes to null when not available

embrace-android-sdk/src/main/cpp/anr/anr.c
We were using the wrong JDI signature for our SIGQUIT capture which led to silent failure. This only affects the migration branch.
=> Use correct method signature for sigquit

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/embrace/gradle/InternalEmbracePlugin.kt, embrace-android-sdk/build.gradle
Updates Kover to the latest version & configures it so that code coverage is included for all current modules.
Looked at the code coverage report locally & will check CI too.
=> Update code coverage to include results from all modules

.github/workflows/functional-tests.yml
Remove setting and requiring of a Github token for Function Test runs. We don't need it since we aren't checkout out files from another repo, and requiring it makes the dependabot PRs fail as secrets are managed differently
This is a test
=> Remove token requirement for running function test workflow

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/startup/AppStartupTraceEmitter.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanFactory.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceTracer.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/SpanService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/UninitializedSdkSpanService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/network/logging/EmbraceNetworkLoggingService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanFactoryImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/SpanServiceImplTest.kt
Make interfaces default to creating spans that are non-private. This is already the case for the create and start span APIs, but the other methods still defaulted to pairing private with internal, which can be confusing.
In practice, the only change is that network request spans are now non-private, which they should've been anyway. All other changes are removing explicit parameters that match the default, which doesn't change existing behaviour
Modified existing tests to verify the default. Did not add additional tests for network spans because that's just using the default now.
=> Explicitly set the default for span creation to non-private

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/envelope/session/SessionEnvelopeSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/envelope/session/SessionEnvelopeSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/envelope/session/SessionPayloadSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/envelope/session/SessionPayloadSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpan.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/FinalEnvelopeParams.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/PayloadFactoryImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/message/PayloadMessageCollatorImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/orchestrator/SessionSnapshotType.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/envelope/session/SessionEnvelopeSourceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/capture/envelope/session/SessionPayloadSourceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeCurrentSessionSpan.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSessionPayloadSource.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanAttributeTests.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/SpanServiceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/FinalEnvelopeParamsTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/message/PayloadMessageCollatorImplTest.kt
Pass down whether or not ending a session in the CurrentSessionSpan should start a new session, and make the check appropriately based on end type as well as whether background sessions are enabled.
Added new tests for the condition
=> Only start a new session span if it's appropriate

build.gradle.kts, buildSrc/src/main/kotlin/embrace-defaults.gradle.kts, buildSrc/src/main/kotlin/io/embrace/gradle/Versions.kt, embrace-android-sdk/build.gradle.kts, gradle/libs.versions.toml
Adding a couple more versions to the library catalogue to reduce the number of duplicate definitions. This was motivated by the need to do some clean up before adding the OTel BOM.
It be nice to get rid of all of them but that doesn't seem possible, at least in some of the places we are using them? I don't know enough about this feature to address this.
=> Clean up version definition

.github/workflows/rc-update-test-apps.yml
This workflow will set the sdk version to each test app.
=> new workflow to update snapshot in test apps

embrace-android-sdk/build.gradle.kts, gradle/libs.versions.toml
Make the versions consistent by pulling in the OTel BOM instead of referring to each version separately.
=> Consume OTel version from BOM

buildSrc/src/main/kotlin/embrace-defaults.gradle.kts, embrace-test-common/README.md, embrace-test-common/build.gradle.kts, embrace-test-common/src/main/kotlin/io/embrace/android/embracesdk/ResourceReader.kt, settings.gradle.kts
Creates a new common module that is added as a `testImplementation` dependency for all modules in the project. This will make it easier to share test code between modules. Initially I've just moved `ResourceReader` over but will do a pass of other classes in a separate changeset.
@bidetofevil I think there's also a bit of a ideological question here - do we want the `embrace-test-common` module to have zero dependencies on any other module? Or should it have a dependency on the `embrace-android-sdk` module so that it can host most of the fakes? Perhaps this is something that will become more apparent later on in the modularisation?
=> Setup common module for test code

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/anr/sigquit/SigquitDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/DataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/DataSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/EventDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/SpanDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/aei/AeiDataSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/BreadcrumbDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/PushNotificationDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/TapDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crumbs/WebViewUrlDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/internal/errors/InternalErrorDataSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/memory/MemoryWarningDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/powersave/LowPowerDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/session/SessionPropertiesDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/webview/WebViewDataSource.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/DataSourceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/SpanDataSourceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeAeiDataSource.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeCrashDataSource.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeDataSource.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeNetworkCaptureDataSource.kt
Renames `alterSessionSpan` to `captureData` as IMO this better reflects what the function is doing.
=> Rename function on data source

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/config/behavior/DataCaptureEventBehavior.kt
Fixes a lint warning in AGP 8.5 that showed up in #1032. Basically the supplied parameter value is not used & we can use the default value instead.
=> Fix lint warning in agp 8.5

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/DataCaptureOrchestrator.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/EmbraceFeatureRegistry.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/DataSourceState.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/DataSourceModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceMemoryServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceWebViewServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/DataCaptureOrchestratorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/DataSourceStateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeDataSourceModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeSessionModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/DataSourceModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorTest.kt
Currently most features in the SDK are built using a `DataSourceState`. These were passed into the `DataCaptureOrchestrator` as a list which then informs them when new data needs capturing in response to changes in the session boundary/config.
This PR alters this so a `DataSourceState` is added directly to the `DataCaptureOrchestrator`. I've also tweaked `DataSource` so that consumers of the internal API don't have the ability to set the `currentSessionType` state. Finally, this also adds support for adding `DataSourceState` values _after_ the session orchestration has started by populating the initial session state. Currently this doesn't happen but is likely to do in future.
In a future changeset I'll investigate adding a way to initialize data sources on a background thread as that …
=> Create registry that tracks what data source states are used in the SDK

build.gradle.kts
Set the environment variables required for the signing task. This was set in `release.gradle` previously but was not ported over as far as I can see when we changed the build files.
=> Set signing credentials

embrace-android-sdk/embrace-proguard.cfg, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EventType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/metadata/AppEnvironment.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/EnvelopeResource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/Span.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/LifeEventType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/payload/TapBreadcrumb.kt
Customers using R8 to obfuscate and shrink their app weren't able to shrink Embrace, because we had proguard rules instructing to keep all classes. This PR changes that. 
In `android-test-app`, turning this on reduced Embrace size by 70%, comparing against master (from 800kb to 250kb, it's not like we were too heavy in the first place 😅)
- Remove unnecessary rules:
- java9.**
- okhttp3.** and okio.**
- Attributes: Exceptions, InnerClasses, Signature.  
- Removed keep rule for the whole embrace package
- Anyone using r8 to either obfuscate or shrink their apk can now remove unused Embrace code.
- Added rules to keep classes used by hosted SDKs, native code, okhttp, swazzled and serialized classes.
- Tested in these apps: 
- https://github.com/embrace-io/small-android-test-app
- …
=> Proguard rules improvements

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/DataSourceState.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/DataSourceStateTest.kt
Prevents the eager initialization of data sources until the `configGate` is `true` and a session is under way.
=> Prevent eager initialization of data sources

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/DataCaptureOrchestrator.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/DataSourceState.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/injection/DataSourceModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/DataCaptureOrchestratorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeDataSourceModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeWorkers.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorTest.kt
Supports the async initialization of features in Embrace. While this changeset does not alter any feature to be initialized async it creates the infrastructure to do so.
=> Support async init of features

embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/InternalInterfaceApi.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/EmbraceConfigServiceTest.kt
Creates an interface that is used for accessing the unity/flutter/react native internal interfaces. This change will ultimately make it easier to create a shim interface around `Embrace/EmbraceImpl`
=> Create interface for internal apis

embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/InternalWebViewApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/NetworkRequestApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/SdkStateApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/InternalWebViewApiDelegate.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/NetworkRequestApiDelegate.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/InternalWebViewApiDelegateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/NetworkRequestApiDelegateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegateTest.kt
Preparatory refactor that will make it easier to create an interface out of `EmbraceImpl`, which will make modularisation possible.
=> Preparatory refactor for making EmbraceImpl an interface

embrace-android-core/README.md, embrace-android-core/build.gradle.kts, embrace-android-core/lint-baseline.xml, embrace-android-features/README.md, embrace-android-features/build.gradle.kts, embrace-android-features/lint-baseline.xml, embrace-android-sdk/build.gradle.kts, settings.gradle.kts
Adds new modules named `embrace-android-core` and `embrace-android-features`. These modules will eventually contain Embrace's implementation details that are required to capture OTel data & send it to a backend, and Embrace's built-in instrumentation features respectively.
`embrace-android-sdk` adds a `implementation` dependency on both, therefore this should effectively have zero breaking change compared to the approach in #1055.
I have not migrated any code over to these modules yet.
=> Setup embrace-android-core & embrace-android-features modules

README.md
Small typo in the README file that tripped me up when I was setting this up, brings it inline with the code snippet from https://embrace.io/docs/android/integration/session-reporting/#add-the-start-call
=> fix small typo in README setup step

embrace-android-sdk/build.gradle.kts
`sdk_version` is null in latest version.
Manual testing.
Fix null sdk_version
**WHAT**:SDK Version was reported as null
**WHY**:It's affecting the dashboard filtering behavior
=> Fix missing sdk_version

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceAutomaticVerification.kt
This isn't used much and has been reported as a security concern
=> Remove unsafe send error email for EmbraceAutomaticVerification

.github/workflows/build-rc-workflow.yml, .github/workflows/pre-patch-workflow.yml, .github/workflows/pre-release-workflow.yml, .github/workflows/release-workflow.yml
Use token user and password for publishing per [new Maven Central requirements](https://central.sonatype.org/news/20240617_migration_of_accounts/#the-impact-on-ossrh-and-the-central-publisher-portal)
I generated the token user and password per instructions [here](https://central.sonatype.org/publish/generate-token/) and added them to the repo as a secret that I now reference in the workflows, which is this change.
=> Use token user and password for Sonatype publishing

.github/workflows/build-rc-workflow.yml
Restore the file containing the key used for Swazzler signing
=> Restore key file for swazzler signing

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/SchemaType.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/network/logging/EmbraceNetworkLoggingServiceTest.kt
Strip the URL for logged network requests so it doesn't contain URL parameters that take up space and may trigger the attribute to be dropped
=> Strip URL of network request of parameters

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/DataSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/NoInputValidation.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/EmbType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/EmbraceAttribute.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/EmbraceAttributeKey.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/FixedAttribute.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/TelemetryType.kt
Moves some internal arch classes into separate source files so there's only one class per file. This should make subsequent refactoring easier to follow.
=> Move classes into separate source files

embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/EmbraceFeatureRegistry.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/SessionType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/DataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/DataSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/DataSourceState.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/datasource/NoInputValidation.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/destination/LogWriter.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/destination/SessionSpanWriter.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/destination/SpanAttributeData.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/limits/LimitStrategy.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/limits/NoopLimitStrategy.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/limits/UpToLimitStrategy.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/EmbType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/EmbraceAttributeKey.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/FixedAttribute.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/SchemaType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/TelemetryAttributes.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/arch/schema/TelemetryType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/crash/CrashDataSourceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/internal/errors/InternalErrorHandler.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/capture/internal/errors/InternalErrorType.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/logs/EmbraceLogService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/payload/Attribute.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/logging/EmbLogger.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/logging/EmbLoggerImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/ndk/NativeCrashDataSource.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/arch/schema/TelemetryAttributesTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeEmbLogger.kt
Makes classes public & marks them as an `@InternalApi` where the feature module needs to access them. In a future changeset I'll also move these to a package under the `internal` namespace.
=> Make internal api symbols visible

embrace-android-core/build.gradle.kts
Removes the OTel dependency in the core module. After discussion our aim is to keep this module free of dependencies such as OTel/Moshi & confine these to other modules.
=> Remove otel dep in core module

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/FlutterInternalInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/ReactNativeInternalInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/UnityInternalInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/InternalInterfaceApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/InternalWebViewApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/LogsApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/SdkApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/spans/EmbraceSpanEvent.kt
Suppresses unwanted symbols that are internal-only from our KDoc. `@hide` should not be used - [`@supress` should be used instead](https://kotlinlang.org/docs/kotlin-doc.html#suppress). Anything inside an `internal.**` package is automatically hidden by our Dokka setup.
This hides the vast majority of unwanted symbols. We may want to convert some Java classes as part of the major bump to have a mechanism for hiding them (and also get rid of Java code).
=> suppress unwanted docs

buildSrc/src/main/kotlin/embrace-defaults.gradle.kts, embrace-android-sdk/src/main/AndroidManifest.xml, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/EmbraceCoreInitializer.kt
Initializes the SDK using the [App Startup library](https://developer.android.com/topic/libraries/app-startup) rather than manual invocation. This happens earlier in the process lifecycle & requires less manual intervention from a user during the integration process.
Manually tested via our test app.
=> Support app startup initialization

gradle.properties
Enables the [gradle build cache](https://docs.gradle.org/current/userguide/build_cache.html), which promises faster builds. We can see what effect this has on performance when developing locally.
Right now enabling configuration cache won't do anything for us because we use kapt, but once we migrate Kotlin there should be some local perf benefits from enabling that.
Relying on CI.
=> Enable build cache

.github/workflows/build-rc-workflow.yml, .github/workflows/ci-gradle.yml, .github/workflows/functional-tests.yml, .github/workflows/generate_baseline_profile.yml, .github/workflows/publish-snapshot.yml, .github/workflows/release-workflow.yml
Use a non-deprecated action for validating our gradle wrapper: https://github.com/gradle/wrapper-validation-action/releases
=> Use latest action for gradle wrapper validation

.github/workflows/build-rc-workflow.yml, .github/workflows/generate_baseline_profile.yml, .github/workflows/publish-snapshot.yml, .github/workflows/rc-release-branch.yml, .github/workflows/rc-update-test-apps.yml, .github/workflows/release-workflow.yml, .github/workflows/swazzler-tests-subset.yml
I'm going through all repos that use CD_GITHUB_TOKEN and replacing it with a more granular one. You probably should view this PR with 'ignore whitespace changes' :)
=> GH-7786 - Cleanup of CD_GITHUB_TOKEN in all workflows.

embrace-android-sdk/src/main/cpp/utils/cpuinfo.c, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/capture/cpu/EmbraceCpuInfoDelegate.kt
EmbraceCpuInfoDelegate is in a new package now, so I updated the JNI method to address it correctly.
=> Fix cpuinfo.c JNI call to address the correct package

embrace-android-core/build.gradle.kts, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/AndroidResourcesService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/BuildInfo.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/EmbraceAndroidResourcesService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/CoreModule.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/CoreModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DependencyInjection.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/registry/ServiceRegistry.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/MemoryCleanerListener.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/MemoryCleanerService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ActivityLifecycleListener.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ActivityTracker.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ProcessStateListener.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ProcessStateService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/StartupListener.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/metadata/AppEnvironment.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/AndroidServicesModuleImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeDataSourceModule.kt
Continues modularisation by moving some dependency injection to the core module.
=> Modularise core module

buildSrc/src/main/kotlin/io/embrace/gradle/Versions.kt, embrace-android-sdk/src/main/cpp/CMakeLists.txt
Adding this allows our library to work on devices with a 16kb memory page size. 
If we don't do this, even if the customer has ndk_enabled set to false, the app will crash with a SIGSEGV when we try to load the native library.
This was done following the steps here: https://developer.android.com/guide/practices/page-sizes
I verified the correct alignment of the test apk after the changes using the alignment script here: https://developer.android.com/guide/practices/page-sizes#test
=> Add linker flag to make library compatible with 16 kb page sizes.

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ActivityLifecycleListener.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/capture/crumbs/EmbraceBreadcrumbService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/session/lifecycle/ActivityLifecycleTracker.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/ActivityLifecycleTrackerTest.kt
Remove the bespoke names and use names that match the lifecycle method that the methods actually map to. This will enable  future changes to be more understandable.
=> Rename methods in ActivityLifecycleListenerInterface to match lifecycle methods

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ActivityLifecycleListener.kt
Make the listener implement `ActivityLifecycleCallbacks` with default no-op implementations so we can observe more lifecycle events.
=> Make ActivityLifecycleListener extend ActivityLifecycleCallacks with no-op defaults

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/FeatureModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/DataSourceModuleImpl.kt
Moves the declaration of 2 data sources so that their instantiation is dealt with in the feature module.
In future changesets we'll leverage the app startup library to automatically add these `DataSourceState` references when initializing the SDK, so that the main SDK module/core module don't need to know anything about the features.
=> Move declaration of data sources to feature module

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/NetworkRequestApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/NetworkRequestApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/NetworkRequestApiDelegateTest.kt
Allows `null` as a valid value when generating a traceparent. This is because the feature may not be enabled in which case we want to avoid generating a traceparent.
=> Allow null for traceparent generator

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt
Add test to clarify what is and isn't supported when it comes to the internal API with respect to creating a child span for a given parent span ID.
=> Verify via test what spans can and can't be parent

buildSrc/src/main/kotlin/embrace-prod-defaults.gradle.kts, buildSrc/src/main/kotlin/embrace-test-defaults.gradle.kts, embrace-android-api/build.gradle.kts, embrace-android-compose/build.gradle.kts, embrace-android-core/build.gradle.kts, embrace-android-fcm/build.gradle.kts, embrace-android-features/build.gradle.kts, embrace-android-okhttp3/build.gradle.kts, embrace-android-payload/build.gradle.kts, embrace-android-sdk/build.gradle.kts, embrace-test-common/build.gradle.kts, embrace-test-common/lint-baseline.xml, embrace-test-common/src/main/kotlin/io/embrace/android/embracesdk/ResourceReader.kt, embrace-test-fakes/README.md, embrace-test-fakes/build.gradle.kts, embrace-test-fakes/lint-baseline.xml, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeClock.kt, settings.gradle.kts
Creates a new module that contains fake implementations used in our test code. Access to fakes is becoming a bit of an obstacle in migrating code over as unit/integration tests typically use fake implementations of a real interface. Currently these are all in `embrace-android-sdk` under the `unitTest` sourceSet, so they become inaccessible if we wish to move unit tests anywhere else.
The solution I've chosen is to create a new module that implements the fakes & added it as a test dependency. I've also taken the opportunity to standardise the quality checks for test modules, as we also have `embrace-test-common` which holds _no_ references to other embrace code & is intended for pure util code.
=> Create test module that holds fake implementations

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImplTest.kt
This was done to match how the OTel library works. Also, it fixes an inconsistency between span snapshots and actual spans.
=> Passing a time of zero to startSpan will now use openTelemetryClock.now()

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/session/EmbraceSessionProperties.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/session/EmbraceSessionPropertiesService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/EssentialServiceModuleImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/SessionModuleImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/properties/EmbraceSessionPropertiesServiceTest.kt
Modularises session properties into `embrace-android-features` and avoids directly referencing `NdkService` from the class.
=> Modularise session prop implementation

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/destination/SessionSpanWriter.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/OpenTelemetrySdk.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/PersistableEmbraceSpan.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/BreadcrumbFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/SessionSpanTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakePersistableEmbraceSpan.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt
Track span events added by the SDK differently so session spans don't artificially cap the amount of telemetry it can hold.
Add unit and integration tests
=> Allow system events to exceed custom event limit

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/assertions/SpanAssertions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImplTest.kt
Span snapshots denote a span that was in process when the session was sent. It makes more sense for the end time to be null, so we don't cause any issues in the backend
=> Span snapshots are now sent with a null end time

buildSrc/src/main/kotlin/embrace-prod-defaults.gradle.kts, embrace-android-features/build.gradle.kts, embrace-android-features/src/test/java/io/embrace/android/embracesdk/capture/crumbs/BreadcrumbDataSourceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/BehaviorFakes.kt, embrace-test-fakes/build.gradle.kts, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/arch/EmbraceAttributeExtensions.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeBreadcrumbBehavior.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeCurrentSessionSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpanData.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/LogEventData.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/SpanEventData.kt
Migrates the breadcrumb test to the features module. This necessitates altering some of the build dependencies & moving fakes around. This is an intermediate step to making some data sources + implementation details internally visible.
=> Migrate tests

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/EmbraceLoggingFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/JvmCrashFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PushNotificationApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SessionApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SpanExporterTest.kt
Give integration tests more appropriate names and packages.
=> Move and rename integration tests

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/SessionModule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/SessionModuleImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionSpanAttrPopulator.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionSpanAttrPopulatorImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeSessionSpanAttrPopulator.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeSessionModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionSpanAttrPopulatorImplTest.kt
Extracts an interface for the `SessionSpanAttrPopulator` class. This is an initial refactor that lays the groundwork for simplifying our session property implementation.
=> Extract interface for SessionSpanAttrPopulator

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/destination/LogWriterImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/id/SessionData.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/id/SessionIdTracker.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/id/SessionIdTrackerImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/EmbraceProcessStateService.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/arch/destination/LogWriterImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/id/SessionIdTrackerImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/event/EventHandlerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/ndk/NativeCrashDataSourceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/network/logging/EmbraceNetworkCaptureServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/network/logging/NetworkCaptureDataSourceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNetworkCapturedCall.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSessionIdTracker.kt
The way we track the current session ID leaves a gap where the current session ID may not match the current state of the app in terms of foreground and background. We address this by tracking the state associated with the session, and use that whenever we need to attach the state of the app for a log, instead of using whatever state the app is in, which may not match with the session
Add unit test to verify this race condition
=> Track session state along with ID in SessionIdTracker

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/destination/SessionSpanWriter.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/session/SessionPropertiesDataSource.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/OpenTelemetrySdk.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/PersistableEmbraceSpan.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/SpanServiceImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/SpanServiceImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/session/SessionPropertiesDataSourceTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionSpanAttrPopulator.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeCurrentSessionSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeDataSource.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePersistableEmbraceSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/SpansTestFixtures.kt
OTel imposes a limit on how many attributes are allowed on a span, which is 128 by default. For the session span, we require more than that because you can theoretically have 100 session properties.
To support this, we bump the total limit set in the OTel layer to 300, and validate that our custom limit of 50 for SDK users is not enforced when the SDK adds attributes via the internal `addSystemAttribute()` method. This will also bump the total number of other attributes the SDK can add to the session span to a safer ceiling.
Added and modified appropriate unit tests to ensure the expected maximums can be written.
=> Increase span attribute limit at the OTel layer

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/cpu/EmbraceCpuInfoDelegate.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/cpu/EmbraceCpuInfoNdkDelegate.kt, embrace-android-sdk/src/androidTest/java/io/embrace/android/embracesdk/ndk/jni/CpuInfoJniInterfaceTest.kt, embrace-android-sdk/src/main/cpp/utils/cpuinfo.c
The JNI interface relies on signatures that might break if a class is moved to another package or renamed. This is only detected in runtime, as compilation goes fine and our tests don't verify this behavior. 
The goal of this PR is to create tests that, at the very least, break when a class targeted by a JNI signature is moved or renamed. If the class is not too complex, the tests will also verify additional functionality.
Classes to test:
=> Add integration tests to check JNI interface - CPU Info

buildSrc/src/main/kotlin/embrace-prod-defaults.gradle.kts, buildSrc/src/main/kotlin/io/embrace/gradle/Versions.kt
Some of the JNI interface tests were affecting other integration tests. We needed a way to run every component in isolation so it wouldn't affect the outcome of other tests. Android Test Orchestrator allows that to happen.
=> Use Android Test Orchestrator to run tests in individual Instrumentation instances

embrace-android-sdk/src/androidTest/java/io/embrace/android/embracesdk/ndk/jni/NativeThreadSamplerJniInterfaceTest.kt
The JNI interface relies on signatures that might break if a class is moved to another package or renamed. This is only detected in runtime, as compilation goes fine and our tests don't verify this behavior.
The goal of this PR is to create tests that, at the very least, break when a class targeted by a JNI signature is moved or renamed. If the class is not too complex, the tests will also verify additional functionality.
Classes to test:
=> Add JNI interface tests for NativeThreadSampler

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/sigquit/EmbraceSigquitNdkDelegate.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/sigquit/SigquitDataSource.kt, embrace-android-sdk/src/androidTest/java/io/embrace/android/embracesdk/ndk/jni/SigquitJniInterfaceTest.kt, embrace-android-sdk/src/main/cpp/anr/emb_anr_manager.c
The JNI interface relies on signatures that might break if a class is moved to another package or renamed. This is only detected in runtime, as compilation goes fine and our tests don't verify this behavior.
The goal of this PR is to create tests that, at the very least, break when a class targeted by a JNI signature is moved or renamed. If the class is not too complex, the tests will also verify additional functionality.
Classes to test:
=> Add JNI interface tests for Sigquit

embrace-android-sdk/src/androidTest/java/io/embrace/android/embracesdk/ndk/jni/NdkJniInterfaceTest.kt
The JNI interface relies on signatures that might break if a class is moved to another package or renamed. This is only detected in runtime, as compilation goes fine and our tests don't verify this behavior.
The goal of this PR is to create tests that, at the very least, break when a class targeted by a JNI signature is moved or renamed. If the class is not too complex, the tests will also verify additional functionality.
Classes to test:
=> Add JNI interface tests for NdkDelegate

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/sigquit/SigquitDataSource.kt, embrace-android-sdk/embrace-proguard.cfg
Some proguard rules were pointing to a wrong location. We should also try to add some swazzler-tests or integration tests to avoid outdated proguard rules.
=> Update proguard rules with new delegates location 

embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/capture/session/SessionPropertiesServiceImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/SessionPropertiesTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/capture/envelope/session/OtelPayloadMapperImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/PayloadModuleImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/PayloadModuleSupplier.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/SessionModuleImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionSpanAttrPopulatorImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/PayloadModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/PayloadFactoryBaTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/SessionHandlerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionOrchestratorTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/session/orchestrator/SessionSpanAttrPopulatorImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeCurrentSessionSpan.kt
We were populating session properties in a session span as a side effect of constructing the end payload of the previous session. This caused a couple of problems: session-only properties not being cleared before the population, and if background activity is disabled, session properties population fails.
Changing where we do the population fixes both of these, as well as allow us to remove the extra population call during SDK startup. 
This change also supersedes #1206 as literal removal is no longer necessary - session only properties will be added or removed from the current session's session span by the `SessionPropertiesService` 
Add integration tests for all cases, as well as the one added in #1206 to verify that session-only props don't bleed into the next session. Unit tests were …
=> Populate session properties in session span during transition

embrace-android-sdk/src/androidTest/java/io/embrace/android/embracesdk/ndk/jni/NativeThreadSamplerJniInterfaceTest.kt, embrace-android-sdk/src/androidTest/java/io/embrace/android/embracesdk/ndk/jni/SigquitJniInterfaceTest.kt, embrace-android-sdk/src/main/cpp/anr/anr.c, embrace-android-sdk/src/main/cpp/anr/anr.h
When we called FindClass on SigquitDataSource and it was not found, we were returning 0 as the result of installGoogleAnrHandler. This means we would've logged that Google ANR was correctly installed, but it wouldn't have worked.
This PR fixes that, and also adds a comment in some interface tests that are also testing classes targeted by JNI FindClass
=> Return an error when configure_reporting fails for Sigquit capture

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/comms/delivery/EmbraceDeliveryService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/SpanAssertions.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePersistableEmbraceSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSession.kt
Use the last heartbeat time of the session span if the end time was missing, like if the session itself wasn't terminated properly, like during a native crash or a user kill while the app is in background.
Previously we were assuming that there's always an end time, and we even tested for that case too, which yield and end of 0 in those cases. The backend is able to work with that in most case, as it just figures it out by looking at other timestamps. So while customers don't see this problem for the most part, like for sessions associated with native crashes, the session span is wrong. I was also seeing some 0-length sessions for background kills where the session span contains a heartbeat time, so it's better than we do this population properly, and test it properly as well.
Modify and …
=> Fall back to heartbeat time when converted span snapshots

.github/workflows/pre-release-workflow.yml, .github/workflows/rc-release-branch.yml, .github/workflows/update-main-versions.yml
Changing the order so the master properties file updates don't make the swazzler branch cutting fail
=> Cut branches for both sdk and swazzler before updating master

.github/workflows/build-rc-workflow.yml
The nexus plugin doesn't like config cache, so disabling both that and the build cache.
=> Don't use build and config gradle caches in RC building workflows

.github/workflows/release-workflow.yml
Don't use Gradle caches for anything in the release workflow, just in case.
=> Don't use gradle caches in release workflow

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/BaseLogService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/EmbraceLogService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/LogCounter.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/gating/EmbraceGatingService.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/LogModuleImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionSpanAttrPopulatorImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeLogService.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeLogModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/logs/EmbraceLogServiceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/logs/LogCounterTest.kt
I started adding unit tests for EmbraceLogService and ended up modifying some things 😅 I wanted to add some tests for the denylist work, so this will serve as a base for that. 
What's in this PR:
- Added tests and simplified LogCounter: we were only using the error log count, regardless of the stored log ids, so I removed those.
- Added tests and simplified EmbraceLogService: fixed trimming logic, removed unhandledExceptionsCount as it was unused.
For the trimming logic, there was an edge case where the limit was smaller than 3, which is the length of the ellipsis we added at the end. The log was lost in this case because we were calling substring with a wrong end index. 
I fixed it, and now, if the max length is smaller than 3, we add the ellipsis.
=> Improved EmbraceLogService

.github/workflows/build-rc-workflow.yml, .github/workflows/ci-gradle.yml, .github/workflows/functional-tests.yml, .github/workflows/generate_baseline_profile.yml, .github/workflows/publish-api-docs.yml, .github/workflows/publish-snapshot.yml, .github/workflows/release-workflow.yml
It doesn't seem setting up the NDK is necessary for the various GH workflows that are doing it, so removing them to see if that's actually.
Also consolidated all the actions that run on Macs to use macos-14
=> Remove the NDK setup step from GH actions

.github/workflows/build-rc-workflow.yml, .github/workflows/pre-release-workflow.yml, .github/workflows/rc-release-branch.yml, .github/workflows/update-main-versions.yml
The names of release sub-workflows are too long and it's hard to see what they are in the UI. Give them shorter names.
=> Rename workflows so they are more readible on the GitHub Actions page

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/BackgroundActivityDisabledTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/SdkStateApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegateTest.kt
Previous SDK versions had getDeviceId() exposed as a synthetic property on the Java `Embrace` object in Kotlin, but it's no longer true, likely because of the Kotlin version change. Restored this ability by exposing it as an actual properly on the interface.
Added additional testing for the case when the SDK is not started. This doesn't change how part behaved, but codecov yelled at me, so I obliged.
=> Expose deviceId as a synthetic immutible property

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRuleExtensions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/SessionPropertiesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/BackgroundActivityTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/SessionApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/SessionApiDelegateTest.kt
Update cached background session explicitly when session properties are updated using the current explicit call.
This is a temporary solution until we can refactor this to more generically trigger a cache update any time new telemetry is captured.
Added unit and integration tests for this scenario.
=> Update cached payload when session props are updated in the background

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/SessionPropertiesTest.kt
Verified that permanent session properties added during the SDK lifetime is persisted in cached payloads
=> Add integration test for cached payloads

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceHttpUrlStreamHandler.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceHttpsUrlStreamHandler.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlConnectionDelegate.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlStreamHandler.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlStreamHandlerFactory.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/InternalNetworkApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/InternalNetworkApiImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/StreamHandlerFactoryInstaller.java, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeInternalNetworkApi.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlConnectionDelegateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlStreamHandlerTest.kt, embrace-test-fakes/lint-baseline.xml, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbraceInternalInterface.kt
Alters our networking code to avoid direct references to the `Embrace` singleton facade.
=> Alter network code to avoid direct embrace reference

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/SdkStateApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegateTest.kt
Store the ability to access `getLastRunEndState()` via a synthetic read-only property in Kotlin as it was that way in previous versions thanks to the old Kotlin version that was used. 
We will revisit this in the next major version.
Add integration tests that access the getter in the Java Embrace object via this
=> Allow getLastRunEndState() to be accessed via a synthetic property in Kotlin

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRuleExtensions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/SessionPropertiesTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeDeliveryService.kt
The test was comparing sessionId to spanId, which is wrong. Looking through the delivery service, it probably works better to have the saved sessions stored in a threadsafe manner, so I made that change too, even though the integration test will do the saving on the main thread.
=> Fix session properties integration tests

buildSrc/src/main/kotlin/embrace-test-defaults.gradle.kts, embrace-android-core/build.gradle.kts, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/AndroidServicesModuleImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/capture/session/EmbraceSessionPropertiesTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crumbs/PushNotificationCaptureService.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.java, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeCoreModule.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/EmbraceInternalInterfaceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/UninitializedSdkInternalInterfaceImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbraceInternalInterface.kt
Fix miscellaneous build warnings. I've also enabled warnings as errors since the Kotlin version we use no longer blocks us from enabling that.
=> Fix miscellaneous build warnings

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/EmbracePendingApiCallsSender.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/delivery/EmbracePendingApiCallsSenderTest.kt
The method used to send failed requests is being invoked before the ApiService is initialized, before `setSendMethod()` is ever called. This leads to a crash in a background thread because a `lateinit var` was being accessed before it was initialized. This leads to `failed_api_calls..json` to re overridden, which leads to lost data.
To fix this, ditch the lateinit var and use an atomic reference to hold the queue. Before trying to access it, check its nullness, and skip if it's null. This will force the api request to retry at the next interval.
A better fix for this will be to delay the retry attempt until after ApiClient is done, but this change is a more appropriate, surgical fix, so we can use this until we make the bigger fix later.
Added unit test to verify the state of the pending …
=> Only try to send failed API requests if the ApiClient is initialized

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/EmbracePendingApiCallsSender.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/PendingApiCallsSender.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/delivery/EmbracePendingApiCallsSenderTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePendingApiCallsSender.kt
Defer the submission of the api calls delivery to the scheduledWorker until `sendMethodRef` (which we will use to execute the delivery) is set
=> Moved scheduled retry after send method setup

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkService.kt
Removes a noisy warning that led to customer confusion.
=> Remove noisy warning

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/SdkModeBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/SdkModeBehaviorImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/behavior/SdkModeBehaviorImplTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkService.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkServiceTest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/remote/RemoteConfig.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/BackgroundActivityDisabledTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SpanExporterTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapperTest.kt
This changeset contains several preparations for initializing NDK error handling on a background thread:
- Removed `isServiceInitDeferred` config as the current implementation breaks signal handler installation, and we should also IMO just default to the correct behavior on this rather than giving a choice
- Remove redundant lock/installed checks within `EmbraceNdkService` as the JNI functions can be called as soon as the SO file is loaded
- Attempted to simplify `ModuleInitBootstrapper` section for NDK/native thread sampling installation, without making any functional changes (yet)
=> Preparatory refactor for initializing NDK error handling on background thread

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/NativeFeatureModuleImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NdkService.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkServiceTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNdkService.kt
Alters the SDK so that NDK error detection is initialized on a background thread, which offloads the loading of a SO file (and other I/O) away from the main thread.
This involved two parts: firstly the NDK service is initialized async from `ModuleInitBootstrapper`, and posts the signal handler installation to the front of the message queue so that it is installed on the main thread asap. Secondly, the Unity ANR thread sampling is called directly from the Unity interface. It appears the Unity SDK already [appears to be doing this](https://github.com/embrace-io/embrace-unity-sdk/blob/2eb7231547bb7a63c69eb1f4f52bef6fa4f4b3e8/io.embrace.sdk/Scripts/Native/Embrace_Android.cs#L511) so it shouldn't affect functionality.
This change reduces startup time from ~16ms to ~14ms on a OnePlus 7 running …
=> Initialize ndk on background thread

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/InitModule.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/InitModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/OpenTelemetryConfiguration.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/LocalConfigTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/behavior/NetworkBehaviorImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/InitModuleImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/network/logging/EmbraceNetworkCaptureServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/opentelemetry/OpenTelemetryConfigurationTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/opentelemetry/OpenTelemetrySdkTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/PayloadFactoryBaTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/PayloadFactorySessionTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SpanExporterTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeOpenTelemetryModule.kt
Generating a process ID for the OTel configuration object was taking a surprisingly long period of time (~1ms). I've offloaded this to the background thread as it didn't need to be on the main thread.
=> Optimize process id generation

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/prefs/EmbracePreferencesService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/prefs/PreferencesService.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/prefs/EmbracePreferencesServiceTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePreferenceService.kt
The SDK startup status is not used so can be removed. This is read on a background thread so won't have a major impact on startup time.
=> Remove unused startup status

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt
Offloads network connectivity listeners so that they are registered async. These are not essential so can afford to wait a few milliseconds until startup is done.
=> Initialize network connectivity listeners async

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/ConfigService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/EmbraceConfigService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/registry/ServiceRegistry.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/EmbraceConfigServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/registry/ServiceRegistryTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeConfigService.kt
Adds objects to the `ServiceRegistry` using lazy initialization so they are only created at the end of startup, to make their impact more obvious. I also removed various objects that don't need to be registered anymore.
=> Register services lazily

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/ApiService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/DeliveryCacheManager.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/DeliveryService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/EmbraceDeliveryCacheManager.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/EmbraceDeliveryService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/NoopDeliveryService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleSupplier.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/EssentialServiceModuleImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImplTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/NativeFeatureModuleImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/NativeFeatureModuleSupplier.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NdkService.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/injection/NativeFeatureModuleImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkServiceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapperTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeApiService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeDeliveryCacheManager.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeDeliveryService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNdkService.kt
The code appears to be making a HTTP request to the old `v1/log/events` endpoint for NDK crashes as well as to the new OTel log endpoint. This PR removes the legacy approach which was the last part of startup that performed I/O on the main thread.
This seems like a modest improvement but I've previously seen this call have very high variance as it performs I/O.
Manually verified that crashes still show in the dashboard.
=> Avoid unnecessary HTTP request for crashes

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/BackgroundActivityDisabledTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SpanExporterTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapperTest.kt
OTel & the span service are initialized on a background thread with the intention of reducing impact on startup times. However, Perfetto tracing shows contention in a couple of places, notably `emb-config-init` and `emb-otel-logger-init`.
IMO it's preferable to always initialize on the main thread as it avoids the unpredictable real-world effects of the main thread waiting on a background thread. This does slightly impact performance in our benchmarks but I believe we've got some budget to use after all the other improvements. It's also worth noting we haven't yet attempted to optimize the OTel initialisation process or updated the baseline profile, which likely makes the trace look worse than it should be.
I profiled before & after on a OnePlus Pro 7 running Android 10.
Initializing on …
=> Initialize OTel on main thread to avoid thread contention

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/connectivity/EmbraceNetworkConnectivityService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/connectivity/NetworkConnectivityService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/metadata/EmbraceMetadataService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/ConfigService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/EmbraceConfigService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/SessionOrchestrationModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/registry/ServiceRegistry.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/OrchestratorBoundaryDelegate.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/capture/metadata/EmbraceMetadataServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/EmbraceConfigServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/registry/ServiceRegistryTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/OrchestratorBoundaryDelegateTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/NetworkStatusFeatureTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeConfigService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNetworkConnectivityService.kt
Avoids a binder transaction when starting a session. The network connectivity service no longer needs to be informed of a session start as it uses spans, whereas in the legacy data model it did.
=> Avoid binder transaction when starting session

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/session/SessionPropertiesServiceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/ConfigService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/EmbraceConfigService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/SensitiveKeysBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/SensitiveKeysBehaviorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/event/EmbraceEventService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModule.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/EmbraceLogService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanFactory.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanFactoryImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/capture/session/SessionPropertiesServiceImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/behavior/SensitiveKeysBehaviorImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/event/EmbraceEventServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/EmbraceLogServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanFactoryImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/SpanServiceImplTest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/local/SdkLocalConfig.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/SensitiveKeysRedactionFeatureTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/BehaviorFakes.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeConfigService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeOpenTelemetryModule.kt
If a `sensitive_keys_denylist` is provided in `embrace-config.json`, the following components will be scanned:
If the key in any of those properties is present in the denylist, the value will be changed to`<redacted>`.
=> Sensitive keys denylist

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/OpenTelemetrySdk.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/opentelemetry/OpenTelemetrySdkTest.kt
Use default `ContextStorage` to short circuit service provider lookup for setting a custom `ContextStorageProvider` to avoid a disk read on SDK startup that violates strict mode.
Add unit test to verify the system property that controls this is set properly.
=> Enforce use of default OTel SDK default ContextStorage

.github/workflows/ci-gradle.yml, .github/workflows/dependency-review.yml, .github/workflows/functional-tests.yml, .github/workflows/swazzler-tests-subset.yml
This concurrency policy cancels in-progress runs when pushing new code to a specific branch.
Example: 
- Let's say we create a `branch_A`, and create a pull request. This will trigger the actions in this PR. 
- If we create a `branch_B`, the actions will also run, simultaneously.
- If we push new code to `branch_A`, the actions that were running on that branch will be canceled, and new ones will be triggered. 
This avoids running actions on stale code.
=> Added concurrency policy to pull_request Github actions

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/schema/EmbType.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/schema/SchemaType.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/schema/SendImmediately.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/schema/SendMode.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/schema/TelemetryType.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/envelope/log/LogEnvelopeSource.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/envelope/log/LogEnvelopeSourceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/envelope/log/LogPayloadSource.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/envelope/log/LogPayloadSourceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/LogOrchestratorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/LogRequest.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/LogSink.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/LogSinkImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/EmbraceAttributeKeys.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/envelope/log/LogEnvelopeSourceImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/envelope/log/LogPayloadSourceImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/EmbraceLogRecordExporterTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/LogOrchestratorTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/LogSinkImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRuleExtensions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/JvmCrashFeatureTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeLogEnvelopeSource.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeLogPayloadSource.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/LogTestFixtures.kt
Changed the `SendImmediately` designation to a `SendMode` enum to additionally allow logs to be saved instead of sent, and use this to save crash logs rather than send them. This ensures they will be delivered on the next app startup in a consistent matter, rather than rely on our existing, flakey mechanism to attempt to send synchronously, and only if it fails, save the payload.
Bundled with this change is the need to serialize the log payload and create the request for other unbatched logs off the calling thread. Right now, they are not being done on a background thread - only sent through it - so this could be problematic depending on where it's being invoked. Instead, we will run them on the same scheduler that we use to run the log batching job.
Added unit tests everywhere to ensure …
=> Save crashes synchronously and process other unbatched log requests in background thread

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/InitModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/serialization/DecoratedSerializer.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/Endpoint.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/remote/Unwinder.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/AnrInterval.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/ApplicationState.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/PushNotificationBreadcrumb.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/ThreadState.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/WebVitalType.kt, embrace-android-sdk/embrace-proguard.cfg
Moshi requires enums to be annotated to prevent R8/ProGuard from stripping their values. Several enums in our codebase were not annotated in this way, which worked fine until we changed the ProGuard rules to be more specific in #1043.
This change adds the `JsonClass` annotation to enums [as recommended](https://github.com/square/moshi?tab=readme-ov-file#r8--proguard).
Manually verified against the `release` build variant of a minified test app that no errors show up in Logcat related to serialization.
=> Add moshi rules to prevent adapters failing in minified build

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/ApiResponse.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/ApiService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/EmbraceDeliveryService.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/api/ApiResponseTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeApiService.kt
Alters the session delivery logic so that for cases where a payload is still deliverable (e.g. if there is no network connection or server response) the SDK attempts delivery again rather than dropping the payload.
Added unit tests for new retry logic & manually verified an error is no longer logged in a test app with no network connection.
=> Retry session delivery where possible

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanLimits.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/SpanServiceImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/SpanServiceImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/SpansTestFixtures.kt
Names of spans we record internally can be longer than than the custom performance traces that we have a name length restriction for. Make the validate not apply to spans logged by the SDK, i.e. internal = true.
=>  Don't enforce span name length limit for spans the SDK logs

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkService.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkServiceTest.kt
_updateAppState was accessed before the native library was loaded. I added some guards to the delegate methods so we always verify that the native library is loaded before we call them.
=> Load the native library in NdkService before accessing the delegate methods

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceExtensions.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanLimits.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/SpanServiceImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/SpanServiceImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/NetworkRequestApiTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpanData.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/SpansTestFixtures.kt
Allow spans that the SDK logs as its out of the box instrumentation to have longer names as well as attribute values. This solves the problem of network requests having long names and attributes because of the URL being logged is greater than what was set as the ceiling for perf traces.
Add unit tests and integration tests
=> Allow internal spans to have longer names

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/sigquit/EmbraceSigquitNdkDelegate.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/sigquit/SigquitDataSourceImpl.kt, embrace-android-sdk/embrace-proguard.cfg, embrace-android-sdk/src/main/cpp/anr/anr.c, embrace-android-sdk/src/main/cpp/anr/anr.h, embrace-android-sdk/src/main/cpp/anr/emb_anr_manager.c
Prevents a JNI error that is triggered by SIGQUIT when Google ANR capture is enabled (i.e. when an ANR happens). This feature is disabled by default & users would either need to set `sdk_config.anr.capture_google` to `true` in `embrace-config.json` _or_ have a remote config set that enables this behavior. The error looks like:
>JNI DETECTED ERROR IN APPLICATION: can't call void io.embrace.android.embracesdk.internal.anr.sigquit.SigquitDataSourceImpl.saveSigquit(long) on instance of io.embrace.android.embracesdk.internal.anr.sigquit.EmbraceSigquitNdkDelegate
This was been introduced in #1214 so will be present in 6.10.0 upwards. The `anr_manager.c` code assumed that the caller would always be the object that would contain the `saveSigquit` function, but that assumption was invalidated in …
=> Prevent JNI error on SIGQUIT when Google ANR capture enabled

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NdkService.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkServiceTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNdkService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSessionIdTracker.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSessionPropertiesService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeUserService.kt
Attach various listeners only after native library loading is success to avoid calling methods on the delegate when the library is not loaded.
Added unit tests to verify the listener attachment, and let the existing unit and functional tests validation functionality.
=> Attaching activity listener conditional to the native library loading

.github/workflows/build-rc-workflow.yml, .github/workflows/ci-gradle.yml, .github/workflows/dependency-review.yml, .github/workflows/functional-tests.yml, .github/workflows/publish-api-docs.yml, .github/workflows/publish-snapshot.yml, .github/workflows/rc-release-branch.yml, .github/workflows/rc-update-test-apps.yml, .github/workflows/release-workflow.yml, .github/workflows/swazzler-tests-subset.yml, .github/workflows/update-main-versions.yml
- Stop using matrix for jdk-version
- Use setup-gradle instead of cache and wrapper_validation
- Use ubuntu-latest instead of macos
- Don't use fetch-depth: 0 when it's not necessary
- Add KVM group permissions for emulator
- Use working-directory instead of cd
- Remove unnecessary refs to default branches
- Replaced references to "master" with "main"
=> Github Actions improvements

.github/workflows/swazzler-tests-subset.yml
Use a specific NDK version so we don't depend on the github runners having it pre installed
=> Download and cache NDK

embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/instrumented/ProjectConfig.kt
This function is not instrumented by the swazzler yet & `BuildInfo` is used in the SDK still. This changeset removes it for now to avoid confusion.
=> Remove unused build id function from project config

.github/workflows/generate_baseline_profile.yml
- Grab the version from gradle.properties in embrace-android-sdk
- Use that version when running the baseline-profile.
=> Set correct version in android-sdk-benchmark repo when running generate_baseline_profile.yml

embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/delivery/EmbraceCacheServiceConcurrentAccessTest.kt
Disable tests that are flaky in the new CI runner images
=> Ignore conccurrent cache service tests for now due to flakiness in new imagew

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/BackgroundWorker.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/worker/BackgroundWorkerTest.kt
Adds a function to `BackgroundWorker` that calls `shutdown` and then `awaitTermination` on the `ExecutorService` implementation. This is intended for use when payloads are being persisted but the process is about to terminate due to a JVM crash. However, it will likely become useful in other scenarios.
=> Add functionality for shutting down worker & waiting for tasks to complete

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/DataCaptureOrchestrator.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/EmbraceDeliveryCacheManager.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/EssentialServiceModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/StorageModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/WorkerThreadModule.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/WorkerThreadModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/PrioritizedWorker.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/ScheduledWorker.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/WorkerThreadModuleImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/storage/EmbraceDeliveryCacheCurrentAccessTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/storage/EmbraceDeliveryCacheManagerTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/worker/BackgroundWorkerTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/worker/PriorityThreadPoolExecutorTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/thermalstate/ThermalStateDataSource.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeDataSourceModule.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeWorkers.kt
Extracts a `PrioritizedWorker` class that is capable of setting a priority, and removes the possibility to set `TaskPriority` on `BackgroundWorker` as the field was ignored for every worker apart from the network request queue.
This is an intermediate stage in the refactor - I plan on combining `BackgroundWorker` and `ScheduledWorker` next as they now effectively fulfil the same function. 
=> Extract prioritised executor

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/WorkerThreadModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/BackgroundWorker.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/arch/DataCaptureOrchestratorTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/capture/session/EmbraceSessionPropertiesTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/EmbraceConfigServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/prefs/EmbracePreferencesServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/worker/BackgroundWorkerTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/StartupServiceImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/thermalstate/ThermalStateDataSourceTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeWorkers.kt
Alters `BackgroundWorker` to use `ScheduledExecutorService` and updates tests also. This should not functionally impact anything as it was always used under the hood anyway. This will allow combining BackgroundWorker/ScheduledWorker in future PRs.
=> Replace worker implementation

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRuleExtensions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/JvmCrashFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/SessionPropertiesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/BackgroundActivityDisabledTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeDeliveryService.kt
Background activities are saved in a background thread, triggered explicitly by certain public API method calls. In order to control the order of execution and taking care of both the case when the background thread save runs before or after the validation code hits on the main test thread, I added `checkNextSavedBackgroundActivity` which takes in a lambda that will trigger an action that in turn triggers a save, as well as one that runs some validation code on the NEXT background activity that is saved. 
Along the way, I tweaked the implementation of `returnIfConditionMet` to separate the data being used to check the condition that is being continuously checked. TBH, I'm not sure if that's really needed - the initial failures were due to the background save not being triggered because …
=> Fix integration test infra for validating saved background activities

embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/worker/BackgroundWorkerTest.kt
The test case assumed that the job would not complete after the latch was released, but internally `BackgroundWorker` calls `shutdown` which allows completion of tasks that are already executing.
My fix is to increase the number of latches required to 2 so the `Runnable` never completes. I've added an assertion to check the latch was counted down instead.
=> Alter assertion of flaky test

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/delivery/EmbraceDeliveryCacheManager.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/WorkerThreadModule.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/WorkerThreadModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/PriorityCallable.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/PriorityRunnable.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/PriorityRunnableFuture.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/PriorityThreadPoolExecutor.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/PriorityWorker.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/comparator/PriorityTaskComparators.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/delivery/EmbraceDeliveryServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/WorkerThreadModuleImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/storage/EmbraceDeliveryCacheCurrentAccessTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/storage/EmbraceDeliveryCacheManagerTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/worker/BackgroundWorkerTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/worker/PriorityThreadPoolExecutorTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/worker/PriorityWorkerTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/worker/comparator/TaskPriorityComparatorTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeWorkers.kt
Adapts the existing `PriorityThreadPoolExecutor` so that instead of only supporting the `TaskPriority` enum, it supports arbitrary data types with a matching comparator. I've updated the implementation so that network requests are prioritised based on whether `ApiRequest` is a session, and so that the `DeliveryCacheManager` prioritises based on the supplied `TaskPriority`.
Updated & added to unit tests.
=> Allow priority based execution using custom comparators

embrace-android-delivery/build.gradle.kts, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/Envelope.kt, embrace-test-fakes/build.gradle.kts
Alters the dependencies in `embrace-android-delivery` so that the core module + test fakes can be accessed. Additionally defines the serialized type that should be used for log payloads.
=> Alter project dependency structure

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadata.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/SupportedEnvelopeType.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeService.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadataTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeIntakeService.kt
Creates an initial interface for the `IntakeService`, an initial implementation for the file metadata, and a fake service implementation.
1. Should we distinguish between different log payloads (log/crash/network) in the file metadata?
2. Do we want to rename the supported log payload types in the file metadata at all?
3. Are there additional types to support (e.g. AEI)?
4. Does the filename metadata structure look correct? Is there anything else we want to encode?
Added unit test coverage
=> Create intake service interface

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparator.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadata.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/SupportedEnvelopeType.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparatorTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadataTest.kt
Implements rules for how stored telemetry should be prioritised. This will be used when sending telemetry, but IMO we should also use this when persisting data to avoid the queue getting saturated. In both scenarios this should be possible by supplying a comparator to the executor in `BackgroundWorker` - I'll make this change in a follow-up PR.
=> Implement prioritisation of stored telemetry

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/IntegrationTestRuleExtensions.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/SessionPropertiesTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeDeliveryService.kt
Getting the last saved session was flakey in the same way getting the last saved background activity was flakey. Fixed this by just not checking that, but instead checking when the session is done, which is not flakey because that save happens on the main test thread.
At the same time, I made the non-flakey saved envelope payload validation function generic and usable for sessions, if we ever need it
=> Simplify session properties tests to not checked cached payload

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/ConfigService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/EmbraceConfigService.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/EmbraceConfigServiceTest.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2Impl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2ImplSupplier.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/DeliveryModule2ImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeConfigService.kt
Makes the `DeliveryModule2` return null if the SDK is configured to only send data to OTel exporters. This avoids unnecessary work.
=> Make delivery services optional

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/caching/PeriodicBackgroundActivityCacher.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/caching/PeriodicBackgroundActivityCacherTest.kt
Reduce min gap between background save to 2s 
Add unit tests
=> Optimize background activity caching

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SessionApiTest.kt, embrace-android-sdk/src/test/resources/v2_session_expected.json
The SessionApiTest was flakey because whether the disk space attribute is written in the session is non-deterministic. So to make the payload predictable, I disabled that feature in this integration test verification, which is superfluous anyway since it working ought to be verified via unit tests anyway.
=> Make SessionApiTest not flakey

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/PriorityRunnableFuture.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/comparator/PriorityTaskComparators.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparator.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparatorTest.kt
Refactors the comparator that will be used to prioritise telemetry to match the pattern used in `taskPriorityComparator` and others.
=> Alter stored telemetry comparator

embrace-android-delivery/build.gradle.kts, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2Impl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2ImplSupplier.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/DeliveryModule2ImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt
Adds the boilerplate of constructor parameters & dependency injection code that `IntakeService` will require. I've also added a dependency on OTel as it'll be necessary to access the `Clock` implementation.
=> Add boilerplate for intake service

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/PriorityCallable.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/PriorityRunnable.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/PriorityThreadPoolExecutor.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/comparator/PriorityTaskComparators.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparator.kt
Makes `storedTelemetryComparator` work on `StoredTelemetryMetadata` & makes some classes visible from the core module that will be required in future PRs.
=> Refactor telemetry comparator

embrace-android-delivery/build.gradle.kts, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakeInitModule.kt
Avoids a runtime crash in our tests due to classloading issues. I've just delayed the classloading for the `openTelemetryModule` because we'll never use it from the delivery tests.
=> Avoid otel dep in delivery module

embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/event/EmbraceEventServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/DataSourceModuleImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/SessionOrchestrationModuleImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/crash/LastRunCrashVerifierTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/features/EmbraceLoggingFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/PeriodicSessionCacheTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/FlutterInternalInterfaceTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakeWorkerThreadModule.kt
Add an additional worker that we can tweak the execution via a blocking executor. This is needed for testing the delivery service components
This PR was hijacked for this as the actual scheduling service code in previous revisions that were under discussion will come in subsequent PRs.
=> Add additional worker to test in FakeWorkerModule 

embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/caching/PeriodicBackgroundActivityCacherTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/assertions/TestAssertions.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/concurrency/BlockingScheduledExecutorService.kt
Add helpers for testing work scheduled on a BlockingScheduledExecutorService that was previously private to a specific test classes. These will be used later to verify that all the tasks queued prior has been executed.
=> Genericize executor test helpers

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2Impl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2ImplSupplier.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/DeliveryModule2ImplTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServiceImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadStorageService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakeDeliveryModule2.kt
Creates an initial implementation of `IntakeService` which stores everything in the existing `CacheService`. This changeset attempts to fulfil the following requirements of `IntakeService`:
- On a crash the SDK will block until pending tasks have finished persisting data
- Crashes/sessions/logs/network capture are prioritised for persistence in order of importance
- Payloads are stored gzip compressed
- The scheduling service is notified after a payload is persisted
- An internal error is logged if persistence fails for whatever reason
I have not implemented cleanup if disk usage exceeds a maximum limit.
I've wrapped `CacheService` with a `PayloadStorageService` interface. My initial thought is that in future PRs we probably want to extract the functionality we want out of `CacheService`, …
=> Initial implementation of intake service

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparator.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2Impl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2ImplSupplier.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/DeliveryModule2ImplTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparatorTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServiceImplTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadStorageService.kt
Creates an initial implementation of `PayloadStorageService`. Ultimately this will fulfil a similar function that `CacheService` did in the old approach, except right now it only persists final payloads (and not cache attempts).
I added functions to store, delete, and load a payload. Payloads are stored using gzip compression & there is a total limit on the number of files stored on disk, after which less important payloads (assessed by type + age) are deleted.
I also altered the atomic file write logic somewhat compared to the `EmbraceCacheService` implementation as there isn't any possibility these files will be overwritten. 
1. If we detect an exception that indicates disk space has run out, should we attempt to delete old/less important payloads in favour of the new one?
2.  Is the …
=> Payload storage service implementation

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule2Impl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImplTest.kt
Makes some of the tweaks to the payload storage implementation that were discussed in #1427. Specifically:
- Create an in-memory list of files
- Fix prioritisation of stored telemetry deletion
Mostly relied on existing unit tests.
=> Tweak payload storage implementation

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/SessionOrchestrationModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/SessionPayloadStore.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/TransitionType.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V1SessionPayloadStore.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorTest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/remote/KillSwitchRemoteConfig.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/behavior/FakeAutoDataCaptureBehavior.kt
Creates a shim that will be used to switch between the v1/v2 storage systems. I've implemented this as an interface that will have 2 implementations that can be gated by the remote config added in #1430.
=> Create shim for session payload storage

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/SessionOrchestrationModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/SessionPayloadStore.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/TransitionType.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V1SessionPayloadStore.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorTest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/remote/KillSwitchRemoteConfig.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/behavior/FakeAutoDataCaptureBehavior.kt
Adds a kill switch in remote config that can be used to disable the v2 storage system if so required.
=> Add kill switch for v2 storage

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/envelope/session/SessionPayloadSourceImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/envelope/session/SessionPayloadSourceImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/BackgroundActivityTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/SequentialSessionTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/session/StatefulSessionTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SessionApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeCurrentSessionSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpanData.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeV2PayloadCollator.kt
Only snapshot session span if we know the session isn't ending, i.e. we are only caching the payload
Added unit and integration tests to verify this. Also fixed related tests that were wrongly validating data on the fake CurrentSessionSpan. This caused a domino of fixes that ultimately results in better validation overall.
=> Only take snapshots of session spans if we are doing a periodic payload cache

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageService.kt
Adds some documentation for the `PayloadStorageService` synchronisation strategy.
@bidetofevil for review it'd be helpful to (1) let me know if you agree this is a reasonable strategy & (2) validate that there aren't any footguns in the actual implementation that I've missed. I'd also specifically be interested in your thoughts on the approach I've taken for `loadPayloadAsStream`.
=> Document synchronisation strategy for PayloadStorageService

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SessionApiTest.kt
Restores assertions in `SessionApiTest` that were altered in #1453.
=> Restore session api assertions

.editorconfig
Codify our preferred code formatting default in an `.editorconfig` file for the SDK project so we don't have to manually apply it on IDE upgrades that don't simply take the previous version's settings.
=> Create editorconfig file for formatting defaults

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ExternalTracerTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/LogRecordExporterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PushNotificationApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SpanExporterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ActivityFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AeiFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/PersonaFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/SensitiveKeysRedactionFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/SessionPropertiesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UserFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/SessionSpanTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceActionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePostSetupInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePreSdkStartInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeRequestExecutionService.kt
Simplify integration test by adding a step to do something before setting up the test harness, and then only starting the SDK after that runs. This makes it not necessary to manually start the SDK, and also exposes a proper place to "do and verify stuff" before the SDK starts without manually needing to do so.
With this, `startImmediately` has been removed as a parameter of the harness, and `startSdk` was introduced as a parameter of `runTest` for those select tests that don't require the SDK to be started automatically.
=> Add post-setup step to integration tests that allows for almost all tests to automatically start the SDK

embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStoreTest.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparator.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadata.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageService.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadataTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadStorageService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/DeliveryFixtures.kt
Make `StoredTelemetryMetadata` be aware of whether it contains a payload that is complete and ready to be delivered. This is so we can load and delete them during payload resurrection. Putting in the filename isn't the most efficient but it gets the job done. 
I avoided added to the interface more than I have to so that store/delete/load methods don't have to know about this.
=> Add the notion of completeness to payload storage

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/caching/NoopPayloadCachingService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/caching/PayloadCachingService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/caching/PayloadCachingServiceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/delivery/caching/PayloadCachingServiceImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadCachingService.kt
Moves further payload caching logic out of `SessionOrchestratorImpl` so that it's isolated in a single class that will make future changes easier.
Updated test coverage.
=> Extract further payload caching

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImplTest.kt
Document the expectation of how the `store` and `load` methods treats the input and output with respect to compression. While the interface sets out no expectation, the implementation will always compress the input, and leave the output uncompressed.
=> Clarify expectations of compression when using  PayloadStorageServiceImpl

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/LogModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/EmbraceLogService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/LogOrchestratorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V1PayloadStore.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/EmbraceLogServiceTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakeLogModule.kt
Improves the threading model for log capture + delivery. This makes the following changes to improve deliverability:
1. `V1PayloadStore` is now responsible for the background worker that stores log payloads, not `LogOrchestrator`. This means when enabled `V2PayloadStore` is consistently called from the same thread for all log payloads
2. Log capture now happens on the main thread which avoids the complexity of 2-3 worker threads interacting with each other. This does not affect log persistence which still happens on a background thread for v1/v2. In principle I can't see any operations that would be very expensive when capturing a log, but this is something we could profile if it needs optimizing
=> Improve threading model for log capture

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSchedulingService.kt
Registers this class as a listener so that it can react to changes in network connectivity.
=> Register scheduling service as network connectivity listener

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleSupplier.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/OpenTelemetryConfiguration.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStore.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionServiceImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStoreTest.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadata.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparatorTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadataTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServiceImplTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/DeliveryFixtures.kt
Encodes the process ID in the filename so that it's simpler to find sessions belonging to a given process.
=> Encode process id in filename

.github/workflows/functional-tests.yml
It's not necessary to use our own fork inside public repos.
**WHAT**:<br>
**WHY**:<br>
=> ci: Don't need to use internal android-emulator-runner fork.

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStore.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStoreTest.kt
Records whether the log was a log, crash, or network capture when persisting to disk.
=> Record correct type when capturing logs

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/StorageModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/WorkerThreadModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/Worker.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/WorkerThreadModuleImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt
Replaces the worker used for the `SchedulingService` with one that can use I/O, as I/O will be triggered the first time the service attempts to read from the `PayloadStore`. Additionally renamed some workers to more appropriate names.
=> Replace scheduling worker

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt
Avoids checkNotNull to prefer returning null in the `ModuleInitBootstrapper`. Functionally this should not make much different as `apiService` will always be null if only OTel export mode is enabled, but it can't hurt to alter this in case that assumption ever breaks.
=> Avoid check not null in module bootstrapper

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/destination/LogWriter.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/destination/LogWriterImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/schema/TelemetryAttributes.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceExtensions.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/utils/Extensions.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/arch/destination/LogWriterImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/arch/schema/TelemetryAttributesTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/utils/ExtensionsKtTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashDataSourceImpl.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/NativeCrashDataSourceImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeLogWriter.kt
The NDK and/or the serialization layer is returning values that are effectively null/empty but with non-null string value like "null", and we weren't filtering out those cases because we assumed it would just return null when those values didn't exist.
Add in the generic ability to detect string values like that, and to skip adding those values as OTel attributes, if you explicitly say that's what you wanted.
There was also some code in the native crash log generation layer that didn't check for empty collections before serializing their values - took care of those cases too.
Units tests all the way down
=> Only write attributes for crashes if they contain valid values

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/PayloadModuleSupplier.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/PayloadSourceModule.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/PayloadSourceModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/EnvelopeExt.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/SpanMapper.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionServiceImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/PayloadSourceModuleImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/payload/SpanMapperTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionServiceImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadResurrectionService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakePayloadSourceModule.kt
The PayloadResurrectionService, for now, depends on the NativeCrashService, which exists in the Features Layer, so I'm moving it there too (in the CrashModule, as it is resurrecting payloads generated sometimes by native crashes) so it can have access to it. 
Change module tests to verify that the service is only initialized if the v2 feature flag is on.
=> Move ResurrectionService to the CrashModule in the Features layer

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionServiceImpl.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ResurrectionFeatureTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt
Enable new resurrection behaviour after the SDK starts, and disable the old one, depending on the feature flag. Add simple integration tests to ensure the SDK starts fine, but will need to add some additional faking in the test harness to actually test the functionality.
=> Hook up Resurrection Service to the SDK behind the v2 kill switch

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadStorageService.kt
Implement the getUndeliveredPayloads method which only returns payloads with a different process identifier than the current one and is incomplete. We won't try to resurrect payloads for the current app instance because it's not dead yet!
=> Implement getUndeliveredPayloads methods in PayloadStorageService

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/WorkerThreadModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStore.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStoreTest.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadata.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/SupportedEnvelopeType.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparatorTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadataTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServiceImplTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImplTest.kt
Change the token encoded in the payload filename to priority, move it to the front of the file, so the natural sort order of the file name will be the priority order
Changed unit tests to verify the new scheme
=> Change the token encoded in a file name for envelope type to priority

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/StorageModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/WorkerThreadModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/WorkerThreadModuleSupplier.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/worker/Worker.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/AndroidServicesModuleImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/WorkerThreadModuleImplTest.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparator.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakeWorkerThreadModule.kt
Uses a separate worker for the v1/v2 delivery systems to avoid the possibility of undesired behavior if the wrong type information is submitted with a `Runnable`. This shouldn't add a thread in practice as only 1 system will be active at a time. As part of this change I also correctly gated a v1 delivery call in SDK bootstrapping behind the v2 storage feature flag.
=> Avoid mixing workers between different delivery systems

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleSupplier.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImplTest.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryComparator.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/PeriodicSessionCacheTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/FakeCacheStorageService.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakeWorkerThreadModule.kt
Alters the periodic session cache test case so that it won't fail when run against the v2 delivery layer. I've not flipped the switch as part of this PR but have instead opted to create lots of the necessary functions etc.
=> Fix periodic session cache test case

embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/PayloadSourceModuleImplTest.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/SessionPropertiesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePayloadAssertionInterface.kt
Fix race condition in scheduling service where a payload is removed from the active send list too early, resulting in a new delivery queue instance that contains it, because the payload was not deleted from disk when the initial query was made, and we needed the active state to filter it out
=> Fix race condition in scheduling service

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServicePeriodicCacheTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadStorageService.kt
Ensures that the periodic session caching deletes any old snapshots after persisting a new snapshot. This aims to prevent sending duplicate payloads unnecessarily.
Added unit test.
=> Deletes old session payloads that have been snapshotted.

.github/fetch-robolectric-dependencies.sh, .github/workflows/ci-gradle.yml
Prevent re-downloading of Robolectric jars from Maven Central.
Run with cold cache
Run with warm cache
=> ci: Pre-fetch and cache robolectric dependencies.

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/AnrStacktraceSampler.kt
Filters out any invalid ANR samples (i.e. any samples that have a timestamp outside of the interval range). Once we eventually migrate this feature over to be captured via pure OTel this problem should go away entirely.
=> Filter invalid ANR samples

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/SessionSpamTest.kt
Adds a load test that confirms 1000 sessions can be captured & delivered by the SDK without problems.
=> Add load test for session capture

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/export/FilteredSpanExporter.kt
If the count of the distinct spans IDs exported is less than the total count of spans exported, fail an integration test.
=> Fail integration test when the same span is exported more than once

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/PayloadSourceModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionServiceImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionServiceImplTest.kt
Pass in the right instance of PayloadStorageService to the resurrection service (cache instead of complete payloads). Also, change the metadata when sending to the intake service to state that it's complete
Found this while writing integration tests, fixed this in unit tests
=> Change the metadata when sending resurrectioned payloads

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/embrace-prod-defaults.gradle.kts, buildSrc/src/main/kotlin/embrace-test-defaults.gradle.kts, buildSrc/src/main/kotlin/io/embrace/gradle/Versions.kt, embrace-test-fakes/build.gradle.kts, gradle/libs.versions.toml
Uses a workaround in Gradle to use the version catalog in a precompiled build script. I've not been able to find a solution that would use the version catalog when setting the plugins yet, but this gets us 90% of the way there.
=> Use version catalog where possible

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt
Register a connectivity listener after delivery module init, as otherwise scheduling service isn't initialized.
=> Register connectivity listener after delivery module init

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/StatefulSessionTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePayloadAssertionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/server/FakeApiServer.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/behavior/FakeSdkEndpointBehavior.kt
Alters `StatefulSessionTest` to use mockwebserver rather than `FakeRequestExecutionService`. This exercises the whole of the SDK against a test harness & also opens the door for returning different responses (e.g. 429) to confirm the SDK can handle it properly.
=> Use mock web server in integration tests

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/session/EmbraceSessionProperties.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/session/SessionPropertiesService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/session/SessionPropertiesServiceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/OrchestratorBoundaryDelegate.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/capture/session/SessionPropertiesServiceImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/OrchestratorBoundaryDelegateTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/SessionPropertiesTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSessionPropertiesService.kt
More consistently set permanent session properties and add more comprehensive testing to deal with implication quirks. This includes separating the properties service clearing and adding permanent properties to the session span into two method is `SessionBoundaryDelegate`. 
We now simply clear the old state when a session ends, and populate the sessions span when it first gets created. Previously, we were doing it together, which would not work if the session span wasn't created right away. Also, the population of the initial span was done as a byproduct of getting the properties - now, we do it more durably, when the session span is created.
The existing tests would've caught this issue if it weren't for a bug in the validation code.
In addition to fixing this, the implementation makes …
=> Fix permanent session properties populate when background activity is disabled

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/PruningFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/SessionSpamTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePayloadAssertionInterface.kt
Adds an integration test that checks the priority in which payloads are pruned. This also fixes a bug where the most recent session was deleted due to the reuse of a comparator that isn't correct for this specific use-case.
=> Add integration test for payload pruning

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/DeliveryConnectivityFeatureTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/DeliveryFixtures.kt
When the SDK loaded there was nothing that triggered the delivery of completed payloads that were stored on disk. I've taken the approach of invoking the `SchedulingService` when the SDK initializes. We could add a more specific function if that's semantically desired but for now I just called `onPayloadIntake()`.
Added an integration test
=> Trigger initial delivery of stored payloads

embrace-android-core/build.gradle.kts, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/EssentialServiceModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/EssentialServiceModuleSupplier.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/EmbraceProcessStateService.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/EmbraceProcessStateServiceTest.kt, embrace-android-sdk/build.gradle.kts, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceActionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/EssentialServiceModuleImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/UserApiDelegateTest.kt, gradle/libs.versions.toml
Adds a test artefact from the lifecycle libraries that allows us to cover more of the SDK surface area in integration tests. Previously we were directly invoking callbacks on `ProcessStateService`. However, since 2.3.0 the androidx lifecycle library has provided an artefact that allows dispatching test events (effectively this just implements the `LifecycleOwner` interface).
I've added this library & updated the integration tests so that a dummy lifecycle owner is passed through during test initialization. This should make it more obvious if changes to this library ever break our SDK.
=> Add lifecycle testing library

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/OkHttpRequestExecutionService.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/OkHttpRequestExecutionServiceTest.kt
Give requests back to our server 60 seconds to finish before timing out. This was the value we used previously for the old implementation.
=> Set read timeout to 60 seconds

.gitignore, build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/embrace-test-defaults.gradle.kts, buildSrc/src/main/kotlin/enable-explicit-api-mode.gradle.kts, embrace-lint/build.gradle.kts
Bumps Kotlin to 2.0.21. We still maintain compatibility back to 1.8.22 by setting the `apiVersion/languageVersion` attributes, so it's not anticipated this change will affect any end-user experience.
Relied on existing test coverage & reviewed [release notes](https://kotlinlang.org/docs/whatsnew20.html).
=> [DNM] Bump kotlin dependency

UPGRADING.md, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/lint-baseline.xml, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/FlutterInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ReactNativeInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/UnityInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/AppFramework.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/LastRunEndState.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/AppFrameworkExt.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/EmbraceAndroidApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/SdkStateApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegateTest.kt, embrace-test-fakes/lint-baseline.xml
Moves the `AppFramework` and `LastRunEndState` into top level classes. This is a breaking change so should be shipped as part of 7.0.
=> [DNM] Move nested classes into top level classes

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/spans/EmbraceSpan.kt, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/spans/EmbraceSpanEvent.kt, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/spans/ErrorCode.kt, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/spans/TracingApi.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceTracer.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.java, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeTracingApi.kt
Removes the beta annotation from the tracing api. This should only be merged as part of 7.0.
=> [DNM] Remove beta annotation from tracing api

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt
Make the retry after after getting a 429 a millisecond after the actual time that we should unblock so it can't possibly be the same timestamp.
Added a comment about why we are bit shifting as well per the review.
=> Updating next retry time after being 429'd

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/FakeCacheStorageService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePayloadStorageService.kt
Track payloads queued for deletion and only attempt to send payloads that aren't queued to be deleted. To support this, I added a basic callback to the `delete` function. Didn't want to complicate things.
Existing tests verify that this works.
=> Don't queue a send for payloads being deleted

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImplTest.kt
Clarify the code a bit and added a test to check that coming back on line will re-trigger any sends that are eligible.
=> Might work status code more readable

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/ExecutionResult.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/HttpUrlConnectionRequestExecutionService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/OkHttpRequestExecutionService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/RequestExecutionService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/HttpUrlConnectionRequestExecutionServiceTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/OkHttpRequestExecutionServiceTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeRequestExecutionService.kt
Created `ExecutionResult` to model the result... of the execution. It's a subset and simplified version of `ApiResponse` which was being used and contains a bunch of things that aren't necessary, as well as gaps that are now explicitly handled, e.g. non failure status codes, retry definition, etc.
This is laying the ground work to better handle various results in terms of whether we retry or log their failure.
Existing tests should cover this. I changed the names in the tests for the OkHttp version but not the HttpUrl one because it'll be gone soon anyway...
=> New abstraction for the result from an execution service attempt

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNetworkConnectivityService.kt
The v2 delivery layer was setting a network connectivity listener early in the bootstrapping which led to initializing OkHttp on the main thread, which is an expensive operation. To fix this I've set the listener at the end of SDK init on a background thread as it's not essential.
=> Optimize performance of v2 delivery layer

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStore.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/orchestrator/V2PayloadStoreTest.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/PayloadType.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadata.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/HttpUrlConnectionRequestExecutionService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/OkHttpRequestExecutionService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/RequestExecutionService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/StoredTelemetryMetadataTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/HttpUrlConnectionRequestExecutionServiceTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/OkHttpRequestExecutionServiceTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeRequestExecutionService.kt
Add `X-EM-TYPES` header to post requests with the type of payload we are sending. 
We are sending the following possible types: 
- "session"
- "sys.log"
- "sys.android.crash"
- "sys.android.native_crash"
- "sys.android.react_native_crash"
- "sys.flutter_exception"
- "sys.exit"
- "sys.exception"
- "sys.network_capture"
- "unknown"
=> Send payload type as a header

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AnrFeatureTest.kt
Using a blockable executor for the ANR worker means a lot of jobs were stuck by default before we needed to block it to simulate ANR capture. Since we were already setting the executor to blocking mode before we capture the ANR, we can set it to default to non-blockable so we only block the thread (when we need to).
This speeds up the execution of the tests as something in the `recordSession` flow, in the background/foreground callbacks, were taking ~1s each. Something was probably waiting for the something to execute, and then timing out at the 1s mark? Anyway, didn't look further as this fixes this tests.
I suspect any long running integration tests have the same issue
=> Default the anr monitor thread executor to non-blocking in integration tests

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/caching/PeriodicSessionCacher.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt
Makes two changes to the periodic cache logic. Firstly, the correct unit is used for the caching interval (this was altered during our delivery refactor & hadn't shipped to prod). Secondly, if `delete` fails due to `RejectedExecution` it should be run on the current thread as in this condition the worker will have shutdown.
=> Periodic cache bug fixes

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkService.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkServiceTest.kt
The initialization of the native crash signal handler happens after the first session (or sessions) is created, so instead of always initializing with no session, we use the sessionId provider to provide the latest one.
Did not a test because the current tests are not fit for purpose and I don't want to rewrite everything. We'll be doing this soon, so I'll leave it to whoever does it to check this. I ain't wasting my time mocking nothing.
=> Update session ID in the native layer after init

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/ApiResponseCache.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/EmbraceConfigService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/EmbraceConfigServiceTest.kt
We were storing config requests with HttpResponseCache but we were not using them. I added the necessary headers to hit the cache entries, and unzipped the result.
I also moved the initial config read to the main thread, to avoid race conditions where we try to read feature flags before they are initialized.
=> Fixed RemoteConfig cache

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/ApiClientImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/api/ApiClientImplTest.kt
Detect whether a response is gzipped and use the appropriate stream to read the data. If this isn't going away soon, I'd change it so we pass along the stream instead so if it doesn't need to be read, it won't be. But we are deleting this soon, so just do the minimum to validate it's working
Add unit tests
=> Detect whether response body is gzipped

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logging/EmbLoggerImpl.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeConfigService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/behavior/FakeSdkModeBehavior.kt
We only ever stop the SDK while it's started, and we validate that the SDK is started before we try to stop it. Somewhere along the way, we messed up this logic to make the SDK impossible to stop. This addresses that now.
Add integration test, and also make the FakeConfigService a bit smarter by taking into account the SdkModeBehavior when deciding whether the SDK is enabled.
=> Allow the SDK to be stopped when it's starting

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/envelope/session/SessionPayloadSourceImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/envelope/session/SessionPayloadSourceImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/JvmCrashFeatureTest.kt
We were including span snapshots for a session end caused by an app crash. How silly!
Add unit test and modify integration test to verify this
=> Only include span snapshots when process is not crashing

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crumbs/PushNotificationCaptureService.kt
Makes a defensive copy of a keyset in push notification capture to avoid the potential for ConcurrentModificationException.
=> Make defensive copy of keyset

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/EmbraceProcessStateService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ProcessStateService.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/IntegrationTestRule.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeProcessStateService.kt
The session orchestrator should be hooked up with after the SDK is initialized, so we'll log the case where it isn't true. The onForeground callback on it not being invoked can explain why some apps never get out of the background despite other callbacks being fired. This will help us narrow down the issue.
Verified this on all integration tests
=> Log situation when SDK starts up with orchestrator not hooked up

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/NoopEmbraceInternalInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/NoopFlutterInternalInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/NoopReactNativeInternalInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/NoopUnityInternalInterface.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/NoopEmbraceInternalInterfaceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/NoopFlutterInternalInterfaceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/NoopReactNativeInternalInterfaceTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/NoopUnityInternalInterfaceTest.kt
Provides no-op implementations of the internal interfaces if the SDK is not initialized yet. This should hopefully avoid NPEs on the hosted SDK side of things & make it easier to move this functionality in future.
=> Provide no-op implementations of internal interface

embrace-android-compose/build.gradle.kts, embrace-android-fcm/build.gradle.kts, embrace-android-okhttp3/build.gradle.kts, embrace-android-sdk/build.gradle.kts, embrace-internal-api/build.gradle.kts, embrace-internal-api/lint-baseline.xml, embrace-internal-api/src/main/kotlin/io/embrace/android/embracesdk/internal/EmbraceInternalApi.kt, embrace-test-fakes/build.gradle.kts, settings.gradle.kts
Creates a new module for our internal API. This is not pulled in by default - our hosted SDKs will have to explicitly add the dependency to access internal APIs. This should reduce the amount of unwanted symbols that are currently exposed to end-users.
=> Create internal api module

UPGRADING.md, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/behavior/BreadcrumbBehaviorImplTest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/instrumented/EnabledFeatureConfig.kt
Disables tap coordinate capture by default
=> Disable tap coordinate capture by default

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/NetworkSpanForwardingBehaviorImpl.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/instrumented/EnabledFeatureConfig.kt
This will allow to enable or disable network span forwarding from the embrace-config.json like the following:
```
{
"app_id": ...
...
"sdk_config": {
"networking": {
"enable_network_span_forwarding": true
}
}
}
```
If a remote config has been set, this will be ignored.
Depends on this Swazzler PR: https://github.com/embrace-io/embrace-swazzler3/pull/651
=> Added enable_network_span_forwarding local config flag

UPGRADING.md, embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/NetworkRequestApi.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/NetworkBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/NetworkBehaviorImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/behavior/NetworkBehaviorImplTest.kt, embrace-android-okhttp3/src/main/java/io/embrace/android/embracesdk/okhttp3/EmbraceOkHttp3ApplicationInterceptor.kt, embrace-android-okhttp3/src/main/java/io/embrace/android/embracesdk/okhttp3/EmbraceOkHttp3NetworkInterceptor.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/instrumented/NetworkCaptureConfig.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/NetworkRequestApiDelegate.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/SdkCallChecker.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlConnectionDelegate.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/InternalNetworkApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/InternalNetworkApiImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeInternalNetworkApi.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/NetworkRequestApiDelegateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlConnectionDelegateTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlStreamHandlerTest.kt, embrace-internal-api/src/main/kotlin/io/embrace/android/embracesdk/internal/EmbraceInternalApi.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/behavior/FakeNetworkBehavior.kt
Remove support for setting an custom name for the header where we expect to find a custom traceId that we will then log as part of the network request data. After this, we will only look for the custom traceId in the header `x-emb-trace-id` of the request.
=> Delete custom traceId header name support

UPGRADING.md, embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/UserApi.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/user/EmbraceUserService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/user/UserService.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/capture/user/EmbraceUserServiceTest.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/PersonaFeaturesTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/UserApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/UserApiDelegateTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeUserService.kt
Delete the methods to explicit add and remove the "payer" persona. Customers that use that can add a custom persona called "payer" to achieve the same effect.
=> Remove the payer person API methods

embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/UserApi.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SessionApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UserFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/V1DeliveryFeatureTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/UserApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/UserApiDelegateTest.kt
Deprecate these methods - they will still work, but we don't want to support these going forward, as we should allow customers to set key-value pairs attached to the specific user rather than have methods that explicitly call out PII, which we don't want to handle.
=> Deprecate explicit storing of PII in telemetry

UPGRADING.md, embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/SdkStateApi.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegateTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeMetadataService.kt
Remove support for setting appId at runtime
=> Delete the setAppId method

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/EmbraceConfigService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/ConfigModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/ConfigModuleSupplier.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/EmbraceConfigServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/ConfigModuleImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/SdkStateApiDelegate.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapperTest.kt
Clean up SDK init to not assume the configured appId can be overridden at runtime
=> Remove support of custom appIds in SDK internals

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/RemoteConfigTest.kt
Reorganises the integration tests so that remote config is stored in an individual source file.
=> Move remote config tests

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/ConfigServiceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/ConfigModuleImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/ConfigServiceImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePayloadAssertionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/server/FakeApiServer.kt
Adds assertions to check that a config request was attempted. Additionally boosted the timeout to 10s as this may have been contributing to flakiness on CI.
It's not possible to use this right now because HttpUrlConnection doesn't play well with the tests - once OkHttp is used in the config request it should make this more testable.
=> Add assertions for checking config request made

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/IntegrationTestRule.kt
Removes `inline` from `runTest` which stops a failure in the integration tests, specifically `EmbraceInternalInterfaceTest`.
I assume this is because test code was moved in this commit, and inlining the function means some property was not always setup correctly: https://github.com/embrace-io/embrace-android-sdk/pull/1640/files#diff-3c7d753cda41b1a11be4b6fd644cc07b341483a78ea6c29980f0382211887704
=> Avoid inlining runTest function

examples/ExampleApp/gradle/wrapper/gradle-wrapper.properties, gradle/wrapper/gradle-wrapper.properties
Bumps Gradle [to 8.11](https://docs.gradle.org/8.11/release-notes.html) which improves compilation error messages.
=> Bump gradle to 8.11

embrace-android-core/build.gradle.kts, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/ApiUrlBuilder.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiUrlBuilder.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/OkHttpRemoteConfigSource.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/EssentialServiceModuleImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiUrlBuilderTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/OkHttpRemoteConfigSourceTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeApiUrlBuilder.kt
Adds an OkHttp implementation of the `RemoteConfigSource` interface. Ultimately this will be used to make requests to the config endpoint - for now it's not invoked in production code. The implementation does not deal with caching/scheduling the request, but the actual HTTP request & error handling should be considered complete for the purposes of review.
=> Add OkHttp implementation of RemoteConfigSource interface

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/source/CachedRemoteConfigSource.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/source/CombinedRemoteConfigSource.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/source/OkHttpRemoteConfigSource.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/source/RemoteConfigSource.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/source/RemoteConfigSourceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/store/RemoteConfigStore.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/store/RemoteConfigStoreImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/OkHttpRemoteConfigSourceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/source/CombinedRemoteConfigSourceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/store/RemoteConfigStoreImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeRemoteConfigSource.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeRemoteConfigStore.kt
Supports etags in the OkHttp config request. The etag header value is persisted so that it can be used across processes.
Added a unit test & removed a flaky one.
=> Add etag support to okhttp

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/ExecutionResult.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/HttpUrlConnectionRequestExecutionServiceTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/OkHttpRequestExecutionServiceTest.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImplTest.kt
`Retry-After` was assumed to be in milliseconds in `ExecutionResult` whereas it's actually in seconds according to MDN. `ApiResponse` in the old delivery layer assumes seconds. The server doesn't actually send the header yet but when it does we should assume the incoming unit is in seconds.
=> Alter units for retry-after header

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/ConfigModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/ConfigModuleSupplier.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/NetworkRequestApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/BreadcrumbFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/JvmCrashFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/RemoteConfigTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ResurrectionFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/V1DeliveryFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/BackgroundActivityTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/ManualSessionTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/OtelSessionGatingTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePayloadAssertionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePreSdkStartInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/server/FakeApiServer.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapperTest.kt
Adds integration tests that assert the remote config response controls whether the SDK is initialized or not. There are 2 scenarios tested here:
1. If the persisted config disables the SDK, a HTTP request will always be made whose response is persisted on disk
2. If the SDK starts normally, it will always attempt a HTTP request
=> Add integration tests for remote config disabling sdk

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/store/RemoteConfigStoreImpl.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePayloadAssertionInterface.kt
Stores the remote config response on disk uncompressed as it's relatively tiny & probably not worth the hit of gzipping.
=> Store remote config response uncompressed

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiUrlBuilder.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiUrlBuilderTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/delivery/EmbracePendingApiCallsSenderTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/network/logging/EmbraceNetworkCaptureServiceTest.kt
#1656 mistakenly added `/api` as a prefix of the span + log endpoints, whereas in reality this isn't used. I've updated the code to point at the correct endpoint. This likely crept in because the integration tests require _some_ path to be specified for the baseUrl of mockwebserver, and I picked 'api'.
Updated unit tests to use correct assertions & confirmed that config, log, and session requests succeed.
=> Use correct endpoint for spans + logs

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiUrlBuilder.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/source/CombinedRemoteConfigSource.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/ConfigModuleImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/api/EmbraceApiUrlBuilderTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/delivery/EmbracePendingApiCallsSenderTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/source/CombinedRemoteConfigSourceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/network/logging/EmbraceNetworkCaptureServiceTest.kt
The SDK instantiates OkHttp on the main thread which hit perf. We should load it on a background thread instead.
=> Create OkHttp on background thread during initialization

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/BehaviorThresholdCheck.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/SdkModeBehaviorImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/ConfigServiceImplTest.kt
Alters how the SDK calculates whether it should be disabled by checking the last 6 digits of the device ID. This matches the behavior with iOS & allows for more granular control of behavior.
=> Alter how threshold works for disabling the SDK

embrace-android-core/config/detekt/baseline.xml, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/caching/PayloadCachingServiceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModule.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleSupplier.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/debug/DeliveryTraceState.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/debug/DeliveryTracer.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/execution/OkHttpRequestExecutionService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePayloadAssertionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakeDeliveryModule.kt
Adds extra debugging for failures in the delivery layer. When a log/session envelope doesn't match the expected number of payloads in an integration test, the error message will now print a trace of important state changes & milestones that happened in the delivery layer.
This does not track all important events (e.g. resurrection) but IMO is good enough to include for now, and we can expand it later if needed.
An example of what an error message looks like can be found below, which was generated by tweaking an assertion in `BreadcrumbFeatureTest` to fail.
```
Expected 3 envelopes, but got 2. Envelopes: [{sessionId=E9BDFEFCA7E64D79AE94AEBBA8C05435, cleanExit=true, state=foreground}, {sessionId=C946E4B93A5947709786DCC10A60589F, cleanExit=true, state=foreground}].
Delivery layer Trace …
```
=> Add extra debugging for delivery layer failures

embrace-android-sdk/src/main/cpp/safejni/jni_util.c, embrace-android-sdk/src/main/cpp/serializer/file_writer.c, embrace-android-sdk/src/main/cpp/utils/utilities.c, embrace-android-sdk/src/main/cpp/utils/utilities.h
Reverts embrace-io/embrace-android-sdk#1664. Turns out emb_jniIsAttached was used by unity 😬 
Will remove dump_map as part of the ndk rework, once we check if we can stop storing and parsing map files.
=> Revert "Remove unused code from NDK"

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashHandlerInstaller.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashProcessor.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativePayloadCacher.kt
Adds the initial interfaces that will be used for splitting up the `NdkService` implementation. I've included 3 interfaces for installing, caching payloads, and processing crashes. The payload caching interface will need future change based on what we decide - I've biased towards just picking something that matches the existing function signatures for now so we can start splitting things up.
=> Add interfaces for NDK implementation

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/RemoteConfigTest.kt
Increases the timeout for checking remote config. The default timeout in the test is 1s, which doesn't seem to be enough for serializing, writing config to disk, then reading it from within the test, leading to flakiness on CI.
=> Increase timeout for checking remote config

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/FlutterInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/NetworkRequestApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PushNotificationApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ReactNativeInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SessionApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ActivityFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AeiFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AnrFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/BreadcrumbFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/JvmCrashFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/LowPowerFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/NetworkStatusFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/SensitiveKeysRedactionFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ThermalStateTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/V1DeliveryFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ViewFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/WebviewFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/BackgroundActivityDisabledTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/BackgroundActivityTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/ManualSessionTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/PeriodicSessionCacheTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/SequentialSessionTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/StatefulSessionTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/assertions/AttributeExtensions.kt
`assertMatches` was not adding values to the `expected` parameter which meant assertions did not fail in tests. I've fixed this by refactoring how the function works & altered a couple of assertions that were silently failing.
=> Fix bug in test assertion code

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crash/CrashDataSourceImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/CrashModuleImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/CrashModuleSupplier.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NdkService.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/crash/CrashDataSourceImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/injection/CrashModuleImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkServiceTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNdkService.kt
- The backend isn't considering any case where NDK and JVM crashes have the same ID. It might even bring issues.
- We weren't setting the ID correctly. If installSignalHandlers gets posted to the main thread handler before we set the ID, we will always use different IDs.
- I tested crashes on an armeabi-v7a device, and we only get native crashes. The CrashDataSource handler never gets called.
=> Remove unityCrashId, as we don't use it anymore

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt
Tracing of the delivery layer from flaky tests indicates that the payload store is erroneously telling the scheduling service that 0 payloads are persisted on disk. I'm suspicious that this might be due to the implementation of `storedFiles` in `getPayloadByPriority` as it uses a `ConcurrentSkipListSet`, whose operations are async. I'd hypothesise that in our tests and also in prod this can result in a race condition where payloads aren't delivered by the scheduling service on the first attempt (although subsequent attempts do result in delivery).
Altering the implementation to use `CopyOnWriteArraySet` should fix this if the theory is correct.
=> Use copy on write collection for tracking stored files

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkServiceRepository.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashProcessor.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashProcessorImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NdkService.kt
Adds functions to the `NativeCrashProcessor` interface and uses delegation to avoid unnecessary function declarations in `EmbraceNdkService`
=> Extract functions to new hierarchy

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AppExitInfoBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/prefs/EmbracePreferencesService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/prefs/PreferencesService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/aei/AeiDataSourceImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/aei/ApplicationExitInfoExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/aei/TraceResult.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/FeatureModuleImpl.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/aei/AeiDataSourceImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePreferenceService.kt
Improves the code quality of the AEI capture. I've attempted this by removing obsolete code constructs, renaming functions, moving to a more functional paradigm as opposed to mutating state, and by splitting up the data capture from the code that reads a trace file.
Relied on existing test coverage added in #1693
=> Improve AEI capture code quality

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/storage/EmbraceStorageService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/storage/StorageService.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/storage/EmbraceStorageServiceTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/NativeFeatureModule.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/NativeFeatureModuleImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNativeCrashHandlerInstaller.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashHandlerInstallerImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeInstallMessage.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NdkServiceRepository.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/jni/JniDelegate.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/injection/NativeFeatureModuleImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkServiceTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/NativeCrashHandlerInstallerImplTest.kt, embrace-android-infra/src/main/kotlin/io/embrace/android/embracesdk/internal/handler/AndroidMainThreadHandler.kt, embrace-android-infra/src/main/kotlin/io/embrace/android/embracesdk/internal/handler/MainThreadHandler.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeJniDelegate.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeMainThreadHandler.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNativeFeatureModule.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSharedObjectLoader.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeStorageService.kt
- Moved the native crash directory creation to EmbraceStorageService. Also handled a possible exception while this is created.
- Created EmbraceNativeCrashHandlerInstaller, with the logic related to installed the signal handlers copied from EmbraceNdkService.
Some considerations when comparing EmbraceNdkService and this new EmbraceNativeCrashHandlerInstaller:
- symbolsForCurrentArch should be moved to the native thread sampler.
- unityCrashId was removed.
- I'm passing the activeSessionId as a class dependency in form of a string, instead of a provider from SessionIdTracker. If we needed the provider to avoid resolving this too quickly, this could be rolled back.
- Listeners that handle updates to session properties, ids, or other metadata should be added in another class. We should check …
=> Add native crash handler installer

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/NativeFeatureModule.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/NativeFeatureModuleImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashDataSourceImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NdkService.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/injection/NativeFeatureModuleImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/EmbraceNdkServiceTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/NativeCrashDataSourceImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/NativeCrashProcessorImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeJniDelegate.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNativeCrashProcessor.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNativeFeatureModule.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNdkService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSymbolService.kt
Splits the `NativeCrashProcessor` and `SymbolService` out of the `NdkService` implementation. There are no functional changes with this PR.
Updated existing unit tests where required.
=> Split ndk service

UPGRADING.md, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImplTest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/instrumented/schema/EnabledFeatureConfig.kt
Disables signal handler reinstallation by default.
=> Alter whether sig handler detection enabled by default

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/FileStorageService.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/FileStorageServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/FileStorageServiceImplTest.kt
Extracts file storage to a separate class so that it can be used for storing NDK payloads too.
Mostly relied on existing test coverage as `PayloadStorageService` is well tested.
=> Extract file storage to separate class

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/NativeCoreModuleImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/StorageLocation.kt
Extracts the logic that declares where files are stored from `PayloadStorageService` as we will need to use this for the NDK crash reporting too.
=> Extract storage dir logic from payload storage service

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/NativeCoreModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/NativeCoreModuleSupplier.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashHandlerInstallerImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashProcessorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeInstallMessage.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/jni/JniDelegate.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/jni/JniDelegateImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/NativeCoreModuleImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/ndk/NativeCrashHandlerInstallerImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/ndk/NativeCrashProcessorImplTest.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/FileStorageServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/storage/PayloadStorageServiceImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/main/cpp/jnibridge/emb_ndk_manager.c, embrace-android-sdk/src/main/cpp/jnibridge/emb_ndk_manager.h, embrace-android-sdk/src/main/cpp/utils/utilities.c, embrace-android-sdk/src/main/cpp/utils/utilities.h, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeJniDelegate.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSessionIdTracker.kt
Updates the native crash processor to use `FileStore` to read crash reports.
Relied on existing test coverage & added extra test cases where appropriate.
=> Use FileStore for NDK crash reports

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DeliveryModuleImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/debug/DeliveryTraceState.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/debug/DeliveryTracer.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/intake/IntakeServiceImpl.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt
Enhance the delivery tracing by adding some extra events in the `SchedulingService`. If an integration test fails now it should give us a decent idea of what's going wrong.
=> Add debug tracing to scheduling service

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/annotation/ObservedActivity.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadEventEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadEventEmitterTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeObservedActivity.kt
Restrict the activities for which loading will be traced. Initially, we will look for a specific annotation on an Activity, but ways to specify this will be added in later PRs.
Add unit tests
=> Create annotation to opt into activity open tracing

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupDataCollector.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupTracker.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeAppStartupDataCollector.kt
Add the ability to invoke a callback when an app startup trace is ready to be logged. This mechanism will be used to hook up the `UiLoadEventEmitter` in a subsequent PR
=> Create callback mechanism to run code post app startup

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupTracker.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/StartupTrackerTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeAppStartupDataCollector.kt
Remove the startup tracing callback when it's done its job. That way, it can never conflict with the UI load activity lifecycle listener when it's attached in a subsequent PR.
Add unit tests
=> Remove startup trace recording callback once it's logged startup

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/schema/KeySpan.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanBuilder.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/payload/SpanMapperTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanBuilderTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceTracerTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/InternalTracerTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/SpanServiceImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ExternalTracerTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UiLoadTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/arch/EmbraceAttributeExtensions.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/assertions/EmbraceSpanDataAssertions.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpanData.kt
Removes the concept of key spans from the SDK. This attribute was used by the backend to aggregate spans but is no longer required given the backend checks for root spans instead.
=> Remove concept of key spans

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/debug/DeliveryTraceState.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/debug/DeliveryTracer.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePayloadAssertionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/server/FakeApiServer.kt
Improves the error message logged out when an integration test fails due to the envelopes not matching what is expected.
=> Improve debuggability of integration tests

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/spans/TracingApi.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceTracer.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.kt
Fixes a few places where the `AutoTermination` enum wasn't getting passed through. I also removed it as a parameter from `recordCompletedSpan` as it doesn't make sense in the context of that function. I debated removing it from `recordSpan` but believe it makes sense to keep it there given that the code block could potentially run for a long time.
Relied on existing test coverage. An upcoming PR will include the integration test that originally caught these problems.
=> Fix auto termination propagation

embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/debug/DeliveryTraceState.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/debug/DeliveryTracer.kt, embrace-android-delivery/src/main/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImpl.kt, embrace-android-delivery/src/test/kotlin/io/embrace/android/embracesdk/internal/delivery/scheduling/SchedulingServiceImplTest.kt
Simplifies the delivery loop logic to avoid checking state as this was causing flakes in our integration tests. 
It's worth noting that (1) `deliveryLoop` can now be called multiple times and (2) `queueDelivery` is much more likely to fail as a consequence of this change, once old payloads are deleted from disk. FWIW, both of these conditions could occur with the old approach too via `scheduleDeliveryLoopForNextRetry`.
One alternative given that `deliveryWorker` is only ever used in this class would be to have `deliveryWorker` infinitely poll a `BlockingQueue`, and to have `schedulingWorker` add to that queue. This adds complications around checking for uniqueness on the elements in the queue & is a larger change, however.
Alternatively, given this is just an issue in testing & not really …
=> Simplify delivery loop logic

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/schema/EmbraceAttributeExt.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/EnvelopeExt.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionServiceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceExtensions.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/EmbraceLogServiceTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionServiceImplTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/NativeFeatureModuleImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashDataSourceImpl.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/NativeCrashDataSourceImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ReactNativeInternalInterfaceTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNativeCrashService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePersistableEmbraceSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSession.kt
Use appState and session properties from associated session when sending native crashes. Prior to this, metadata from the current session was being used erroneously. Now, we will grab this from the session that is associated with the crash that will be resurrected.
In a later PR, the code will be modified to take from the cached payload envelope if a session doesn't exist.
=> Add session properties to native crashes from the associated session

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logging/EmbLoggerImpl.kt, embrace-android-infra/src/main/kotlin/io/embrace/android/embracesdk/internal/logging/EmbLogger.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/InternalErrorLogTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbLogger.kt
The internal error logger was set in `ModuleInitBootstrapper` at a point where it would return false, meaning internal error logs were effectively not sent in 6.13.0. I've fixed this by setting the value via a lambda (as was the case in versions below 6.13.0). I also added the lambda as a property of the logging interface so that it's testable with the fake implementation.
Added an integration test.
=> Set internal error logger correctly

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/envelope/session/SessionPayloadSourceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/PayloadSourceModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/SpanRepository.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/envelope/session/SessionPayloadSourceImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/PayloadFactoryBaTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/SessionHandlerTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/SpanAutoTerminationTest.kt
Implements auto-termination of spans. This is achieved by checking whether a span has `AutoTerminationMode.ON_BACKGROUND` just before the session payload is constructed, and terminating it and its descendants if this is true.
Added integration tests.
=> Allow auto termination of spans

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/EmbraceAndroidApi.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/EmbraceLogRecordExporter.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/OpenTelemetryConfiguration.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanExporter.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/EmbraceLogRecordExporterTest.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ActivityFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/DisableSdkFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/LowPowerFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/IntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceOtelExportAssertionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/export/FilteredLogExporter.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/export/FilteredSpanExporter.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt
Adds a `disableDataExport` function to our public API that prevents exporting data via OTel exporters or HTTP requests. This calls `stop()` which shuts down all executors internally, and deletes any persisted data/blocks OTel exporters from exporting more data.
The intention is that an app would call this function if a user opted out of tracking halfway through a session, and on the next launch they would conditionally initialize the Embrace SDK.
Added an integration test & ran manual tests in example app.
=> Add ability to disable data export

.github/workflows/swazzler-tests-subset.yml
Runs the full set of swazzler tests on CI as this should help us catch when things break.
=> Run full swazzler tests

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashHandlerInstallerImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/jni/JniDelegate.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/jni/JniDelegateImpl.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeJniDelegate.kt
Prevents a null session ID from crashing in the JNI due to not checking for null. I fixed this by serializing `null` instead, which is the previous behavior before our NDK refactors.
=> Prevent null session ID crashing ndk processing

.github/workflows/swazzler-tests.yml
Updates the swazzler-test workflow due to repo reorganisation.
The ref in the workflow needs to be updated before merging to main, but this allows us to test the workflow now.
=> Update swazzler test workflow

.github/workflows/swazzler-tests.yml, buildSrc/src/main/kotlin/embrace-prod-defaults.gradle.kts
Publishes the SDK artefact without generating Javadoc, which is a bottleneck in build time and doesn't affect things for test purposes.
`./gradlew publishDebugSdk` can be used to run this task.
=> Publish local artefact without javadoc

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ResurrectionFeatureTest.kt
Disabling flakey test until I figure out why if the internal logs are sent after the native crash, we never get it in the mock server
=> Disable flakey resurrection test for now'

embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt
Add tests to verify that interrupted load will still yield UI load traces
=> Add tests for interrupted UI loads

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadEventListener.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeUiLoadEventListener.kt
Add in the ability at the `UiLoadTraceEmitter` level to designate a UI Load trace to be ended manually. This has not been hooked up with the API yet so it cannot be triggered externally yet.
=> Add option to manually end UI load trace

.github/workflows/ci-gradle.yml, buildSrc/build.gradle.kts
Updates codecov GH action to the latest version.
=> Bump codecov/codecov-action from 4 to 5

embrace-android-sdk/src/main/cpp/serializer/file_writer.c, embrace-android-sdk/src/main/cpp/unwinders/stack_unwinder.cpp, embrace-android-sdk/src/main/cpp/unwinders/unwinder.c
Tested by reducing kEMBMaxSFrames to 3, and forcing a native crash. Before this fix, either the native crash is lost due to an exception, or the native crash is sent but with trash data (things like sessionId containing a stack frame or other weirdness).
Now, the native crash is sent correctly, but capped to 3.
In the future, we might want to: 
- Increase the kEMBMaxSFrames limit.
- Add some kind of warning to let the user know that the stacktrace was limited.
=> Avoid out of bound access to emb_exception->stacktrace

embrace-android-sdk/src/main/cpp/utils/string_utils.c, embrace-android-sdk/src/main/cpp/utils/string_utils.h, embrace-android-sdk/src/test/cpp/testcases/utilities/test_string_utils.c
We use strncpy in many places. In almost all places, we call it with the size of the destination array. That means something like this:
```
char destinationArray[3]
char sourceArray[5]
emb_strncpy(destinationArray, sourceArray, sizeof(destinationArray))
```
In that case, sizeof(destinationArray) will be 3. That means the while loop will execute until 4, and we will try to write `src[3]` to `dst[3]`, which is out of bounds.
While C might let you write out of bounds, it may cause memory corruption or failure. 
Changes: 
- Modified the while loop so `i` won't be equal to `destination_len`.
- Added a `source[i] != '\0'` verification in case the source is smaller than the destination. Strings passed in src should end in that termination char. If they don't, we might face another OOB. We could …
=> strncpy out of bounds fix

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadEventListener.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeUiLoadEventListener.kt
A renaming of interface and objects to make them align better with their purpose. Note there are additional naming changes down the line, i.e. `exit` becomes `discard`.
=> Align event emitter names with lifecycle methods

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UiLoadTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceActionInterface.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/assertions/EmbraceSpanDataAssertions.kt
Simplify the UI load trace by starting it on the first sign of the triggering lifecycle event. 
What we give up is including in a trace the time between when the previous activity was paused to when the new activity starts to be created. But this allows us to not worry about the state of the app prior to the start of the activity loading, which removes a lot of complexity when dealing with edge cases.
I think this simplification is overall beneficial, and if we want to add this back, we can do it later.
Add appropriate unit and integration tests.
=> Change start time of UI Load traces

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/annotation/NotTracedActivity.kt, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/annotation/ObservedActivity.kt, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/annotation/TracedActivity.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImplTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleImpl.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExtTest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/instrumented/schema/EnabledFeatureConfig.kt, embrace-android-sdk/embrace-proguard.cfg, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UiLoadTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNotTracedActivity.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeObservedActivity.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeTracedActivity.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/behavior/FakeAutoDataCaptureBehavior.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/config/FakeEnabledFeatureConfig.kt
Add in annotations that allow a local config to specify that all activities loads are traced, with an opt-out annotation for those that shouldn't be.
Note: a change to the swazzler is needed to properly wire this up, but the SDK changes are all contained and tested in this PR.
=> Allow all activities to ge traced by default

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/annotation/CustomLoadTracedActivity.kt, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/annotation/CustomTracedActivity.kt, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/annotation/LoadTracedActivity.kt, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/annotation/TracedActivity.kt, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/InstrumentationApi.kt, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/SdkApi.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImplTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModule.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleImpl.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExtTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleImplTest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/instrumented/schema/EnabledFeatureConfig.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UiLoadTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceActionInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/InstrumentationApiDelegate.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeCustomTracedActivity.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeTracedActivity.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/behavior/FakeAutoDataCaptureBehavior.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/config/FakeEnabledFeatureConfig.kt
Add in the ability to specify that a a UI Load trace should wait for a manual end as well as a public API to do that.
=> API and integration tests for manually ending UI load traces

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UiLoadTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceActionInterface.kt
Tweaked tests so the timing assertions are more readible.
=> Restructure assertions to remove magic numbers

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupTracker.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ui/DrawEventEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ui/FirstDrawDetector.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/StartupTrackerTest.kt, embrace-android-infra/src/main/kotlin/io/embrace/android/embracesdk/internal/logging/InternalErrorType.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeActivityLifecycleListener.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeDrawEventEmitter.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNotStartupActivity.kt
Extract the code to detect when a app startup is ended by the first activity drawing its first frame into its own class so it can be used for the UI Load trace as well.
=> Extract frame draw detection to its own component

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExt.kt
To make these traces work with our onForeground callbacks, which work off of different events, we delay the emission of the `start` event until `onStart` callbacks are all done. This will solve the synchronization issue as long as the onForeground callback is registered first, which should always been true for now.
Covered by existing tests that verify the start times of child spans and hot UI load traces
=> Delay starting of hot UI load traces until onStart completes

.github/workflows/swazzler-tests.yml
Fixes an incorrect path in a GH workflow that means test results aren't uploaded as an artefact.
=> Fix an incorrect path in a workflow

.github/workflows/swazzler-tests.yml
Ubuntu 22.04 has [Cmake 3.10 installed](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) but Ubuntu 24.04 does not, causing a build failure on the swazzler test workflow. Pinning this should resolve this specific problem until we decide to update.
=> Pin runner version

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceModifier.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt
Add the ability to customize an on-going UI Load trace with custom attribute and child spans. API to expose this to customers will come in the subsequent PR.
Unit tests
=> Custom attributes and child spans for UI Load traces

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/LogModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/EmbraceLogService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/LogService.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/EmbraceLogServiceTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/EmbraceInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/FlutterInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/LogsApiDelegate.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/ReactNativeInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/UnityInternalInterfaceImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/EmbraceInternalInterfaceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/FlutterInternalInterfaceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/UnityInternalInterfaceImplTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/LogsApiDelegateTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeLogService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakeLogModule.kt
Builds on #1805 by continuing a refactor of the `LogService` to simplify the parameters passed in. This should make it easier for when we add the file attachment functionality.
=> Additional log implementation refactor

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/LogsApi.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/attachments/Attachment.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/attachments/AttachmentErrorCode.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/attachments/AttachmentService.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/attachments/AttachmentTest.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/FileAttachmentFeatureTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/LogsApiDelegate.kt
Removes the size parameter from user hosted log messages as we will calculate this on the backend & the attribute was unnecessary
Updated existing tests.
=> Remove size parameter from user hosted log messages

embrace-android-core/src/main/java/io/embrace/android/embracesdk/WebViewChromeClientSwazzledHooks.java, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/ViewSwazzledHooks.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/WebViewClientSwazzledHooks.java
Restore public-ness of classes whose methods are injected into the bytecode by the swazzler
Note: lint picked up some nullality annotation issues so I added them. I hope this won't break things?
=> Restore public visibility of classes containing swazzled code

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceTracer.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/InternalTracer.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceTracerTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/InternalTracerTest.kt, embrace-android-okhttp3/src/main/java/io/embrace/android/embracesdk/okhttp3/EmbraceOkHttp3ApplicationInterceptor.kt, embrace-android-okhttp3/src/main/java/io/embrace/android/embracesdk/okhttp3/EmbraceOkHttp3NetworkInterceptor.kt, embrace-android-okhttp3/src/test/kotlin/io/embrace/android/embracesdk/okhttp3/EmbraceOkHttp3InterceptorsTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/EmbraceInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/EmbraceInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlConnectionDelegate.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/InternalNetworkApi.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/InternalNetworkApiImpl.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeInternalNetworkApi.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/EmbraceInternalInterfaceImplTest.kt, embrace-internal-api/src/main/kotlin/io/embrace/android/embracesdk/internal/EmbraceInternalInterface.kt, embrace-internal-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/delegate/NoopEmbraceInternalInterface.kt, embrace-internal-api/src/test/kotlin/io/embrace/android/embracesdk/internal/api/NoopEmbraceInternalInterfaceTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbraceInternalInterface.kt
Consolidated private APIs that exposed the SDK time and use the new public API instead.
=> Consolidate APIs to return the current SDK time

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/SpanRepository.kt
While building out the tree of spans to look for ones to auto terminate, make sure to access the completed spans is thread safe.
Changing the underlying map to a concurrent one should make it thread safe, and using the method to synchronize access will make consistent.
This runs only on background, so the extra bit of locking shouldn't affect perf things a great deal.
=> Synchronize access to complete spans

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/InstrumentationApi.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceActionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/export/FilteredSpanExporter.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/InstrumentationApiDelegate.kt
Add API to notify the SDK when the application object init has ended so we can better estimate the time it takes between the launching of the first activity from when the app object was created.
This makes the heuristic of identifying warm vs cold starts better.
=> API to notify SDK when application object created

.github/workflows/swazzler-tests.yml
Adds a step to run gradle plugin integration tests in the CI workflow.
=> Run integration tests on sdk workflow

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupTracker.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ui/DrawEventEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ui/FirstDrawDetector.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExtTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/StartupTrackerTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/export/FilteredSpanExporter.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeDrawEventEmitter.kt
Start the render span when the first frame starts to draw. This more accurately times the duration of the time it takes the frame to be delivered, rather than starting when resume ends.
=> Start render span when first frame callback is attached

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleImpl.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExtTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/StartupTrackerTest.kt
Split up and consolidate the logic to check whether the current API version fires pre and post lifecycle events and whether or not we we try to instrument rendering for UI Load events.
This is so that in a later PR, we can disable the rendering events without affecting everything else.
Existing tests pass
=> Consolidate and disambiguate version checking for load traces capability detection

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExt.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExtTest.kt
Disable rendering event usage in UI load traces for now, as the way it detects the first frame draw is on the Window's root view, which isn't compatible with Compose navigation. 
This means that for now, all versions of Android will end with the onResume event. 
Existing tests pass after adjustments
=> Disable the use of render events to construct UI load traces for now

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt
End UI load traces on `postResume` for API versions that support it. This will allow us to track the duration for all onResume callbacks.
Existing tests passed after adjustment
=> Use resume end for UI load end for now if possible

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleImplTest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/remote/RemoteConfig.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UiLoadTest.kt
Support remote config feature flag to turn on UI Load, default to disabled
Added unit and integration tests
=> Allow UI Load to be enabled remotely

.github/workflows/swazzler-tests.yml
Removes the swazzler functional test step as this has been removed from the swazzler repo.
=> Remove swazzler functional test step

build.gradle.kts
Increases the timeouts when publishing to Sonatype as suggested here: https://github.com/gradle-nexus/publish-plugin?tab=readme-ov-file#http-timeouts
=> Increase sonatype timeouts

.github/workflows/build-rc-workflow.yml
If we run check along publishToSonatype, the gradle integration test plugin won't be installed, and the tests will fail
=> Move gradle plugin check to a different step in build-rc-workflow.yml

embrace-android-sdk/embrace-proguard.cfg
Without those rules, enabling FCM capture with a proguard build resulted in a compilation error
=> Add proguard rules for FCM capture

buildSrc/src/main/kotlin/embrace-prod-defaults.gradle.kts
Removes the publishDebugSdk task as this was causing issues with signature mismatches when used locally with `publishToMavenLocal` at the same time, and also causes frustration when debugging as the sources aren't available.
=> Remove publishDebugSdk task

.github/workflows/build-rc-workflow.yml
Avoids running tests on the RC workflow for consistency between the SDK + swazzler process.
=> Avoid running tests on RC workflow

CHANGELOG.md
TIL: callouts are not standard markdown syntax
=> Fix formatting in changelog

.github/workflows/build-rc-workflow.yml
workflow_call wasn't working, and now GitHub Actions has unified inputs, so you can use inputs for both workflow_call and workflow_dispatch
=> Update build-rc-workflow.yml to use inputs instead of github.events.input

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/extension/EmbraceExtensionInternal.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/extension/utils/VariantConfigurationToEmbraceExtensionInternal.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/il2cpp/Il2CppUploadTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/r8/JvmMappingUploadTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/reactnative/EmbraceRnSourcemapGeneratorTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/registration/TaskRegistrar.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTaskRegistrationTest.kt
Ports code that has been merged into the swazzler repo recently.
=> Port merged code from swazzler repo

gradle.properties
Bumps the max metaspace to 2Gb in an attempt to workaround intermittent local build failures.
=> Bump max metaspace

.github/workflows/generate-baseline-profile.yml
Removes incorrect syntax for setting a token in the baseline profile workflow
=> Remove incorrect token setting in baseline profile workflow

.github/workflows/example-app-emulator-tests.yml, examples/ExampleApp/app/src/androidTest/kotlin/io/embrace/android/example/SmokeTest.kt
Adds a workflow that runs a smoke test to confirm the example app can launch its activity. This should allow us to merge dependabot PRs with more confidence.
=> Add example app instrumented test workflow

build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/embrace/internal/ProductionModuleConfig.kt, embrace-android-sdk/build.gradle.kts, gradle/libs.versions.toml
Configures the codecov plugin so that coverage is aggregated into one report rather than just using coverage from one module.
I wasn't able to get this working instantly with the gradle plugin module, [possibly due to this issue](https://github.com/Kotlin/kotlinx-kover/issues/728), so I'd suggest we just stick with our previous behavior & fix this when I have a bit more time to investigate what's going wrong.
=> Configure codecov plugin

gradle/libs.versions.toml
Use the same Kotlin version in the version catalog rather than defining versions in 2 places. This does not affect the Kotlin version exposed to consumers.
=> Use same kotlin version

.github/workflows/upload-artifacts-to-sonatype.yml, embrace-gradle-plugin/build.gradle.kts
Fixes the publishing workflow on CI by ensuring javadoc + source JARs are added to the publication for the gradle plugin. Additionally prevent the integration test plugin from getting uploaded by removing the task from execution in the CI workflow.
Ran the workflow and confirmed artifacts were uploaded in a closed state & an example app could compile with them: https://github.com/embrace-io/embrace-android-sdk/actions/runs/13369659964
=> Update publish workflow

embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/RnSourcemapTaskIntegrationTest.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/reactnative/EmbraceRnSourcemapGeneratorTask.kt
We introduced a bug in the gradle plugin in 7.1.0 that caused the sourcemap file we send to the backend to be invalid. We were writing binary data to the JSON directly, without formatting it as a string.
I corrected the integration test that verified this behavior, and asserted that now symbols are now parsed correctly in the backend.
=> Fix RN mapping file JSON bug

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupTracker.kt
Prevents a leak in startup tracing where an activity reference was held in an anonymous inner class, leading to a potential leak reported via LeakCanary.
Tested scenario via LeakCanary and confirmed that it happened before the changeset but not after.
=> Prevent activity leak in startup tracking

.editorconfig, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/extension/EmbraceExtensionInternal.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/extension/EmbraceExtensionInternalSource.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/extension/utils/VariantConfigurationToEmbraceExtensionInternal.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/registration/TaskRegistrar.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTaskRegistrationTest.kt
symbolsDir and projectType are only used in NdkUploadTaskRegistration so I added them as parameters wrapped in providers to not realize them too soon.
Relied in existing testing
=> Remove symbolsDir and projectType from EmbraceExtensionInternal and pass them directly to NdkTaskRegistration

embrace-android-compose/src/main/java/io/embrace/android/embracesdk/compose/ComposeActivityListener.kt, embrace-android-compose/src/main/java/io/embrace/android/embracesdk/compose/internal/ComposeClickedTargetIterator.kt, embrace-android-compose/src/main/java/io/embrace/android/embracesdk/compose/internal/EmbraceClickedTargetIterator.kt, embrace-android-compose/src/main/java/io/embrace/android/embracesdk/compose/internal/EmbraceGestureListener.kt, embrace-android-compose/src/main/java/io/embrace/android/embracesdk/compose/internal/EmbraceNodeIterator.kt
Prevents a rare crash in compose click detection. This was triggered by accessing elements of the compose tree on a background thread. It's possible the internals of compose may have changed to trigger this problem, as `SemanticNode` now has its properties implemented as customer getters.
Manually verified clicking a compose button is shown in the dashboard when the functionality is enabled.
=> Prevent rare crash in compose click detection

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/LifecycleStage.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UiLoadTest.kt
Add extra child span modelling the time after activity resumes to when the trace is manually terminated for completeness.
=> Create child span for time waiting for manual UI load ending

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt
Remove attributes useful for debugging the startup spans but ultimately little value for customers. If folks request these, we can add them back. The correctness of these spans are verified in tests with respect to the start and end times of child spans, so these are more information in production more than anything.
=> Remove low-value attributes added to startup spans

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/annotation/IgnoreForStartup.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/registry/ServiceRegistry.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ActivityLifecycleTracker.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ActivityTracker.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/StartupListener.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/registry/ServiceRegistryTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/ActivityLifecycleTrackerTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupTracker.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeActivityTracker.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNotStartupActivity.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSplashScreenActivity.kt
Add new, appropriately named annotation for activities to be ignored during app startup (i.e. splash screens whose loading does not represent the completion of app startup).
We used to use the old `@StartupActivity` annotation for Moments but that is terribly named, as it is literally not the activity you want to track for start up.
As well, I removed the listener infra that you can add to listen to app startup - it was only used for moments, so it's actually not ever used now.
=> Add a new annotation for splash screen activities

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupDataCollector.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupTracker.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/StartupTrackerTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeAppStartupDataCollector.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNotStartupActivity.kt
Use the init of an ignored splashscreen activity to detect the first sign the app process is running because of a user initiated launch. This reduces the false positive for detecting a warm start when app startup is so slow, it takes more than 2s to transition of app object creation finishing to activity init. Previously, it was ignoring the signal from an activity we didn't use for startup calculation.
We could do a better job at detecting this even further by eliminating the heuristic of "time between app object activity object init" to separate warm and cold startups, but switching to that needs a bit more research and experimentation than we have time for. 
This, combined with the use of `applicatinInitEnd()`, should be good enough now for those who seek directional accuracy, with …
=> Remove splash screen time in warm/cold app startup heuristic

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/EmbraceGradlePluginDelegate.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/AsmTasks.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/config/model/VariantConfig.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/il2cpp/Il2CppUploadTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/r8/JvmMappingUploadTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/reactnative/EmbraceRnSourcemapGeneratorTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/registration/RegistrationParams.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/registration/TaskRegistrar.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/config/VariantConfigDeserializerTest.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTaskRegistrationTest.kt
Replace uses of EmbraceExtensionInternal.config with variantConfigurationListProperty.
We were using the config property of EmbraceExtensionInternal all across the task registration code. I replaced it with variantConfigurationListProperty, and I'll remove EmbraceExtensionInternal in a following PR.
Some considerations: 
- Before these changes, variantConfigurationListProperty was realized pretty late, as it was only used in a provider in the telemetry service. Now, it's resolved quite early, in the same fashion as the EmbraceExtensionInternal config was resolved. We should look into it and try to delay the access to the config, though it'll be quite hard because we need to consult it quite often to know if tasks should be registered.
- NdkUploadTaskRegistrationTest are quite bad, we …
=> Use VariantConfigurationListProperty instead of EmbraceExtensionInternal

embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/PluginIntegrationTestRule.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/AgpSupportTest.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/EmbraceGradlePlugin.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/gradle/GradleVersion.kt, embrace-test-common/src/main/kotlin/io/embrace/android/gradle/config/TestMatrix.kt
Validate that the version used to build an app that uses Embrace is higher or equal than the minimum
Added an integration test that validates this behavior
=> Throw an exception when building with a Gradle version lower than the minimum supported

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/annotation/IgnoreForStartup.kt, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/annotation/StartupActivity.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/registry/ServiceRegistry.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ActivityLifecycleTracker.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/ActivityTracker.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/StartupListener.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/registry/ServiceRegistryTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/ActivityLifecycleTrackerTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupDataCollector.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupTracker.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/StartupTrackerTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeActivityTracker.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeAppStartupDataCollector.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNotStartupActivity.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSplashScreenActivity.kt
Revert app startup changes so we can release without leaving the feature in a partially changed state.
=> Revert in-flight app startup changes

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/r8/JvmMappingUploadTaskRegistration.kt
An error was reported in 7.1.0 where multiple jvmMapping tasks are registered with the same name. This change rolls back the naming logic to the one we used in 7.0.0, though keeping the new task name.
Relied on existing tests. Will add tests for dexguard next week.
=> Rollback naming logic for JvmMappingUpload tasks

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/PersistableEmbraceSpan.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePersistableEmbraceSpan.kt
Start the startup span as soon as it's reasonable that any terminations during it can result in it being captured as having failed.
Rely on existing tests for now to ensure there are no regressions. Additional tests will be added later to check for in-process termination when we're able to allow the finish to be triggered manaually
=> Start app start up root span early to detect terminations

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupDataCollector.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeAppStartupDataCollector.kt
Add the ability to defer ending of a startup trace until manually notified. Note that this has not been hooked up to the SDK yet, which will come in a subsequent PR. This just adds the ability to do so in the trace emitting and data collection components.
I also significantly refactored the tests so that I can test this more easily. Doing so reveal a small bug where the pre-create time was not used when available (the activity create time was always used), which this PR also addressed.
=> Support manual ending of an app startup trace

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/InstrumentationApi.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupDataCollector.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/StartupTracker.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleImpl.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/instrumented/schema/EnabledFeatureConfig.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/InstrumentationApiDelegate.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeAppStartupDataCollector.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/behavior/FakeAutoDataCaptureBehavior.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/config/FakeEnabledFeatureConfig.kt
Add `appReady()` to the public API that ends the startup trace if a local feature flag set on the AutoDataCaptureBehavior indicates that it should do so.
The code to derive the value for the flag will come in a later PR.
Add integration test
=> Hook up API to allow manual app start trace ending

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/PluginBehavior.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/PluginBehaviorImpl.kt
If failBuildOnUploadErrors is enabled, any error during an upload task in the gradle plugin will fail the build. If it's not, build should continue as usual.
Will add tests on specific tasks that use this property
=> Add failBuildOnUploadErrors gradle plugin property

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehavior.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/behavior/AutoDataCaptureBehaviorImplTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleImpl.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/instrumented/schema/EnabledFeatureConfig.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/config/arch/sdk/EnabledFeatureConfigInstrumentation.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/config/model/AutomaticDataCaptureLocalConfig.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/instrumentation/config/arch/sdk/ConfigInstrumentationAssertions.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/instrumentation/config/arch/sdk/EnabledFeatureConfigInstrumentationKtTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/behavior/FakeAutoDataCaptureBehavior.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/config/FakeEnabledFeatureConfig.kt
Add support in the plugin to pickup the appropriate attribute in the config file to enable/disable this.
Added unit tests in the gradle plugin an sdk behavior,. The integration tests have already been written as we were faking that  layer in the test.
=> Add support in the config file to enable manual ending of startup traces

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/source/CombinedRemoteConfigSource.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/config/source/CombinedRemoteConfigSourceTest.kt
Defer the reading of the etag until the request runs, which allows `HttpSource` (and its copy of the OkHttpClient) to be initialized in the background. The `response` object and the deserialization thereof will still need to happen on the main thread but will do so when it's really needed, when the config service is initialized, but it still allows us to eliminate the OkHttpClient creation.
=> Defer the initialization of the OkHttp client until it's needed

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleSupplier.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleImplTest.kt, embrace-android-sdk/embrace-proguard.cfg, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt
Eat the costs of logging the startup trace on the main thread so it will always be in the payload of the same session the trace ended in. This will take around 1ms on a mid-range device (Pixel 4) and about 4ms on a low end device (Samsung A14)
=> Log startup trace synchronously

embrace-gradle-plugin-integration-tests/build.gradle.kts, embrace-gradle-plugin-integration-tests/fixtures/android-with-code/build.gradle, embrace-gradle-plugin-integration-tests/fixtures/android-with-code/proguard-rules.pro, embrace-gradle-plugin-integration-tests/fixtures/android-with-code/src/main/AndroidManifest.xml, embrace-gradle-plugin-integration-tests/fixtures/android-with-code/src/main/java/com/example/app/Bar.java, embrace-gradle-plugin-integration-tests/fixtures/android-with-code/src/main/java/com/example/app/Foo.java, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/ApkDisassembler.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/ArtifactFinder.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/DecodedApk.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/smali/SmaliMethod.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/framework/smali/SmaliParser.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/AndroidNdkTest.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/ConfigInstrumentationTest.kt, embrace-gradle-plugin-integration-tests/src/test/resources/smali_example.smali
Adds a test that reads the smali files (generated from dex files) when disassembling the APK in a Gradle TestKit test case.
In short, this allows to verify our bytecode instrumentation at the integration test level. We can compare the expected return value against what is actually in the dex code.
Future changesets will increase the coverage of this test so that we check _all_ the config values that are instrumented, and also check the override behaviors.
=> Add validation for bytecode instrumentation that looks at smali files

embrace-gradle-plugin-integration-tests/fixtures/ndk-upload-simple/build.gradle, embrace-gradle-plugin-integration-tests/src/main/java/io/embrace/android/gradle/integration/framework/IntegrationTestExtension.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/NdkUploadTaskIntegrationTest.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/UnityTest.kt, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/UnsuccessfulHttpCallTest.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/EmbraceGradlePluginDelegate.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/PluginBehaviorImpl.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/HttpCallResultHandler.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/common/MultipartUploadTask.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/common/RequestParams.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/il2cpp/Il2CppUploadTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadHandshake.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTask.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/r8/JvmMappingUploadTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/reactnative/EmbraceRnSourcemapGeneratorTask.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/reactnative/EmbraceRnSourcemapGeneratorTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/registration/RegistrationParams.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/registration/TaskRegistrar.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTaskRegistrationTest.kt
If the gradle plugin fails during a HTTP request then it now throws an error. This can be disabled by setting `embrace.failBuildOnUploadErrors` to `false` in `gradle.properties`. This did necessitate removing try-catch blocks from a few places in the tasks but I think we would rather know if there are any hidden problems in these tasks than silently swallowing bugs.
I've added a test for 4xx + 5xx status codes for the proguard endpoint. I thought it was overkill to add test cases for every endpoint given that each test case takes at least a couple of seconds to execute & the code runs through the same path anyway.
=> Throw error if gradle plugin fails HTTP request

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/lifecycle/EmbraceProcessStateService.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/EmbraceProcessStateServiceTest.kt
Invoke the onBackground callback for the `SessionOrchestrator` last so that every other service has a chance to "do the wrap up before going into the background" thing.
Currently, this only affects the ANR service, which means it'll stop monitoring ANRs just before the session payload is taken. A side effect of this is our session payload creation time won't be counted in an on-going ANR, which seems to be correct to me as the app will soon not be on screen, so extending the blockage interval doesn't seem like it adds much value.
=> Change the order of the process state listen invocation

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/FlutterInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/LogRecordExporterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AeiFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AnrFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/DisableSdkFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/FileAttachmentFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/InternalErrorLogTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/LogFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/PruningFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/BackgroundActivityDisabledTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/PeriodicSessionCacheTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/StoredNdkData.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/assertions/PayloadAssertions.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapperTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbLogger.kt
Register `AppStartupTraceEmitter` as service so the `onBackground()` callback will be invoked when the app background while while app startup is still taking place
As a result, we had to make sure the integration tests that aren't faking app startup (which means the startup data it collects will be incomplete) ignore internal errors that are generated for when app startup trace cannot be generated. 
Similarly, startup traces will now be generated if the conditions are corrected, so those tests that assume that only the logs they create will be exported need to be modified to ignore the internal errors (which are also OTel logs).
=> Hook up SDK to abandon app startup trace on background

embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/DataSourceModuleImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/session/SessionOrchestrationModuleImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/crash/LastRunCrashVerifierTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/FlutterInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AeiFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AnrFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/DisableSdkFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/LogFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UiLoadTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/BackgroundActivityDisabledTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/PeriodicSessionCacheTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceActionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbracePreSdkStartInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/StoredNdkData.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbLogger.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakeWorkerThreadModule.kt
Simplify how you can use blocking executors for background and priority workers. This allows us to then not have to create new instances of `EmbFakeLogger` for integration tests, thus allowing us to just set the internal error exclusion when instantiating an instance of that for the integration test rule. In turn, this allows us to get rid of the poorly named/documented factory method for `FakeEmbLogger`.
=> Reduce the overridding surface area for integration test setup

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/api/EmbraceBytecodeInstrumentation.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/api/EmbraceExtension.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/swazzler/plugin/extension/SwazzlerExtension.kt
Adds the new extension that will form our plugin's public API. This is not publicly exposed as part of the plugin yet & the changeset is kept small so we can review the particulars of each property and its documentation.
=> Add new embrace extension

UPGRADING.md, embrace-gradle-plugin-integration-tests/fixtures/android-with-code/build.gradle, embrace-gradle-plugin-integration-tests/src/main/java/io/embrace/android/gradle/integration/framework/IntegrationTestExtension.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/EmbraceGradlePlugin.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/EmbraceGradlePluginDelegate.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/api/EmbraceBytecodeInstrumentation.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/InstrumentationBehaviorImpl.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/PluginBehaviorImpl.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/swazzler/plugin/extension/SwazzlerExtension.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/config/InstrumentationBehaviorImplTest.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/config/PluginBehaviorImplTest.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTaskRegistrationTest.kt
Aliases existing properties on the `SwazzlerExtension` interface onto the `EmbraceExtension` interface.
=> Alias swazzler extension onto embrace extension

UPGRADING.md, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/EmbraceGradlePlugin.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/EmbraceGradlePluginDelegate.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/InstrumentationBehavior.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/InstrumentationBehaviorImpl.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/PluginBehaviorImpl.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/AsmTasks.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/BytecodeInstrumentationParams.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/swazzler/plugin/extension/SwazzlerExtension.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/config/InstrumentationBehaviorImplTest.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/config/PluginBehaviorImplTest.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/instrumentation/fakes/TestBytecodeInstrumentationParams.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTaskRegistrationTest.kt
Ignores some obsolete properties on swazzler extension and marks them as deprecated.
=> Ignore obsolete properties on swazzler extension

embrace-gradle-plugin-integration-tests/fixtures/android-disable-product-flavor/build.gradle, embrace-gradle-plugin-integration-tests/fixtures/react-native-android/android/app/build.gradle, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/api/EmbraceExtension.kt
Updates the test fixtures to use the embrace extension rather than swazzler.
=> Update test fixtures to use embrace extension

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/PublicApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AnrFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/InternalErrorLogTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/NativeCrashFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/PersonaFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/PruningFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ResurrectionFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/SessionPropertiesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UserFeaturesTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/SdkIntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt
Miscellaneous changes to reduce the number of things you can override in the integration test setup. Most of what's being overridden was just so the tests can read the data, so either we provide the fake right in the setup object, or we expose the real component so it can be read.
These components were being faked universally in the integration tests anyway, so this doesn't make the tests less comprehensive.
Note: more changes are coming. I just had to break them up as I wanted to do some more targeted changes later on so they can be more easily reviewed.
=> Further simplify the integration test rule

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/FlutterInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/LogFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/BackgroundActivityDisabledTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/PeriodicSessionCacheTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/FakeCacheStorageService.kt
Most workflows don't require faking workers anymore since we have a wait-for-payload mechanism in the integration tests now, which is more representative of the actual workflow.
The one remaining worker to fake is for ANR testing. Not sure if we can do without it but leaving it in for now.
=> Reduce the usage of fake workers in integration tests

embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/ndk/NativeCrashProcessorImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/DeliveryConnectivityFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/NativeCrashFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ResurrectionFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceActionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSymbolService.kt
Instantiate fakes we always use within the setup interface and expose them for reading/altering. In addition, we don't prepopulate native symbols and instead rely on the tests to do the setup..
=> Further simplify the usage of the integration test rule

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AeiFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbLogger.kt
Don't log an internal error for any that are supposed to be ignored. And ignore the right error, not the error that is generated if that error isn't ignore, duh.
=> Really ignore startup trace recording error in integration tests

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/metadata/EmbraceMetadataService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ui/FirstDrawDetector.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceHttpUrlConnection.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceHttpUrlConnectionImpl.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceHttpsUrlConnectionImpl.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceUrlConnectionDelegate.java, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/util/GradleVersionTest.kt, embrace-test-common/src/main/kotlin/io/embrace/android/gradle/config/TestMatrix.kt, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties
Update AGP and Gradle and fix the issues identified in the upgrades
=> Update AGP to 8.9 and Gradle to 8.13 and fix new issues

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/schema/SchemaType.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/EmbraceAttributeKeys.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/prefs/EmbracePreferencesService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/prefs/PreferencesService.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/prefs/EmbracePreferencesServiceTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/aei/AeiDataSourceImpl.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AeiFeatureTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePreferenceService.kt
Adds an ordinal as an OTel attribute for AEIs containing a native crash. This will be incremented whenever an AEI object contains an NDK protobuf file - assumed by checking `reason == REASON_CRASH_NATIVE` and the `trace` property not being null.
Additionally, the existing `android.crash_number` attribute will be incremented for AEI crashes.
If the AEI object does not have an NDK protobuf file, the attribute value will be explicitly set as `"null"`.
Added test coverage.
=> Add ordinal for AEI native crashes

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/aei/AeiDataSourceImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/FeatureModuleImpl.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/aei/AeiDataSourceImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/aei/AeiNdkCrashProtobufSendTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AeiFeatureTest.kt
If `ndk_enabled` is false then AEI native crashes should not be delivered.
Added a test case.
=> Gate AEI native crashes by ndk_enabled flag

embrace-gradle-plugin-integration-tests/fixtures/android-dexguard/build.gradle, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/DexguardTest.kt
Adds a test case that checks DexGuard mapping files are uploaded.
=> Add gradle test case for dexguard

embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/FlutterInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ReactNativeInternalInterfaceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SessionApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ActivityFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AnrFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/FileAttachmentFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/JvmCrashFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/LogFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/LowPowerFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/NetworkStatusFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/SpanAutoTerminationTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UiLoadTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/ViewFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/BackgroundActivityDisabledTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/PeriodicSessionCacheTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/AppExecutionTimestamps.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceActionInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/SessionTimestamps.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/assertions/OTelLogAssertions.kt, embrace-android-sdk/src/integrationTest/resources/system-low-power-export.json, embrace-android-sdk/src/integrationTest/resources/ux-view-export.json
Make it so that session creation in integration tests will simulate the app/activity lifecycle of the app. This ensures that side effects from lifecycle handlers are taken into account when running the tests end to end.
To that end, I've adding more functionality to the `recordSession()` method, having it call `simulateOpeningActivities()` with the appropriate parameters, and returning an object that contains some useful timestamps to validate against.
This requires a few changes to the tests:
- Change time verifications now that the clock isn't only moved manually 
- Account for the extra telemetry that are logged as a result of going through the lifecycle
- Tweak some internals of the faking logic to ensure that the callbacks are invoked in the same order as in prod
=> Fake app lifecycle when faking a session during integration tests

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExt.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ui/DrawEventEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ui/HandlerMessageDrawDetector.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadExtTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/StartupTrackerTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ui/HandlerMessageDrawDetectorTest.kt, embrace-android-infra/src/main/kotlin/io/embrace/android/embracesdk/internal/handler/AndroidMainThreadHandler.kt, embrace-android-infra/src/main/kotlin/io/embrace/android/embracesdk/internal/handler/MainThreadHandler.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeMainThreadHandler.kt
Use an alternate way to detect that a frame was been delivered that works for Android 12 and Android 6 to 9. Implement a new `DrawEventEmitter` that uses this alternative method, and supply when the other one doesn't work.
All the unit tests have been updated to reflect this new reality, but the integration tests don't check for hardware based render events. But with this, we may be able to test this by simulating this, so stay tuned!
Manually tested for a subset of real devices/apps. Will test it more comprehensively.
=> Adds support for render detect for Android 6+

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt
Compose navigation isn't compatible with frame render detection, so I needed to disable it again because it'll be inconsistent,
Apparently I forgot why I disabled it in the first place....
Existing tests cover it.
=> Disable render tracking in UI loading

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ui/DrawEventEmitter.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt
Rename app startup render child span that tracks less. An alternative implementation is adding a new event to be tracked, and keying off that to create the span.
I don't like that because a new event adds little value for android versions that can do frame commit callbacks, and it adds complication to the code. Basically using one or the other and calling both of them render removes that distinction, so we just have to make sure the name is correct. I prefer this.
=> Rename less good version of render span for clarity

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/spans/EmbraceSpan.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/gating/SpanSanitizer.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/EmbSpan.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/SpanMapper.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceLinkData.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanData.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/SpanDataExt.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/opentelemetry/EmbSpanTest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/instrumented/schema/OtelLimitsConfig.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/Link.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/Span.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePersistableEmbraceSpan.kt
Add basic support for SpanLinks. A couple of things still have to be finalized:
- Payload shape
- Limits
Thought I'd get this in review first and made the approach changes after
Unit and integration tests added
=> Add support for SpanLinks

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/destination/SessionSpanWriter.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/session/EmbraceSessionProperties.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/OpenTelemetrySdk.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/SpanMapper.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/SessionOrchestratorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/session/orchestrator/SessionSpanAttrPopulatorImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceExtensions.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceLinkData.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/PersistableEmbraceSpan.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crumbs/BreadcrumbDataSource.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crumbs/PushNotificationDataSource.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crumbs/TapDataSource.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crumbs/WebViewUrlDataSource.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/memory/MemoryWarningDataSource.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/webview/WebViewDataSource.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/config/instrumented/schema/OtelLimitsConfig.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeCurrentSessionSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeDataSource.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePersistableEmbraceSpan.kt
Apply the total limits of attributes, event, and links correctly on the OTel layer, separating the ones added by users and others added by the SDK. The notion of system links was also added in this PR.
We were using the system one for the total when applying it at the OTel layer, which theoretically should be way more than needed, and should easily absorb the user ones without issue. Fixing this makes the OTel layer agree with the SDK layer, so if you can add an attribute through the SDK, it will be exported for sure.
Some method names on the `CurrentSessionSpan` interface was also renamed to clarify what it's doing
=> Set correct total limits on OTel layer

embrace-gradle-plugin-integration-tests/src/test/resources/instrumented-config-default.json, embrace-gradle-plugin-integration-tests/src/test/resources/instrumented-config-overrides.json
New fields were added to OTelLimitsConfig, so I added them to the instrumented-config json files in the order they get parsed in the tests. 
I'm not sure why the tests weren't broken in CI though.
=> Update instrumented-config json files to account for new OTelLimitsConfig fields

embrace-gradle-plugin-integration-tests/fixtures/compress-shared-object-files/build.gradle, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/CompressSharedObjectFilesTaskTest.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/CompressSharedObjectFilesTask.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTasksRegistration.kt
Use a custom property to enable and disable the task in tests. Will use this approach for the other tests too
=> Use failBuildOnUploadTask in CompressSharedObjectFilesTask

embrace-gradle-plugin-integration-tests/fixtures/hash-shared-object-files/build.gradle, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/HashSharedObjectFilesTaskTest.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/HashSharedObjectFilesTask.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTasksRegistration.kt
Use a custom property to enable and disable the task in tests.
=> Use failBuildOnUploadTask in HashSharedObjectFilesTask

embrace-gradle-plugin-integration-tests/fixtures/inject-shared-object-files/build.gradle, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/InjectSharedObjectFilesTaskIntegrationTest.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/CompressSharedObjectFilesTask.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/HashSharedObjectFilesTask.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/InjectSharedObjectFilesTask.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/UploadSharedObjectFilesTask.kt
Use a custom property to enable and disable the task in tests.
Also used correct logging class in all of the upload classes.
=> Use failBuildOnUploadTask in InjectSharedObjectFilesTask

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/EmbraceGradlePluginDelegate.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/AsmTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/registration/TaskRegistrar.kt
- Removed the old AsmTasks class. 
- Altered the order in which the tasks run overall. Now ASM will be done last. This will be used to plug the output of the Injection task as an input of the ASM one.
=> Create AsmTaskRegistration to register the ASM task in the same way as the rest of the tasks

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/gradle/TaskRegistrationUtils.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/AsmTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/BytecodeInstrumentationParams.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/instrumentation/fakes/TestBytecodeInstrumentationParams.kt
- Add an encodedSharedObjectFilesMap property to the params passed to ASM.
- Add a tryGetTaskProvider with class information.
- If the encodeSharedObjectFilesTask is found, make the asmTransformationTask depend on it, and wire the encodedSharedObjectFilesMap properties.
The build will fail if the encodeSharedObjectFilesTask is found but the asmTransformationTask is not, because symbols won't be injected as they should.
We are currently not using failBuildOnUploadTask on configuration time, but we should review this in the future.
=> Make ASM task depend on EncodeSharedObjectFilesTask if it exists

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/NativeCoreModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/symbols/SymbolServiceImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/ndk/symbols/SymbolServiceImplTest.kt, embrace-gradle-plugin-integration-tests/fixtures/android-cmake-with-code/build.gradle, embrace-gradle-plugin-integration-tests/fixtures/android-cmake-with-code/src/main/AndroidManifest.xml, embrace-gradle-plugin-integration-tests/fixtures/android-cmake-with-code/src/main/cpp/CMakeLists.txt, embrace-gradle-plugin-integration-tests/fixtures/android-cmake-with-code/src/main/cpp/crisps.c, embrace-gradle-plugin-integration-tests/fixtures/android-cmake-with-code/src/main/cpp/donuts.c, embrace-gradle-plugin-integration-tests/fixtures/android-cmake-with-code/src/main/embrace-config.json, embrace-gradle-plugin-integration-tests/fixtures/android-cmake-with-code/src/main/java/com/example/app/Bar.java, embrace-gradle-plugin-integration-tests/fixtures/android-cmake-with-code/src/main/java/com/example/app/Foo.java, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/AndroidNdkTest.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/AsmTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/il2cpp/Il2CppTaskSource.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTasksRegistration.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTasksRegistrationTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/config/FakeBase64SharedObjectFilesMap.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/config/FakeInstrumentedConfig.kt
I tried to keep this small but I had to replace many parts at once so it doesn't stop working.
- Stop looking into resources in the SDK, fetch symbols from the new instrumentedConfig field.
- Update SymbolService tests to verify behavior of the new injected symbols.
- Use project.afterEvaluate in AsmTaskRegistration to ensure that the AsmTask is found.
- Register EncodeSharedObjectFilesTask instead of InjectSharedObjectFilesTask (will remove this one in a following PR).
- Modify AndroidNdkTest: Now we're disassembling the apk and parsing the Smali to ensure the map is injected as expected. Removed resources verification.
=> Use the new EncodeMapTask output in the SDK and stop using resources

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/EmbraceClassVisitorFactory.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/visitor/BytecodeMethodInsertionParams.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/visitor/InstrumentationTargetMethodVisitor.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/visitor/OnClickClassAdapter.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/visitor/OnLongClickClassAdapter.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/visitor/WebViewClientClassAdapter.kt
Until now the bytecode instrumentation has assumed that we always want to mirror the function signature of the instrumented method in our own target API. This changes that assumption by allowing us to specify what variables should be loaded onto the operand stack.
Practically speaking, this means we can delete unused parameters such as `View.OnClickListener` in our bytecode API. This should simplify the code & therefore reduce surface area for bugs.
=> Alter how operand stack indices are specified

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/ClassVisitBehavior.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/EmbraceClassVisitorFactory.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/strategy/ClassVisitStrategy.kt
Formalises the strategies that we use to decide whether a class should be visited by a feature during instrumentation. This is an intermediate step towards making it easier to define this via config.
=> Create class visit strategy hierarchy

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTasksRegistration.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTasksRegistrationTest.kt
Using flatMap wires a dependency between the result and the outputs of the mergeNativeLibs task. 
Using map doesn't do that, so I think that's why the provider was realized before the outputs where available, causing the exception: 
```
* What went wrong:
Configuration cache state could not be cached: field `architecturesDirectory` of task `:app:compressSharedObjectFilesRelease` of type `io.embrace.android.gradle.plugin.tasks.ndk.CompressSharedObjectFilesTask`: error writing value of type 'org.gradle.api.internal.file.DefaultFilePropertyFactory$DefaultDirectoryVar'
> Shared object file not found
```
Also use elements.map so we don't resolve the task output files too early.
Tested manually: now the example app builds correctly. We will add additional configuration cache testing later.
=> Use flatMap instead of map to make the getSharedObjectFilesProvider depend on the outputs of merge[Variant]NativeLibs

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ui/DrawEventEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ui/FirstDrawDetector.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ui/HandlerMessageDrawDetector.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ui/HandlerMessageDrawDetectorTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeDrawEventEmitter.kt
Activity init events might not be processed when the onDraw event fires because the latter jumps in front of the main thread handler queue. In these rare cases, use that timestamp in place of the activityInit timestamps.
=> Use the draw complete time for missing activity init timestamps

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/UploadSharedObjectFilesTask.kt
Fixes error: 
```
[EmbraceGradlePlugin] [OkHttpNetworkService] Exception occurred while making network request
java.lang.NullPointerException: Cannot invoke "okhttp3.OkHttpClient.newCall(okhttp3.Request)" because the return value of "io.embrace.android.gradle.plugin.network.OkHttpNetworkService.access$getClient$p(io.embrace.android.gradle.plugin.network.OkHttpNetworkService)" is null
```
=> Inline OkHttpNetworkService

embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/ConfigCacheTest.kt
Ensures the CC test case exercises the NDK upload code path.
=> Enhance configuration cache test

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/ProjectTypeVerifier.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/registration/TaskRegistrar.kt
`getProjectType` was wrapped in a provider, without considering its dependency on `unitySymbolsDir`. As a result, when `projectType` was realized, it would try to realize `unitySymbolsDir` eagerly, potentially resolving it before it was available.
This change updates `getProjectType` to use `unitySymbolsDir.map`, wiring the dependency and ensuring that `unitySymbolsDir` is resolved only when needed.
=> Fix eager resolution of unitySymbolsDir in getProjectType

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTasksRegistration.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTasksRegistrationTest.kt
`getUnitySharedObjectFiles` was accessing `unitySymbolsDir` (using `orNull`) too early, which could mess with the build or with configuration cache if the symbols directory isn't ready yet.
This change switches to using `flatMap` so `unitySymbolsDir` is resolved lazily, only when needed.
Also removed a test that didn't make sense, as the provider we receive can't be null.
=> Fix eager resolution of unitySymbolsDir in shared object file provider

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTasksRegistration.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTasksRegistrationTest.kt
When using `mergeNativeLibsTask.flatMap` at the start of the shared object files provider, we were enforcing a dependency on the mergeNativeLibs task for Unity projects and projects that set up a custom symbols directory. 
While I think most Unity projects will have that task, I'm not sure if 100% of them will. Also, this would've been an unintended change from our last version.
=> Remove unnecessary dependency on mergeNativeLibsTask for customSymbolsDirectory and Unity

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTasksRegistration.kt
We were using `project.provider { projectType.orNull == ... }`, which could cause early resolution of projectType, ignoring its dependencies. Using map wires it correctly.
I think onlyIf might only be resolved in execution time, so we wouldn't be facing any issues here, but just in case, this is a more correct way of doing things.
Also, use map for failBuildOnUploadErrors instead of resolving it early.
=> Map projectType correctly in getShouldExecuteCompressionTaskProvider

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/EmbraceClassVisitorFactory.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/VisitorFactoryImpl.kt, embrace-gradle-plugin/src/main/resources/bytecode_instrumentation_features.json
Standardises the class visitor factory further by extracting the logic for whether a feature is enabled via the Gradle DSL into a function. I also rearranged the order of instrumentation in the JSON file so it matches what is currently done in the code.
=> Standardise class visitor factory

examples/ExampleApp/app/build.gradle.kts, examples/ExampleApp/app/src/main/AndroidManifest.xml, examples/ExampleApp/app/src/main/kotlin/io/embrace/android/exampleapp/ui/examples/bytecode/BytecodeFcmPushNotificationActivity.kt, examples/ExampleApp/app/src/main/kotlin/io/embrace/android/exampleapp/ui/examples/bytecode/BytecodeInstrumentationExample.kt, examples/ExampleApp/app/src/main/kotlin/io/embrace/android/exampleapp/ui/examples/bytecode/ExamplePushNotificationService.kt, examples/ExampleApp/app/src/main/res/layout/activity_bytecode_fcm_push_notification.xml, examples/ExampleApp/gradle/libs.versions.toml
Adds an example that simulates receiving a push notification, so that we can exercise the bytecode instrumentation API.
=> Add push notification bytecode example

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/instrumented/OtelLimitsConfigExt.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/SpanServiceImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/SpanServiceImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/SpansTestFixtures.kt
Internally created spans are able to have more attributes and span events than ones created via the SDK APIs, but the validation logic for `recordCompletedSpan()` did not take that into consideration. Allow for this to happen and create tests to validate the the higher limits.
=> Improve validation with internally recorded completed spans

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/envelope/session/OtelPayloadMapper.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/envelope/session/SessionPayloadSourceImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/envelope/session/SessionPayloadSourceImplTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/AnrOtelMapper.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/envelope/session/OtelPayloadMapperImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/AnrModuleImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/AnrModuleSupplier.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/anr/AnrOtelMapperTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/injection/AnrModuleImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AnrFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeAnrOtelMapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeOtelPayloadMapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/injection/FakeAnrModule.kt
Log ANRs as real spans through the SDK if we are producing a final session payload. This allows for ANRs to be exported as spans when a session ends. To that end, I added a new method to take the `AnrInterval` objects and log them as real spans that will be used when a session is ending, and only use the method to produce the fake spans to stuff in a session payload snapshot before it ends when we are doing a snapshot. 
Existing tests validate that the logic change doesn't affect the final payload. Additional tests added to validate the exported spans.
=> Ensure ANR spans are exported when a session ends

embrace-gradle-plugin-integration-tests/fixtures/react-native-android/android/app/src/main/embrace-config.json, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTasksRegistration.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTasksRegistrationTest.kt
Change the logic to only register if the attribute is defined and true. The early return logic is difficult to read given that the object not being specified doesn't match and the logic proceeds.
=> Default symbol upload task registration to false if unspecified

embrace-bytecode-instrumentation-tests/src/test/java/io/embrace/gradle/plugin/instrumentation/FakeBytecodeInstrumentationParams.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/AsmTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/BytecodeInstrumentationParams.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/EmbraceClassVisitorFactory.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/instrumentation/fakes/TestBytecodeInstrumentationParams.kt
```
params.encodedSharedObjectFilesMap.set(
encodeFileToBase64Task.nullSafeMap { encodeTask ->
encodeTask.outputFile.asFile.orNull?.let { file ->
file.takeIf { it.exists() }
?.bufferedReader()
?.use { it.readText() }
}
}
)
```
Here, outputFile.asFile.orNull eagerly resolved the output file without considering whether the encode task had already produced an output. 
Now, we flatMap the task output to the Asm param input, so Gradle will consider the dependencies and avoid early resolution.
I had to move the file reading to the params class, because if it happened inside the provider, it was resolved too early. 
I still have to test this on a configuration-cache project.
=> flatMap the encode file task so it doesn't get resolved too early within the ASM task

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTasksRegistration.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTasksRegistrationTest.kt
When the ndk_enabled flag is null: 
- Native projects should not upload native files
- Unity projects should. 
This is how just to make it work like before, but we will be revisiting this behavior in the future.
=> Unity projects should upload files when ndk_enabled isn't set

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/EmbSpan.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/KotlinApiConversions.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/SpanMapper.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceExtensions.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanData.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/PersistableEmbraceSpan.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/SpanDataExt.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/payload/SpanMapperTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceTracerTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/InternalTracerTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/arch/EmbraceAttributeExtensions.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePersistableEmbraceSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/SpansTestFixtures.kt
Uses the Kotlin API for `StatusCode` rather than the OTel Java API.
=> Uses the Kotlin API for `StatusCode`

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModule.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/OpenTelemetrySdk.kt
Alters how and where the Kotlin API logger is accessed, and makes it more clear what property contains the Kotlin API.
=> Small tweak to logger definition

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/envelope/session/SessionPayloadSourceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/LogSinkImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/LogMapper.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/SpanMapper.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/SpanDataExt.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/EmbraceLogRecordDataTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/EmbraceLogRecordExporterTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/LogSinkImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/payload/LogMapperTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/payload/SpanMapperTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionServiceImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/AnrOtelMapper.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ExternalTracerTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeCurrentSessionSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakePersistableEmbraceSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/SpansTestFixtures.kt
Renames some functions that convert OpenTelemetry/Embrace model classes into Embrace payload classes, so that the naming better reflects the action taken.
=> Rename OTel conversion functions

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/EmbraceLogRecordExporter.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/opentelemetry/OpenTelemetryConfiguration.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanExporter.kt
Don't create a composite exporter if there are no custom exporters that will use it. That way, we save pushing data to an empty composite exporter.
=> Only export if there is a configured exporter

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTasksRegistration.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTasksRegistrationTest.kt
Even if a task is not executed because of its onlyIf, the tasks that depend on it will be executed (nice, gradle ✨).
For now, I'm applying the same onlyIf to every task. I'll check if there's a way of avoiding this in the future.
=> Apply onlyIf to every task

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/network/logging/EmbraceNetworkLoggingService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/EmbraceSpanService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/SpanServiceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/UninitializedSdkSpanService.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/SpanServiceImplTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbSpanBuilder.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/TracerExt.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactory.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImpl.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanImpl.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanBuilderWrapper.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanService.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbSpanBuilderTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanImplTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanBuilderWrapperTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpanService.kt
Make `OtelSpanBuilderWrapper` hold only OTel API concepts and data, and move the business logic as well as any Embrace specific concepts to the factory method (i.e. `Tracer.otelSpanBuilderWrapper()` as well as the factory class for `EmbraceSpanImpl`, i.e. `EmbraceSpanFactoryImpl`. This allows the wrapper to only hold the mapped values from the OTel API, making it a lot simpler to be replaced by the Kotlin version.
This entailed moving concepts like `AutoTerminationMode` to the right layer, including cleaning the internal API that exposes it.
Rely on existing tests
=> Clarified scope of OtelSpanBuilderWrapper and EmbraceSpanFactory

embrace-gradle-plugin-integration-tests/build.gradle.kts
Add embrace-android-otel to the modules added in the integration tests
=> Publish embrace-android-otel so integration tests can use it

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/destination/LogWriter.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/destination/LogWriterImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/arch/schema/TelemetryAttributes.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/EmbraceLogService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/logs/LogService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashService.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/network/logging/NetworkCaptureDataSourceImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionServiceImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/arch/destination/LogWriterImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/arch/schema/TelemetryAttributesTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/aei/AeiDataSourceImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/crash/CrashDataSourceImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/telemetry/InternalErrorDataSourceImpl.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/ndk/NativeCrashDataSourceImpl.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/aei/AeiDataSourceImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/crash/InternalErrorDataSourceImplTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/ndk/NativeCrashDataSourceImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/FlutterInternalInterfaceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/LogsApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/FlutterInternalInterfaceImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeLogService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeLogWriter.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeNativeCrashService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/LogEventData.kt
Tweaks the implementation to avoid referencing several OpenTelemetry concepts from within `embrace-android-features`.
=> Begin modularising otel usage

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/gating/SpanSanitizer.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/EnvelopeExt.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionServiceImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/envelope/session/SessionPayloadSourceImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/config/OtelLimitsConfigExt.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/EmbraceExt.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OtelSdkWrapper.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanExt.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/payload/SpanMapperTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/assertions/SessionPayloadEnvelopeAssertions.kt
Moves functions out of `EmbraceExt` where an existing source file for extensions exists.
=> Move functions out of EmbraceExt

embrace-android-infra/build.gradle.kts, gradle/libs.versions.toml
The recently added androidx-annotation-jvm dependency was causing a conflict in the gradle plugin integration tests that failed the build. I've added the lifecycle/runtime as a dependency instead as this brings in the annotation library as a transitive dependency.
Ran tests manually & waited on CI.
=> Fix build on CI

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/gating/SpanSanitizer.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/resurrection/PayloadResurrectionServiceImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/EmbraceTracerTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/SpanServiceImplTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/AnrOtelMapper.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/anr/AnrOtelMapperTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/activity/UiLoadTraceEmitterTest.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/StartupServiceImplTest.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/payload/SpanMapper.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/id/OtelIds.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImpl.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanExt.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ExternalTracerTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/UiLoadTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/SpansTestFixtures.kt
Reduces the direct usage of `SpanId.getInvalid()` so that it's confined to the `embrace-android-otel` module.
=> Reduce usage of spanid.getinvalid

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTasksRegistration.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/ndk/NdkUploadTasksRegistrationTest.kt
Even if a task is not executed because of its onlyIf, the tasks that depend on it will be executed (nice, gradle ✨).
For now, I'm applying the same onlyIf to every task. I'll check if there's a way of avoiding this in the future.
=> Use onlyIf in every task so they don't get executed unnecessarily

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/payload/SpanMapper.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OtelExt.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbSpanTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanImplTest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/payload/Link.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbraceSdkSpan.kt
Add additional attributes to Span Link serialized form to support linking to spans created remotely
Add unit and integration tests
=> Add additional attributes to internal span link JSON

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpan.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/schema/LinkType.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/EmbraceExt.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImpl.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanRepository.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/SessionSpanTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/assertions/LinkAssertions.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/assertions/SpanAssertions.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeCurrentSessionSpan.kt
When a span ends, add a span link to the session span as well as a span link to the current session on the span about to end. Added a bunch of test infra and tests so testing future span link features will be easier.
=> Create bidirection relationships between spans and sessions

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/UnityInternalInterfaceImpl.kt, embrace-internal-api/src/main/kotlin/io/embrace/android/embracesdk/internal/UnityInternalInterface.kt, embrace-internal-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/delegate/NoopUnityInternalInterface.kt, embrace-internal-api/src/test/kotlin/io/embrace/android/embracesdk/internal/api/NoopUnityInternalInterfaceTest.kt
Remove API that is no logger needed as Unity thread sampling is no longer supported
=> Remove thread sampler installer internal API for Unity

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/buildreporter/BuildFeaturesWrapper.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/buildreporter/BuildTelemetryCollector.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/gradle/GradleVersion.kt
BuildFeatures was introduced after Gradle 8.5 to fetch information about the build. Use that instead of StartParameter, which will be deprecated in Gradle 10.
Should fix issue #2207.
In the ExampleApp, the warning following warning was showing up when running `./gradlew build --warning-mode all`:
```
The StartParameter.isConfigurationCacheRequested property has been deprecated. This is scheduled to be removed in Gradle 10.0.
```
It doesn't show up anymore after this change.
=> Get configuration cache telemetry from BuildFeatures

embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/capture/session/EmbraceSessionPropertiesTest.kt
Added a couple of additional conditions that we don't explicitly test for session properties
=> Add explicit test for max temp session properties

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/gradle/TaskRegistrationUtils.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/AsmTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/ndk/NdkUploadTasksRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/reactnative/GenerateRnSourcemapTaskRegistration.kt
Mapped task outputs correctly to asm task parameters without using afterEvaluate. Also added a lazyTaskLookup utility function.
=> Removed afterEvaluate from AsmTaskRegistration

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt
`runCatching` doesn't handle exceptions happening on another thread. This PR fixes that issue.
=> Fix a bug where disabling the sdk might cause a background exception

build.gradle.kts, embrace-gradle-plugin/build.gradle.kts
The legacy OSSRH publishing service will be sunset on June 30th, 2025. [[Notice here]](https://central.sonatype.org/publish/publish-guide/)
[[Here]](https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/) are the differences between Legacy OSSRH and Central Portal.
I already migrated the repo through self-service migration and generated a new token, which will be set as a secret in this repo. 
This PR follows the docs on [[this page]](https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/) to use the new URLs. It seems like it's a short-term solution for the migration, as they intend users to use another API for publication. I'd wait until there's an official Gradle plugin released for Central Portal publication, or we could also …
=> Maven central portal migration

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/KotlinApiConversions.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OtelExt.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/wrapper/KotlinSpanContextWrapper.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/wrapper/KotlinTraceFlagsWrapper.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/wrapper/KotlinTraceStateWrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeKotlinSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeKotlinTracer.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeKotlinTracerProvider.kt
Creates some wrappers + fakes that are required to move over to using the Kotlin API.
This will be covered by existing tests once the internal implementation uses these objects.
=> Preparatory work for kotlin api

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/EmbraceAnrService.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/AnrModuleImpl.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/anr/EmbraceAnrServiceRule.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/anr/EmbraceAnrServiceTest.kt
I'll start working on a new use case for EmbraceAnrService tomorrow, so I'm doing some preparatory cleanup. No behavior changes, just tidying up fields initialization and access modifiers.
=> EmbraceAnrService cleanup

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/r8/JvmMappingUploadTaskRegistration.kt
Using flatMap instead of map should carry dependencies from the compression task to the upload task in JvmMappingUploadTaskRegistration.kt.
This should fix the following issue: 
```
Task ':app:jvmMappingUploadTaskForFordexguardApkOnVariantUsProduction' uses this output of task ':app:jvmMappingCompressionTaskForFordexguardAabOnVariantUsProduction' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
```
Also removed old obfuscation tasks that are not present in the gradle versions we support.
=> Dexguard fix: pass dependencies correctly between tasks

embrace-gradle-plugin-integration-tests/fixtures/react-native-android/android/build.gradle, embrace-gradle-plugin-integration-tests/fixtures/react-native-android/package.json, embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/ReactNativeAndroidTest.kt
The React Native integration test cases were failing as they used a version of Kotlin that's incompatible with what is supplied via opentelemetry-kotlin.
=> Fix react native tests

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModule.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbTracer.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OtelSdkWrapper.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/TracerExt.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImpl.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanCreator.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/wrapper/KotlinTraceFlagsWrapper.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbSpanBuilderTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OpenTelemetrySdkTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImplTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanImplTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanServiceTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanCreatorTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanServiceImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeKotlinSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeOpenTelemetryModule.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpanBuilder.kt
Alters the SDK to use opentelemetry-kotlin's implementation of `Tracer`. This is not fully complete as the tests are failing due to context propagation not being fully ported over yet. A future PR will address this problem before merging down to the integration branch.
=> Use opentelemetry-kotlin implementation of Tracer

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanCreator.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanStartArgs.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanCreatorTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/ExternalTracerTest.kt
Get the parent `SpanContext` from the context key set by the Java SDK, which will always be there. Previously, it got it from the context key set by the Embrace SDK, which would not exist if the OTel tracing API implementation was used, as is in `ExternalTracerTest`.
Fixed the tests to look for the right things. The `SpanAdapter` returned is all correct other than the fake span stored in `impl` because it was created by the FakeTracer. Also deleted an invalid test as we can really only check that the SpanContext is propagated in that test
=> Retrieve parent from the context using the context key set by the Java SDK

embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/anr/EmbraceAnrService.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/anr/EmbraceAnrServiceRule.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/anr/EmbraceAnrServiceTimingTest.kt
Adds testing for previous PR (https://github.com/embrace-io/embrace-android-sdk/pull/2260)
=> Add integration tests for background ANR monitoring stop

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/logs/EmbraceLogRecordExporter.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/logs/LogSink.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/logs/LogSinkImpl.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/StoreDataResult.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/StoreDataResultExt.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanExporter.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanSink.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanSinkImpl.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/logs/LogSinkImplTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanSinkImplTests.kt
Creates an enum that avoids using `CompleteableResultCode` from the opentelemetry-java repo.
=> Create enum for result code

embrace-android-core/lint-baseline.xml, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImpl.kt, embrace-android-otel/lint-baseline.xml, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/config/OtelSdkConfig.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbOtelJavaClock.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OtelSdkWrapper.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/config/OtelSdkConfigTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OpenTelemetrySdkTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanServiceTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanServiceImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/OTelApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/OTelApiDelegateTest.kt, embrace-test-fakes/lint-baseline.xml
Starts using the kotlin api for creating the OTel object. In a future changeset I'll swap over the API calls so that we're no longer using `OpenTelemetryJavaBuilder`.
=> Start using kotlin api for creating OTel object

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/config/OtelSdkConfig.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/logs/EmbraceOtelJavaLogRecordExporter.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/logs/EmbraceOtelJavaLogRecordProcessor.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceOtelJavaSpanExporter.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceOtelJavaSpanProcessor.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanSink.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/logs/EmbraceLogRecordExporterTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/logs/EmbraceLogRecordProcessorTest.kt
Renames the processor/exporter implementations so that it's clear they are implementing opentelemetry-java interfaces.
=> Rename exporter/processor symbols

embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/envelope/log/LogPayloadSourceImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/envelope/session/SessionPayloadSourceImplTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/logs/LogOrchestratorTest.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/logs/EmbraceOtelJavaLogRecordExporter.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/logs/LogSink.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/logs/LogSinkImpl.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceOtelJavaSpanExporter.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanSink.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanSinkImpl.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/logs/LogSinkImplTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanSinkImplTests.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/LogTestFixtures.kt
Alters the type that is accepted by the log/span sinks to depend on an embrace type rather than an OTel type.
=> Alter types for sinks

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OtelSdkWrapper.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/DefaultSpanProcessor.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/wrapper/KotlinSpanContextWrapper.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/wrapper/KotlinTraceStateWrapper.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeReadWriteLogRecord.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeReadWriteSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpanContext.kt, gradle/libs.versions.toml
Builds on https://github.com/embrace-io/opentelemetry-kotlin/pull/140 by using exporters to create an OpenTelemetry object via the Kotlin API.
=> Setup exporters correctly via Kotlin API

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImplTests.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/config/OtelSdkConfig.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceOtelJavaSpanProcessor.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanServiceTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanServiceImplTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/export/ExportedSpanValidator.kt, embrace-android-sdk/src/integrationTest/resources/system-low-power-export.json, embrace-android-sdk/src/integrationTest/resources/ux-view-export.json, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/assertions/EmbraceSpanDataAssertions.kt
Add `session.id` attribute to all spans that corresponds to the session in which they were started in
=> Add session.id attribute to spans to denote starting session

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/process/ProcessInfo.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/process/ProcessInfoImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/process/ProcessInfoImplTest.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitter.kt, embrace-android-features/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/DataCaptureServiceModuleImpl.kt, embrace-android-features/src/test/java/io/embrace/android/embracesdk/internal/capture/startup/AppStartupTraceEmitterTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeProcessInfo.kt
Create version-aware wrapper around the Android API to get process creation time. This simplifies the app startup instrumentation, and in addition allows us to use a newer API (T+) to obtain more accurate time for when the process zygote is specialized into the app process. The previous one uses the time the process is created, which could be done well before hand to reduce the latency when the app process is created.
Unfortunately, there's no way to fake the process start times using Roboletric, so while everything else is unit tested, we can't really differentiate between the two in a test. We just have to trust that API works as expected...
=> Use new API in T+ to obtain process creation request time

embrace-android-api/api/embrace-android-api.api, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/EmbraceAndroidApi.kt, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/InstrumentationApi.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/AppStartupTraceTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/SdkIntegrationTestRule.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testframework/actions/EmbraceSetupInterface.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/EmbraceImpl.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/InstrumentationApiDelegate.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/injection/ModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/FakeModuleInitBootstrapper.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/injection/ModuleInitBootstrapperTest.kt
Expose the application object init start time tracking without needing the SDK to be started or do a lot of initialization that is deferred to the SDK startup time. This involves plumbing through a clock instance created in `EmbraceImpl` as well as moving some methods around so the application init start time won't result in a set of cascading inits. This time is cached and will be used when the `applicationInitEnd()` method is called.
Right now, this allows for a better fallback for Android 23 or earlier for when the app started up, but in the future, we can track how long the application object took to initialize (or even earlier).
Added integration tests - unit tests already exist for this, as this functionality existed but just not exposed publicly.
=> Add ability to track application init time before SDK startup

embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/ReactNativeAndroidTest.kt
Update expected react native bundle ID for tests. 
I'm not quite sure about what changed, but we do have some unpinned dependencies in our package.json for this test. We could pin dependencies to a specific version, but that wouldn't allow npm fetch the latest version of embrace.
I'll just fix the test for now, and do some research later to check if there's a better way.
=> Update expected bundle id for ReactNativeAndroidTest.kt

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/payload/SpanMapper.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OtelExt.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/payload/SpanMapperTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/OTelExportTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/SessionApiTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/features/AeiFeatureTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/session/BackgroundActivityDisabledTest.kt
Removes further references to opentelemetry-java in the project
=> Remove further opentelemetry-java references

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/spans/CurrentSessionSpanImpl.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/payload/SpanMapper.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceLinkData.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSdkSpan.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImpl.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbSpanTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanImplTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbraceSdkSpan.kt
Uses the kotlin symbol for `SpanContext` links in our implementation.
=> Use kotlin symbol for SpanContext links

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModule.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/OpenTelemetryModuleImplTest.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/OTelApiDelegate.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeOpenTelemetryModule.kt
Alters `OpenTelemetryModule` to have properties for both the Java/Kotlin API and hides visibility of some properties that no longer need to be public.
=> Alter otel module

embrace-bytecode-instrumentation-tests/src/main/java/io/embrace/test/fixtures/TargetMethodEndVisitorObj.kt, embrace-bytecode-instrumentation-tests/src/test/java/io/embrace/gradle/plugin/instrumentation/InstrumentationTargetMethodEndVisitorTest.kt, embrace-bytecode-instrumentation-tests/src/test/resources/TargetMethodEndVisitorObj_expected.txt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/json/InstrumentationConfigFeaturesReader.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/json/InstrumentationConfigInsert.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/visitor/BytecodeMethodInsertionParams.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/visitor/InsertSuperOverrideClassVisitor.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/visitor/InstrumentationTargetClassVisitor.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/visitor/InstrumentationTargetMethodEndVisitor.kt
With this change, we can now add `insertAtEnd` in the insert block of an instrumentation instruction in `bytecode_instrumentation_features.json`:
```
"insert": {
...
"insertAtEnd": true
},
```
With this, we'll inject the call with ASM at the end of the method, rather than the beginning. 
"The end" is going to be any return or throw instruction, so our code will be injected immediately before those lines.
=> Add InstrumentationTargetMethodEndVisitor to inject calls at the end of methods

embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/instrumentation/bytecode/ApplicationInitTimeBytecodeEntrypoint.kt, embrace-bytecode-instrumentation-tests/src/test/java/io/embrace/gradle/plugin/instrumentation/FakeBytecodeInstrumentationParams.kt, embrace-bytecode-instrumentation-tests/src/test/java/io/embrace/gradle/plugin/instrumentation/InstrumentedBytecodeTest.kt, embrace-bytecode-instrumentation-tests/src/test/resources/TestApplication_application_init_time_end_expected.txt, embrace-bytecode-instrumentation-tests/src/test/resources/TestApplication_application_init_time_start_expected.txt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/api/EmbraceBytecodeInstrumentation.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/InstrumentationBehavior.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/InstrumentationBehaviorImpl.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/AsmTaskRegistration.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/BytecodeInstrumentationParams.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/instrumentation/VisitorFactoryImpl.kt, embrace-gradle-plugin/src/main/resources/bytecode_instrumentation_features.json, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/instrumentation/EmbraceClassVisitorFactoryTest.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/instrumentation/fakes/TestBytecodeInstrumentationParams.kt
Added bytecode instrumentation for adding calls to applicationInitStart and applicationInitEnd on any Application.onCreate()
The resulting code should look like this: 
```
class TestApplication : Application() {
override fun onCreate() {
// inject call to applicationInitStart
super.onCreate()
// inject call to applicationInitEnd
}
}
```
Added bytecode instrumentation tests 
Tested manually:
=> Instrument calls to applicationInitStart and applicationInitEnd

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/payload/SpanMapper.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/id/OtelIds.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/payload/SpanMapperTest.kt
Migrates from OTel Java to OTel Kotlin for getting span/trace IDs.
=> Use otel-kotlin symbols for id

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/EmbraceGradlePluginDelegate.kt
The code used to check `!AgpVersion.isAtLeast(AgpVersion.AGP_8_3_0)` but a refactor turned it into `agpExtension.version <= AgpVersion.AGP_8_3_0`. Restore the old logic so 8.3.0 becomes a valid version again.
This will be tested in a test that Fran is adding
=> Allow AGP 8.3.0 to be used with desugaring enabled

embrace-android-api/api/embrace-android-api.api, embrace-android-api/build.gradle.kts, embrace-android-api/src/main/kotlin/io/embrace/android/embracesdk/internal/api/OTelApi.kt, embrace-android-sdk/api/embrace-android-sdk.api, embrace-android-sdk/build.gradle.kts, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/Embrace.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/api/delegate/OTelApiDelegate.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/api/delegate/OTelApiDelegateTest.kt, gradle/libs.versions.toml
Adds an entrypoint for accessing OTel kotlin as an escape hatch. This is marked as an experimental API so will be subject to change without warning.
=> Add entrypoint for OTel kotlin

examples/ExampleApp/app/src/main/embrace-config.json
Remove test appId from the sample app. It should be specified locally in the environment config.
=> Remove appId from sample app

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbSpan.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImpl.kt
Makes span wrappers implement `ImplicitContextKeyed` so they can delegate how context is propagated.
=> Make span wrappers implement ImplicitContextKeyed

gradle.properties
Enables parallel caching for Gradle's configuration cache, and tweaks a few other build options that should improve build perf.
=> Enable CC parallel cache

embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbOtelJavaOpenTelemetryTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbOtelJavaSpanBuilderTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbOtelJavaSpanTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbOtelJavaTracerBuilderTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbOtelJavaTracerProviderTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbOtelJavaTracerTest.kt
Some tests files were not renamed when their associated classes were renamed with the `OtelJava` token to declare that they are implementations of the Java API.
This caused a bit of confusion when I saw what `EmbSpanTest` was testing - it wasn't `EmbSpan`, the Kotlin API impl....
=> Rename a bunch of test files to match their subjects

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbSpan.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbTracer.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/IdGenerator.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSdkSpan.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImpl.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanStartArgs.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanServiceImpl.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbSpanTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbTracerProviderTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbTracerTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/payload/SpanMapperTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImplTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanImplTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/OtelSpanStartArgsTest.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/spans/SpanRepositoryTest.kt, embrace-android-sdk/src/integrationTest/kotlin/io/embrace/android/embracesdk/testcases/TracingApiTest.kt, embrace-test-fakes/build.gradle.kts, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbraceSdkSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeOtelJavaSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSession.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpanBuilder.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpanService.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fixtures/SpansTestFixtures.kt
Uses opentelemetry-kotlin's symbols for `Context` where possible.
=> Use opentelemetry-kotlin context symbols

embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/EmbraceGradlePluginDelegate.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/PluginBehavior.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/config/PluginBehaviorImpl.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/registration/TaskRegistrar.kt, embrace-gradle-plugin/src/test/java/io/embrace/android/gradle/plugin/config/PluginBehaviorImplTest.kt
- Use `withPlugin("com.facebook.react")` instead of checking `node_modules/react-native` directory.
- Create separate task registration flow for React Native specific tasks.
Uses Gradle's plugin system instead of file system checks, which are failing for some customers. This should be configuration-cache safe, as it's the same thing we use for waiting for AGP. React Native tasks still register only when the React Native plugin is detected
- Remove `isReactNativeProject` property from `PluginBehavior`
- Add `withPlugin("com.facebook.react")` detection in `EmbraceGradlePluginDelegate` 
- Create `registerReactNativeTasks()` method for RN-specific task registration
- Extract shared methods to reduce code duplication
- Update tests to remove obsolete React Native detection logic
=> Improve React Native project detection in gradle plugin

embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceHttpUrlStreamHandler.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/EmbraceHttpsUrlStreamHandler.java, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/HttpUrlConnectionUtils.kt, embrace-android-sdk/src/main/java/io/embrace/android/embracesdk/internal/network/http/StreamHandlerFactoryInstaller.java, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/network/http/FakeURLStreamHandler.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/internal/network/http/HttpUrlConnectionUtilsTest.kt
Traverse up the object hierarchy to find the `openConnection` method to be invoked in an existing URLStreamingHandler installed on an app before the Embrace SDK started. Previously, we were only looking in the wrapped class, but it could have inherited the method from an ancestor instead.
=> Look for openConnection method in ancestor of wrapped URLStreamHandler

.github/workflows/pre-release-workflow.yml
The pre-release workflow was failing with "Could not read PGP secret key" when trying to sign Maven publications. This occurred because reusable workflows don't automatically inherit secrets from the calling workflow, even when the secrets are referenced in the `env` section of the called workflow.
The fix adds `secrets: inherit` to the `upload-artifacts-to-sonatype` job in the pre-release workflow, allowing the Maven Central upload workflow to access the required PGP signing secrets.
=> Fix PGP signing error in pre-release workflow by inheriting secrets

embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/config/source/OkHttpRemoteConfigSource.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/CoreModule.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/CoreModuleImpl.kt, embrace-android-core/src/main/kotlin/io/embrace/android/embracesdk/internal/injection/PayloadSourceModuleImpl.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/comms/api/ApiRequestTest.kt, embrace-android-core/src/test/java/io/embrace/android/embracesdk/internal/injection/CoreModuleImplTest.kt, embrace-android-payload/build.gradle.kts, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/capture/metadata/AppEnvironment.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/ApiRequest.kt, embrace-android-payload/src/main/kotlin/io/embrace/android/embracesdk/internal/comms/api/HttpMethod.kt, embrace-android-payload/src/test/kotlin/io/embrace/android/embracesdk/internal/payload/EmbraceSerializerTest.kt, embrace-android-sdk/src/test/java/io/embrace/android/embracesdk/fakes/injection/FakeCoreModule.kt
Updates the embrace-android-payload module so that it doesn't depend on other modules in the project.
=> Make embrace-android-payload more isolated

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/io/embrace/internal/AndroidCompileConfig.kt, buildSrc/src/main/kotlin/io/embrace/internal/EmbraceBuildLogicExtension.kt
We only require Java 11 at build time, so bumping the minimum java version was a mistake. Rolling it back, at least until the next major
=> Revert Java bump

.github/workflows/android-emulator-tests.yml, embrace-microbenchmark/build.gradle.kts
[Dry run mode](https://developer.android.com/topic/performance/benchmarking/microbenchmark-instrumentation-args#dryrunmode-enable) means the benchmark tests only run once without any warm up, so are not as accurate. Removing this should give us more meaningful benchmarking results, at the price of longer execution times.
=> Tweak microbenchmark arguments

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbSpan.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSdkSpan.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImpl.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OpenTelemetrySdkTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbraceSdkSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeOpenTelemetryModule.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpanService.kt
`ImplicitContextKeyed` forces us to include `opentelemetry-java` as a dependency, and it's not really used anymore.
- `FakeEmbraceSdkSpan` contained a Java and a Kotlin span. This didn't make sense, as the actual `EmbraceSdkSpan` only has one kotlin Span implementation.
- `EmbraceSdkSpan` and `EmbSpan` do not extend `ImplicitContextKeyed` anymore. The context operations that are actually used are handled by `opentelemetry-kotlin`. If `opentelemetry-java` is used, `opentelemetry-kotlin` will call the appropiate compat classes.
=> Remove ImplicitContextKeyed from EmbSpan and EmbraceSdkSpan

embrace-android-api/build.gradle.kts, embrace-android-core/build.gradle.kts, embrace-android-features/build.gradle.kts, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbSpan.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSdkSpan.kt, embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/spans/EmbraceSpanFactoryImpl.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/sdk/OpenTelemetrySdkTest.kt, embrace-android-sdk/build.gradle.kts, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbraceSdkSpan.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeOpenTelemetryModule.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeSpanService.kt
Remove unused opentelemetry-java dependencies from different gradle files.
_Still haven't removed testImplementation and androidTestImplementation dependencies, as tests haven't been correctly separated yet._
=> Remove otel-java gradle deps from embrace-android-core

embrace-gradle-plugin-integration-tests/src/test/java/io/embrace/android/gradle/integration/testcases/MissingConfigFileTest.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/EmbraceGradlePluginDelegate.kt, embrace-gradle-plugin/src/main/java/io/embrace/android/gradle/plugin/tasks/registration/TaskRegistrar.kt
Disabling the plugin for certain variants or setting up the `disableMappingFileUpload` flag should disable the upload of our telemetry. 
We should also review our flags in the future. `embrace.disableMappingFileUpload` might not be ample enough, and it does disable NDK, Unity, RN, Proguard, and any other kind of uploads.
=> BuildTelemetryService should not upload telemetry if upload tasks are disabled.

embrace-android-otel/src/main/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbTracer.kt, embrace-android-otel/src/test/kotlin/io/embrace/android/embracesdk/internal/otel/impl/EmbTracerTest.kt, embrace-test-fakes/src/main/kotlin/io/embrace/android/embracesdk/fakes/FakeEmbraceSdkSpan.kt
Propagates the parameters supplied to `EmbTracer` correctly.
Added a unit test.
=> Propagate EmbTracer arguments correctly
